/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library


__attribute__((visibility("hidden")))
@interface __DeallocNotifier : NSObject {
@private
	id block;	// 4 = 0x4
	id object;	// 8 = 0x8
	BOOL _retainsNoLongerAllowed;	// 12 = 0xc
}
+ (void)object:(id)object attachDeallocationBlock:(id)block;	// 0x34dcfac1
- (id)init;	// 0x34dcfb41
- (void)dealloc;	// 0x34dcfb6d
- (id)retain;	// 0x34dcfb45
@end

