/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRController.h"

@class BRAirportNetwork, BRTextControl, BRWaitSpinnerControl, BRHeaderControl;
@protocol ATVAPTestResultDelegate;

@interface ATVAPTestController : BRController {
@private
	BRWaitSpinnerControl *_spinner;	// 60 = 0x3c
	BRAirportNetwork *_network;	// 64 = 0x40
	BOOL _testFailed;	// 68 = 0x44
	id<ATVAPTestResultDelegate> _delegate;	// 72 = 0x48
	BRHeaderControl *_header;	// 76 = 0x4c
	BRTextControl *_prompt;	// 80 = 0x50
}
- (id)initForNetwork:(id)network notifying:(id)notifying;	// 0x34c3aae1
- (void)_testFinished:(id)finished;	// 0x34c3affd
- (void)_testInternetConnection;	// 0x34c3afcd
- (void)dealloc;	// 0x34c3ad01
- (void)setFrame:(CGRect)frame;	// 0x34c3adb5
- (void)wasExhumed;	// 0x34c3af91
- (void)wasPushed;	// 0x34c3af55
@end

