/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library


__attribute__((visibility("hidden")))
@interface ATVAsyncNetworkTest : NSObject {
}
+ (void)performAsyncTest;	// 0x34c3b461
- (id)_performTest;	// 0x34c3b571
- (void)_testCompleted:(id)completed;	// 0x34c3b665
- (void)dealloc;	// 0x34c3b51d
@end

