/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRTextEntryController.h"


__attribute__((visibility("hidden")))
@interface ATVAPNameEntryController : BRTextEntryController {
}
+ (void)initialize;	// 0x34c391a9
- (id)init;	// 0x34c3922d
@end

