/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVReadOnlyFeedResource.h"
#import <Foundation/Foundation.h> // Unknown library

@class NSString, NSBundle;

__attribute__((visibility("hidden")))
@interface ATVBundleFeedResource : NSObject <ATVReadOnlyFeedResource> {
@private
	NSString *_basePath;	// 4 = 0x4
	NSBundle *_bundle;	// 8 = 0x8
}
@property(readonly, assign, nonatomic) NSString *path;	// G=0x34c9de71; 
+ (void)initialize;	// 0x34c9dd05
- (id)initWithBundlePath:(id)bundlePath;	// 0x34c9dd69
- (void)dealloc;	// 0x34c9de19
- (id)feedResourceNamed:(id)named;	// 0x34c9de81
// declared property getter: - (id)path;	// 0x34c9de71
@end

