/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "MSSubscriberDelegate.h"
#import "MSMediaStreamDaemonDelegate.h"
#import "MSSubscriberPlugin.h"
#import "AppleTV-Structs.h"
#import <Foundation/Foundation.h> // Unknown library

@class NSString, MSMediaStreamDaemon, NSMutableArray, ATVCupidImageRetrievalTask, NSDictionary, ATVCupidUpdateTask, NSMutableDictionary;
@protocol MSSharingManager, MSSubscriber;

__attribute__((visibility("hidden")))
@interface ATVCupidDataClientImpl : NSObject <MSSubscriberDelegate, MSMediaStreamDaemonDelegate, MSSubscriberPlugin> {
@private
	id<MSSharingManager> _sharingManager;	// 4 = 0x4
	NSDictionary *_manifest;	// 8 = 0x8
	NSMutableArray *_queuedManifestAssets;	// 12 = 0xc
	NSMutableArray *_retrievingManifestAssets;	// 16 = 0x10
	NSMutableArray *_waitingToRetrieveManifestAssets;	// 20 = 0x14
	NSMutableDictionary *_imageManagers;	// 24 = 0x18
	NSString *_baseCachePath;	// 28 = 0x1c
	BOOL _pollingForUpdates;	// 32 = 0x20
	BOOL _processingUpdateRequest;	// 33 = 0x21
	ATVCupidUpdateTask *_updateTask;	// 36 = 0x24
	ATVCupidImageRetrievalTask *_imageRetrievalTask;	// 40 = 0x28
	ATVDataClientRef _dataClient;	// 44 = 0x2c
	id<MSSubscriber> _subscriber;	// 48 = 0x30
	MSMediaStreamDaemon *_daemon;	// 52 = 0x34
	ATVMediaQueryRef _pendingQuery;	// 56 = 0x38
}
@property(readonly, assign) MSMediaStreamDaemon *daemon;	// G=0x34cad1e1; @synthesize=_daemon
@property(assign) ATVDataClientRef dataClient;	// G=0x34cad1b1; S=0x34cad1c1; @synthesize=_dataClient
@property(readonly, assign) ATVMediaQueryRef pendingQuery;	// G=0x34cad1f1; @synthesize=_pendingQuery
@property(readonly, assign) id<MSSubscriber> subscriber;	// G=0x34cad1d1; @synthesize=_subscriber
+ (id)personIDsForPollingTriggeredByPushNotification;	// 0x34caca85
+ (id)subscriberPluginForPersonID:(id)personID;	// 0x34caca69
- (id)init;	// 0x34cac56d
- (id)_account;	// 0x34cae64d
- (void)_accountAuthenticationFailed:(id)failed;	// 0x34cae5dd
- (void)_accountAuthenticationSucceeded:(id)succeeded;	// 0x34cae55d
- (id)_collectionsFromManifest:(id)manifest;	// 0x34cad7e9
- (void)_commitManifest;	// 0x34cad2c5
- (id)_createImageManagerForStreamID:(id)streamID;	// 0x34cadf51
- (void)_cupidNotVisible:(id)visible;	// 0x34cae4e9
- (void)_cupidVisible:(id)visible;	// 0x34cae4d1
- (id)_imageManagerCachePathForStreamID:(id)streamID;	// 0x34cae00d
- (id)_imageManagerForStreamID:(id)streamID;	// 0x34cadec5
- (id)_imageManagersFromManifest:(id)manifest;	// 0x34cae05d
- (id)_itemIDForAsset:(id)asset;	// 0x34cae755
- (id)_itemsForStreamID:(id)streamID;	// 0x34cae7f5
- (id)_manifest;	// 0x34cad201
- (id)_manifestAssetsForAsset:(id)asset;	// 0x34cad669
- (id)_manifestAssetsForStreamID:(id)streamID;	// 0x34cad5ad
- (id)_manifestDictForStreamID:(id)streamID;	// 0x34cad31d
- (id)_manifestEmailForStreamID:(id)streamID;	// 0x34cad50d
- (id)_manifestFirstNameForStreamID:(id)streamID;	// 0x34cad3cd
- (id)_manifestLastNameForStreamID:(id)streamID;	// 0x34cad46d
- (void)_pollForUpdates;	// 0x34cae17d
- (void)_preferredAccountRemoved:(id)removed;	// 0x34cae501
- (id)_queuedManifestAssetsFromManifest:(id)manifest;	// 0x34cadc29
- (void)_removeImageManagerForStreamID:(id)streamID;	// 0x34cae135
- (void)_resetForAccount:(id)account;	// 0x34cae695
- (void)_retrieveAssets:(id)assets;	// 0x34cadea5
- (void)_retrieveManifestAsset:(id)asset;	// 0x34cadd91
- (void)_retrieveNextImageRequested:(id)requested;	// 0x34cae365
- (void)_setManifest:(id)manifest;	// 0x34cad231
- (void)_setManifestAssets:(id)assets forStreamID:(id)streamID;	// 0x34cad5f5
- (void)_setManifestDict:(id)dict forStreamID:(id)streamID;	// 0x34cad361
- (void)_setManifestEmail:(id)email forStreamID:(id)streamID;	// 0x34cad539
- (void)_setManifestFirstName:(id)name forStreamID:(id)streamID;	// 0x34cad3f9
- (void)_setManifestLastName:(id)name forStreamID:(id)streamID;	// 0x34cad499
- (void)_setPollingForUpdates:(BOOL)updates;	// 0x34cae1cd
- (void)_startUpdate;	// 0x34cae341
- (void)_startUpdateTaskWithSlowInterval:(BOOL)slowInterval;	// 0x34cae3ed
- (void)_updateMetadataForShares;	// 0x34caea5d
- (void)_updateRequested:(id)requested;	// 0x34cae219
- (void)connect;	// 0x34cac8d1
// declared property getter: - (id)daemon;	// 0x34cad1e1
// declared property getter: - (ATVDataClientRef)dataClient;	// 0x34cad1b1
- (void)dealloc;	// 0x34cac7e5
- (void)disconnect;	// 0x34cac98d
- (void)mediaStreamDaemonDidIdle:(id)mediaStreamDaemon;	// 0x34caca61
- (void)mediaStreamDaemonDidUnidle:(id)mediaStreamDaemon;	// 0x34caca65
// declared property getter: - (ATVMediaQueryRef)pendingQuery;	// 0x34cad1f1
- (void)processQuery:(ATVMediaQueryRef)query;	// 0x34cac991
// declared property setter: - (void)setDataClient:(ATVDataClientRef)client;	// 0x34cad1c1
// declared property getter: - (id)subscriber;	// 0x34cad1d1
- (void)subscriber:(id)subscriber didFailToRetriveSubscriptionUpdateWithError:(id)error;	// 0x34cacf6d
- (void)subscriber:(id)subscriber didFindDisappearedSubscriptionforStreamID:(id)anId;	// 0x34cacfb1
- (void)subscriber:(id)subscriber didFinishRetrievingAsset:(id)asset error:(id)error;	// 0x34cacc6d
- (void)subscriber:(id)subscriber didRequestAssetRetrievalForAssetCollections:(id)assetCollections streamID:(id)anId;	// 0x34cacacd
- (void)subscriber:(id)subscriber didResetSyncForStreamID:(id)streamID;	// 0x34cad165
- (void)subscriberDidCompleteCheckForNewAssetCollections:(id)subscriber;	// 0x34cad049
- (void)subscriberWillAssignPluginAsDelegateOfSubscriber:(id)subscriber;	// 0x34caca89
- (void)subscriberWillCheckForNewAssetCollections:(id)subscriber;	// 0x34cacfa5
- (void)subscriberWillDeassignPluginAsDelegateOfSubscriber:(id)subscriber;	// 0x34cacaa5
@end

