/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */



@protocol ATVCatalogAgent
+ (void)acquireItem:(id)item;
+ (id)allLeafItemsForItem:(id)item;
+ (id)catalogHandler;
+ (void)checkForPurchases;
+ (id)configureRelatedControlsFromControl:(id)control style:(int)style;
+ (id)controlForItem:(id)item;
+ (void)controlForObject:(id)object;
+ (void)controlForObject:(id)object merchant:(id)merchant;
+ (id)coverArtForItem:(id)item;
+ (id)coverArtURLForItem:(id)item featured:(BOOL)featured thumbnail:(BOOL)thumbnail;
+ (long)downloadItem:(id)item;
+ (id)episodeArtURLForItem:(id)item;
+ (BOOL)isItemFeatured:(id)featured;
+ (BOOL)isItemOrdered:(id)ordered;
+ (BOOL)isTemplateParameterSet:(id)set forItem:(id)item;
+ (long)itemIDForItem:(id)item;
+ (int)itemType:(id)type;
+ (id)mediaAssetForStoreOffer:(id)storeOffer;
+ (id)mediaTypeForItem:(id)item;
+ (void)playStoreItem:(id)item;
+ (id)plistFromURLDocument:(id)urldocument;
+ (void)registerClass:(Class)aClass withTemplateName:(id)templateName;
+ (void)sendPingForItem:(id)item;
+ (void)setDownloadFunction:(/*function-pointer*/ void *)function;
+ (void)setPurchaseFunction:(/*function-pointer*/ void *)function;
+ (void)setRentalFunction:(/*function-pointer*/ void *)function;
+ (void)setSubscribeFunction:(/*function-pointer*/ void *)function;
+ (BOOL)showAllTitles:(id)titles;
+ (BOOL)showTitleAndSubtitle:(id)subtitle;
+ (BOOL)storeVersionIsCompatibileForPageDictionary:(id)pageDictionary redirectURL:(id *)url;
+ (void)subscribeToItem:(id)item;
@end

