/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRBackgroundTask.h"

@class BRDownloadManager;

@interface ATVDownloadsPeriodicCheckForPurchasesMonitor : BRBackgroundTask {
@private
	BRDownloadManager *_downloadManager;	// 44 = 0x2c
	BOOL _currentlyPerformingAccountAuthentication;	// 48 = 0x30
	BOOL _currentlyPerformingAutomaticCheckForDownloads;	// 49 = 0x31
	int _failedAuthCount;	// 52 = 0x34
}
+ (BOOL)isCurrentlyAuthenticatingAccount;	// 0x34bf277d
+ (BOOL)isCurrentlyCheckingForDownloads;	// 0x34bf2771
- (id)initWithInterval:(double)interval delay:(double)delay userInfo:(id)info taskType:(int)type;	// 0x34bf2789
- (void)_accountAuthenticationDidComplete:(id)_accountAuthentication;	// 0x34bf2a39
- (void)_acquisitionFailure:(id)failure;	// 0x34bf2bdd
- (void)_checkForPurchases;	// 0x34bf29bd
- (void)_checkingForPurchasesDidComplete:(id)_checkingForPurchases;	// 0x34bf2d45
- (void)dealloc;	// 0x34bf2869
- (void)enable;	// 0x34bf28d5
- (BOOL)perform:(id)perform;	// 0x34bf290d
@end

