/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVDotMacParserDelegate.h"

@class NSString, NSArray, NSDate, NSDictionary;

__attribute__((visibility("hidden")))
@interface ATVDotMacAlbumDelegate : ATVDotMacParserDelegate {
@private
	NSString *_keyImageID;	// 24 = 0x18
	NSArray *_imageOrder;	// 28 = 0x1c
	NSDate *_modDate;	// 32 = 0x20
	NSDictionary *_startSelectors;	// 36 = 0x24
	NSDictionary *_endSelectors;	// 40 = 0x28
}
@property(readonly, retain) NSDictionary *endSelectors;	// G=0x34bfa6bd; converted property
@property(readonly, retain) NSDate *modDate;	// G=0x34bfa995; converted property
@property(readonly, retain) NSDictionary *startSelectors;	// G=0x34bfa6ad; converted property
- (id)init;	// 0x34bf9fcd
- (void)__atv_end_dotmac_keyImagePath;	// 0x34bfa391
- (void)__atv_end_dotmac_largeImagePath;	// 0x34bfa4d9
- (void)__atv_end_dotmac_moviePath;	// 0x34bfa5f1
- (void)__atv_end_dotmac_title;	// 0x34bfa4a1
- (void)__atv_end_dotmac_userHidden;	// 0x34bfa549
- (void)__atv_end_dotmac_useritemguid;	// 0x34bfa581
- (void)__atv_end_dotmac_userorder;	// 0x34bfa3d5
- (void)__atv_end_dotmac_videoDuration;	// 0x34bfa629
- (void)__atv_end_dotmac_viewIdentifier;	// 0x34bfa431
- (void)__atv_end_dotmac_webImagePath;	// 0x34bfa511
- (void)__atv_end_iphoto_photoDate;	// 0x34bfa5b9
- (void)__atv_end_title;	// 0x34bfa469
- (void)__atv_end_updated;	// 0x34bfa661
- (id)albumID;	// 0x34bfa959
- (id)albumName;	// 0x34bfa9a5
- (void)dealloc;	// 0x34bfa305
// converted property getter: - (id)endSelectors;	// 0x34bfa6bd
- (int)imageCount;	// 0x34bfa935
- (id)itemInfos;	// 0x34bfa6cd
- (id)keyImageInfo;	// 0x34bfa885
// converted property getter: - (id)modDate;	// 0x34bfa995
- (id)sortedItemInfos;	// 0x34bfa82d
// converted property getter: - (id)startSelectors;	// 0x34bfa6ad
@end

