/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVInternetPhotosMonitor.h"

@class BRBackgroundTask;

@interface ATVDotMacMonitor : ATVInternetPhotosMonitor {
@private
	BRBackgroundTask *_backgroundTask;	// 32 = 0x20
}
@property(readonly, retain) BRBackgroundTask *backgroundTask;	// G=0x34bfff69; converted property
+ (void)initialize;	// 0x34bff599
+ (void)setSingleton:(id)singleton;	// 0x34bff58d
+ (id)singleton;	// 0x34bff581
- (id)init;	// 0x34bff5f9
- (void)_addCollectionForTemporaryDataMonitoring:(id)temporaryDataMonitoring;	// 0x34c02f31
- (id)_authenticationsForAccountWithName:(id)name;	// 0x34c02c39
- (void)_collectionLoadFailure:(id)failure newCollectionInfo:(id)info status:(int)status;	// 0x34c01d55
- (id)_dataForRelativePath:(id)relativePath forAccountWithName:(id)name secondaryAccount:(id)account;	// 0x34c0223d
- (BOOL)_isAccountRegisteredForDataMonitoring:(id)dataMonitoring;	// 0x34c02e85
- (void)_performAccountIconImageLoad:(id)load;	// 0x34c01e95
- (void)_performAccountLoad:(id)load;	// 0x34c001f1
- (void)_performAccountMediaLoad:(id)load;	// 0x34c00361
- (void)_performAssetCoverArtImageLoad:(id)load;	// 0x34c01e55
- (void)_performAssetFullSizeImageLoad:(id)load;	// 0x34c01e75
- (void)_performAssetImageLoad:(id)load sizeKey:(id)key;	// 0x34c01f51
- (void)_performAssetThumbnailImageLoad:(id)load;	// 0x34c01e35
- (void)_performAuthenticateCollection:(id)collection;	// 0x34bfff79
- (void)_performCollectionAssetsLoad:(id)load;	// 0x34c00c4d
- (void)_performCollectionAssetsLoadForPhotoCollection:(id)photoCollection;	// 0x34c00d01
- (void)_performCollectionAssetsLoadForVideoCollection:(id)videoCollection;	// 0x34c015bd
- (id)_queryParamsForPath:(id)path;	// 0x34c02c9d
- (void)_saveAuthenticationForAccountWithName:(id)name secondaryAccount:(id)account;	// 0x34c02dad
- (id)_transactionForAccountWithName:(id)name path:(id)path depth:(int)depth secondaryAccount:(id)account;	// 0x34c02955
- (int)_xmlDataForRelativePath:(id)relativePath withDepth:(int)depth forAccountWithName:(id)name withParserDelegate:(id)parserDelegate;	// 0x34c02901
- (id)_xmlDataForRelativePath:(id)relativePath withDepth:(int)depth forAccountWithName:(id)name withParserDelegate:(id)parserDelegate secondaryAccount:(id)account requiresAuthentication:(BOOL)authentication;	// 0x34c02529
- (void)authenticateCollection:(id)collection withUserName:(id)userName password:(id)password;	// 0x34bff761
// converted property getter: - (id)backgroundTask;	// 0x34bfff69
- (void)cancelAuthenticateForCollection:(id)collection;	// 0x34bffb29
- (void)cancelLoadAccountIconForAccount:(id)account;	// 0x34bffefd
- (void)cancelLoadAccountWithName:(id)name;	// 0x34bffb89
- (void)cancelLoadAssetsForCollection:(id)collection;	// 0x34bffcdd
- (void)cancelLoadCoverArtImageForAsset:(id)asset;	// 0x34bffe3d
- (void)cancelLoadFullSizeImageForAsset:(id)asset;	// 0x34bffe9d
- (void)cancelLoadMediaForAccount:(id)account;	// 0x34bffbe1
- (void)cancelLoadThumbnailImageForAsset:(id)asset;	// 0x34bffddd
- (void)dealloc;	// 0x34bff67d
- (void)loadAccountIconForAccount:(id)account;	// 0x34bffab9
- (void)loadAccountWithName:(id)name;	// 0x34bff825
- (void)loadAssetsForCollection:(id)collection;	// 0x34bff8f1
- (void)loadCoverArtImageForAsset:(id)asset;	// 0x34bff9d9
- (void)loadFullSizeImageForAsset:(id)asset;	// 0x34bffa49
- (void)loadMediaForAccount:(id)account;	// 0x34bff881
- (void)loadThumbnailImageForAsset:(id)asset;	// 0x34bff969
- (void)removeAccountWithName:(id)name;	// 0x34bff6f9
- (id)taskContext;	// 0x34bfff5d
@end

