/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRSingleton.h"


@interface ATVDiskSpaceManager : BRSingleton {
}
+ (void)setSingleton:(id)singleton;	// 0x34bf02c1
+ (id)singleton;	// 0x34bf02b5
- (id)init;	// 0x34bf02cd
- (id)_volumeSizeStringForSize:(unsigned long long)size;	// 0x34bf0505
- (void)dealloc;	// 0x34bf02f5
- (unsigned long long)mediaCapacity;	// 0x34bf03bd
- (id)mediaCapacityString;	// 0x34bf0435
- (unsigned long long)mediaFreeSpace;	// 0x34bf0461
- (id)mediaFreeSpaceString;	// 0x34bf04d9
- (unsigned long long)primaryStreamedMediaRepositorySize;	// 0x34bf031d
- (unsigned long long)primaryStreamedMediaRespositoryMaxFileSize;	// 0x34bf0385
- (unsigned long long)shortContentStreamedMediaRepositorySize;	// 0x34bf03a1
- (unsigned long long)shortContentStreamedMediaRespositoryMaxFileSize;	// 0x34bf03a9
@end

