/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRControl.h"
#import "AppleTV-Structs.h"

@class BRImageControl, BRTextControl, ATVMultistateProgressIndicator, BRMarqueeTextControl;

__attribute__((visibility("hidden")))
@interface ATVDownloadMenuItem : BRControl {
@private
	BRMarqueeTextControl *_downloadTitle;	// 44 = 0x2c
	BRImageControl *_downloadOrPauseButtonImage;	// 48 = 0x30
	ATVMultistateProgressIndicator *_progressIndicator;	// 52 = 0x34
	BRTextControl *_statusText;	// 56 = 0x38
	BRTextControl *_percentCompleteText;	// 60 = 0x3c
	float _percentComplete;	// 64 = 0x40
}
+ (id)_downloadButtonImage;	// 0x34bf1a89
+ (id)_pauseButtonImage;	// 0x34bf1ae1
+ (void)_setStateGraphicsOnProgressIndicator:(id)indicator;	// 0x34bf1b91
+ (id)_statusTextAttributes;	// 0x34bf1b39
- (id)init;	// 0x34bf0e29
- (void)_downloadStateChangedNotificationHandler:(id)handler;	// 0x34bf1fe9
- (void)_requeryAssetAndUpdateUI;	// 0x34bf1db9
- (void)_setDownloadStateForDownload:(id)download;	// 0x34bf17fd
- (void)_setPercentComplete:(float)complete;	// 0x34bf194d
- (void)_setStatusText:(id)text;	// 0x34bf1779
- (void)_setTitle:(id)title;	// 0x34bf1675
- (void)_updateRequestNotificationHandler:(id)handler;	// 0x34bf2071
- (void)controlWasFocused;	// 0x34bf15cd
- (void)controlWasUnfocused;	// 0x34bf15e1
- (void)dealloc;	// 0x34bf1125
- (CGRect)focusCursorFrame;	// 0x34bf15f5
- (void)layoutSubcontrols;	// 0x34bf11d9
- (void)setDownload:(id)download;	// 0x34bf15a5
@end

