/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */



@protocol ATVDotMacAuthentication
@property(assign) BOOL initialAuthCheckComplete;	// converted property
@property(assign) BOOL requiresAuthentication;	// converted property
@property(retain) id secondaryAccount;	// converted property
// converted property getter: - (BOOL)initialAuthCheckComplete;
- (BOOL)isAuthenticated;
// converted property getter: - (BOOL)requiresAuthentication;
// converted property getter: - (id)secondaryAccount;
// converted property setter: - (void)setInitialAuthCheckComplete:(BOOL)complete;
// converted property setter: - (void)setRequiresAuthentication:(BOOL)authentication;
// converted property setter: - (void)setSecondaryAccount:(id)account;
@end

