/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRSelectionHandler.h"
#import <Foundation/Foundation.h> // Unknown library


__attribute__((visibility("hidden")))
@interface ATVDotMacPhotoSelectionHandler : NSObject <BRSelectionHandler> {
}
+ (id)selectionHandler;	// 0x34c59ce9
- (BOOL)handleSelectionForControl:(id)control;	// 0x34c59d19
@end

