/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVDotMacProvider.h"

@class ATVInternetPhotosAccount, NSSet, NSArray;

__attribute__((visibility("hidden")))
@interface ATVDotMacProviderForAccount : ATVDotMacProvider {
@private
	ATVInternetPhotosAccount *_account;	// 28 = 0x1c
	NSSet *_ignoredMediaCollectionTypes;	// 32 = 0x20
	NSArray *_dataWithTypeDividers;	// 36 = 0x24
	BOOL _disableTypeDividers;	// 40 = 0x28
}
@property(readonly, retain) ATVInternetPhotosAccount *account;	// G=0x34c05c7d; converted property
@property(retain) NSSet *ignoredMediaCollectionTypes;	// G=0x34c060cd; S=0x34c060dd; converted property
+ (id)providerForAccount:(id)account;	// 0x34c05a5d
- (id)initWithAccount:(id)account;	// 0x34c05a9d
- (id)_data;	// 0x34c05f29
- (id)_dataWithTypeDividers;	// 0x34c05dc1
- (BOOL)_handlesObject:(id)object;	// 0x34c05f9d
- (void)_updateDataCount;	// 0x34c060a5
// converted property getter: - (id)account;	// 0x34c05c7d
- (id)dataAtIndex:(long)index;	// 0x34c05cc1
- (long)dataCount;	// 0x34c05c9d
- (void)dealloc;	// 0x34c05bb1
- (id)hashForDataAtIndex:(long)index;	// 0x34c05d21
// converted property getter: - (id)ignoredMediaCollectionTypes;	// 0x34c060cd
- (void)setDisableTypeDividers:(BOOL)dividers;	// 0x34c05c8d
// converted property setter: - (void)setIgnoredMediaCollectionTypes:(id)types;	// 0x34c060dd
@end

