/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRTextFieldDelegate.h"
#import "BRController.h"

@class BRTextControl, ATVIPv4AddressEntryControl, NSString, BRHeaderControl;
@protocol ATVDottedQuadEntryDelegate;

@interface ATVDottedQuadEntryController : BRController <BRTextFieldDelegate> {
@private
	id<ATVDottedQuadEntryDelegate> _delegate;	// 60 = 0x3c
	ATVIPv4AddressEntryControl *_editor;	// 64 = 0x40
	BRTextControl *_prompt;	// 68 = 0x44
	BRHeaderControl *_header;	// 72 = 0x48
	NSString *_dottedQuad;	// 76 = 0x4c
}
@property(retain) NSString *dottedQuad;	// G=0x34c079a1; S=0x34c079b1; converted property
- (id)initWithTitle:(id)title prompt:(id)prompt label:(id)label notifying:(id)notifying;	// 0x34c074a9
- (id)accessibilityLabel;	// 0x34c07a05
- (void)dealloc;	// 0x34c0765d
// converted property getter: - (id)dottedQuad;	// 0x34c079a1
// converted property setter: - (void)setDottedQuad:(id)quad;	// 0x34c079b1
- (void)setFrame:(CGRect)frame;	// 0x34c076e9
- (void)setIcon:(id)icon horizontalOffset:(float)offset kerningFactor:(float)factor;	// 0x34c078bd
- (void)textDidChange:(id)text;	// 0x34c078f5
- (void)textDidEndEditing:(id)text;	// 0x34c078f9
@end

