/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRBackgroundTask.h"


__attribute__((visibility("hidden")))
@interface ATVDotMacMonitorBackgroundTask : BRBackgroundTask {
}
- (BOOL)perform:(id)perform;	// 0x34c02f79
@end

