/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library


__attribute__((visibility("hidden")))
@interface ATVEvaluation : NSObject {
}
+ (id)evaluationWithName:(id)name;	// 0x34c36a9d
+ (void)initialize;	// 0x34c36a45
+ (void)registerEvaluation:(id)evaluation withName:(id)name;	// 0x34c36abd
- (BOOL)evaluateValue:(id)value usingOperator:(id)anOperator withUserInfo:(id)userInfo;	// 0x34c36c09
- (SEL)selectorForOperator:(id)anOperator;	// 0x34c36add
@end

