/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRUserPasswordAccount.h"


@interface ATVFlickrManagedAccount : BRUserPasswordAccount {
}
- (void)authenticate;	// 0x34c11add
- (id)type;	// 0x34c11abd
@end

