/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRUserPasswordAuthenticator.h"
#import "NSXMLParserDelegate.h"

@class NSMutableString;

__attribute__((visibility("hidden")))
@interface ATVFlagstaffAuthenticator : BRUserPasswordAuthenticator <NSXMLParserDelegate> {
@private
	BOOL _requestSucceded;	// 5 = 0x5
	BOOL _inIdentificationSection;	// 6 = 0x6
	BOOL _inStatusSection;	// 7 = 0x7
	NSMutableString *_currentProperty;	// 8 = 0x8
}
- (id)_URLRequest;	// 0x34ca06a9
- (void)_failAuthenticationWithError:(id)error;	// 0x34ca0a8d
- (void)_handleAuthenticateResponse:(id)response;	// 0x34ca0929
- (void)_sendAuthenticationRequest;	// 0x34ca0881
- (void)dealloc;	// 0x34ca0655
- (void)parser:(id)parser didEndElement:(id)element namespaceURI:(id)uri qualifiedName:(id)name;	// 0x34ca0cd5
- (void)parser:(id)parser didStartElement:(id)element namespaceURI:(id)uri qualifiedName:(id)name attributes:(id)attributes;	// 0x34ca0add
- (void)parser:(id)parser foundCharacters:(id)characters;	// 0x34ca0ebd
@end

