/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRProvider.h"
#import <Foundation/Foundation.h> // Unknown library

@class NSMutableArray, NSString, NSDate;
@protocol BRControlFactory;

__attribute__((visibility("hidden")))
@interface ATVFlickrProvider : NSObject <BRProvider> {
@private
	NSMutableArray *_persistentAccounts;	// 4 = 0x4
	id<BRControlFactory> _controlFactory;	// 8 = 0x8
	NSDate *_lastUpdateDate;	// 12 = 0xc
	BOOL _updatePending;	// 16 = 0x10
	NSString *_uniqueID;	// 20 = 0x14
}
@property(readonly, retain) NSString *uniqueID;	// G=0x34c0f091; converted property
+ (id)providerOfPersistentAccounts;	// 0x34c0eb79
- (id)init;	// 0x34c0eba9
- (BOOL)_accountIconLoadedForAccount:(id)account updateData:(id)data;	// 0x34c1009d
- (void)_accountToRemove:(id)remove;	// 0x34c0f691
- (id)_accountWithName:(id)name;	// 0x34c10a01
- (id)_assetWithIdentifier:(id)identifier parentCollection:(id)collection;	// 0x34c10985
- (BOOL)_assetsLoadedForCollection:(id)collection updateData:(id)data;	// 0x34c10281
- (id)_cachedAccountIconForIconPath:(id)iconPath;	// 0x34c10891
- (id)_collectionWithIdentifier:(id)identifier withParentAccount:(id)parentAccount;	// 0x34c10909
- (BOOL)_contactsLoadedForAccount:(id)account updateData:(id)data;	// 0x34c1013d
- (id)_data;	// 0x34c108f9
- (BOOL)_handlesObject:(id)object;	// 0x34c0fb51
- (BOOL)_imageLoadedForAsset:(id)asset updateData:(id)data;	// 0x34c10751
- (id)_initForPersistentAccounts;	// 0x34c0f0a5
- (void)_listenerUpdate:(id)update;	// 0x34c0f7e9
- (id)_loadAccountsFromPersistentAccounts;	// 0x34c0f1e9
- (BOOL)_mediaLoadedForAccount:(id)account updateData:(id)data;	// 0x34c0fb55
- (void)_newAccountToAdd:(id)add;	// 0x34c0f3dd
- (id)_persistentAccounts;	// 0x34c0f19d
- (void)_postUpdateNotification:(id)notification;	// 0x34c0fb21
- (void)_processChangeToObject:(id)object;	// 0x34c0f82d
- (void)_sendUpdateNotification;	// 0x34c0f9d5
- (void)_sendUpdateNotificationAfterDelay;	// 0x34c0f9a5
- (id)accessibilityLabel;	// 0x34c0f0a1
- (BOOL)accountIsPersistent:(id)persistent;	// 0x34c0ee29
- (id)controlFactory;	// 0x34c0ed41
- (id)dataAtIndex:(long)index;	// 0x34c0ed75
- (long)dataCount;	// 0x34c0ed51
- (void)dealloc;	// 0x34c0ec75
- (void)handleDataUpdate:(id)update updateData:(id)data;	// 0x34c0eeb5
- (id)hashForDataAtIndex:(long)index;	// 0x34c0edd5
// converted property getter: - (id)uniqueID;	// 0x34c0f091
@end

