/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library

@class NSString, NSDate;

@interface ATVFavorite : NSObject {
@private
	NSDate *_dateAdded;	// 4 = 0x4
	NSString *_title;	// 8 = 0x8
	NSString *_itemID;	// 12 = 0xc
}
@property(copy) NSDate *dateAdded;	// G=0x34c53f91; S=0x34c53fa9; @synthesize=_dateAdded
@property(copy) NSString *itemID;	// G=0x34c54009; S=0x34c54021; @synthesize=_itemID
@property(copy) NSString *title;	// G=0x34c53fcd; S=0x34c53fe5; @synthesize=_title
+ (id)favoriteFromDictionary:(id)dictionary;	// 0x34c53cb1
- (id)initWithDictionary:(id)dictionary;	// 0x34c53d3d
- (id)_currentDsid;	// 0x34c54045
- (id)_currentStoreFront;	// 0x34c540c9
// declared property getter: - (id)dateAdded;	// 0x34c53f91
- (void)dealloc;	// 0x34c53df5
- (void)encodeWithDictionary:(id)dictionary;	// 0x34c53e5d
- (BOOL)isSaved;	// 0x34c53eed
// declared property getter: - (id)itemID;	// 0x34c54009
- (void)remove;	// 0x34c53f61
- (BOOL)removeUponAcquisition;	// 0x34c53ee9
- (void)save;	// 0x34c53f31
// declared property setter: - (void)setDateAdded:(id)added;	// 0x34c53fa9
// declared property setter: - (void)setItemID:(id)anId;	// 0x34c54021
// declared property setter: - (void)setTitle:(id)title;	// 0x34c53fe5
// declared property getter: - (id)title;	// 0x34c53fcd
@end

