/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVFeedCyclerController.h"


__attribute__((visibility("hidden")))
@interface ATVFlagstaffLineScoreCyclerController : ATVFeedCyclerController {
}
- (id)cycler:(id)cycler itemAtIndex:(int)index;	// 0x34ca94dd
@end

