/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRProvider.h"
#import <Foundation/Foundation.h> // Unknown library

@class ATVFavoritesControlFactory, NSArray;

__attribute__((visibility("hidden")))
@interface ATVFavoritesProvider : NSObject <BRProvider> {
@private
	NSArray *_favorites;	// 4 = 0x4
	ATVFavoritesControlFactory *_factory;	// 8 = 0x8
}
+ (id)provider;	// 0x34bf728d
+ (id)providerWithFavorites:(id)favorites;	// 0x34bf7351
+ (id)providerWithItemType:(int)itemType;	// 0x34bf72ed
- (id)initWithFavorites:(id)favorites;	// 0x34bf7385
- (void)_favoritesChanged:(id)changed;	// 0x34bf751d
- (id)controlFactory;	// 0x34bf7509
- (id)dataAtIndex:(long)index;	// 0x34bf74c9
- (long)dataCount;	// 0x34bf74e9
- (void)dealloc;	// 0x34bf7449
- (id)hashForDataAtIndex:(long)index;	// 0x34bf7519
@end

