/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRMediaMenuController.h"

@class ATVInternetPhotosAccount;

__attribute__((visibility("hidden")))
@interface ATVFlickrCollectionController : BRMediaMenuController {
@private
	ATVInternetPhotosAccount *_account;	// 136 = 0x88
	BOOL _isScreenSaverMenu;	// 140 = 0x8c
}
+ (id)menuControllerForAccount:(id)account;	// 0x34c08165
+ (id)screenSaverMenuControllerForAccount:(id)account;	// 0x34c081a5
- (id)initWithAccount:(id)account;	// 0x34c081e5
- (id)initWithAccount:(id)account forScreenSaver:(BOOL)screenSaver;	// 0x34c081fd
- (void)_handleAddSelection:(id)selection;	// 0x34c08a9d
- (void)_handleCollectionSelection:(id)selection;	// 0x34c087f9
- (void)_handleContactsSelection:(id)selection;	// 0x34c08c1d
- (void)_handleRemoveSelection:(id)selection;	// 0x34c08961
- (void)_providerUpdated:(id)updated;	// 0x34c08cd9
- (void)dealloc;	// 0x34c08755
- (long)defaultIndex;	// 0x34c087c1
- (BOOL)isNetworkDependent;	// 0x34c087f5
@end

