/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRMediaShelfViewCell.h"
#import "BRControl.h"

@class BRAsyncImageControl, BRReflectionControl, ATVFlagstaffPosterHeader, ATVFlagstaffPosterBottomOverlay, BRImageControl;

__attribute__((visibility("hidden")))
@interface ATVFlagstaffPoster : BRControl <BRMediaShelfViewCell> {
@private
	BRReflectionControl *_reflectionControl;	// 44 = 0x2c
	BOOL _imageEdgeAntialiasingEnabled;	// 48 = 0x30
	int _style;	// 52 = 0x34
	ATVFlagstaffPosterHeader *_header;	// 56 = 0x38
	BRImageControl *_backgroundImageControl;	// 60 = 0x3c
	BRAsyncImageControl *_imageControl;	// 64 = 0x40
	ATVFlagstaffPosterBottomOverlay *_bottomOverlay;	// 68 = 0x44
}
@property(readonly, assign, nonatomic) BRImageControl *backgroundImageControl;	// G=0x34ca7ba9; @synthesize=_backgroundImageControl
@property(readonly, assign, nonatomic) ATVFlagstaffPosterBottomOverlay *bottomOverlay;	// G=0x34ca7bc9; @synthesize=_bottomOverlay
@property(readonly, assign, nonatomic) ATVFlagstaffPosterHeader *header;	// G=0x34ca7b99; @synthesize=_header
@property(readonly, assign, nonatomic) BRAsyncImageControl *imageControl;	// G=0x34ca7bb9; @synthesize=_imageControl
@property(assign, nonatomic) int style;	// G=0x34ca7b89; S=0x34ca77f5; @synthesize=_style
+ (id)flagstaffPosterWithStyle:(int)style;	// 0x34ca769d
- (id)init;	// 0x34ca76d1
- (id)initWithStyle:(int)style;	// 0x34ca76e9
- (CGRect)_contentFrame;	// 0x34ca7bd9
- (void)_imageControlImageReady:(id)ready;	// 0x34ca7f85
- (void)_setStyle:(int)style;	// 0x34ca7c65
// declared property getter: - (id)backgroundImageControl;	// 0x34ca7ba9
// declared property getter: - (id)bottomOverlay;	// 0x34ca7bc9
- (void)dealloc;	// 0x34ca7741
- (CGRect)focusCursorFrame;	// 0x34ca781d
// declared property getter: - (id)header;	// 0x34ca7b99
- (void)hideTextLayers;	// 0x34ca78a9
// declared property getter: - (id)imageControl;	// 0x34ca7bb9
- (BOOL)isAccessibilityElement;	// 0x34ca7b85
- (void)layoutSubcontrols;	// 0x34ca78e9
- (void)setImageEdgeAntialiasingEnabled:(BOOL)enabled;	// 0x34ca78ad
// declared property setter: - (void)setStyle:(int)style;	// 0x34ca77f5
// declared property getter: - (int)style;	// 0x34ca7b89
@end

