/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRControl.h"
#import "BRReady.h"

@class BRTextControl, BRAsyncImageControl, NSString;

__attribute__((visibility("hidden")))
@interface ATVGameVersusPreview : BRControl <BRReady> {
@private
	BRTextControl *_centerTextControl;	// 44 = 0x2c
	BRAsyncImageControl *_backgroundImageControl;	// 48 = 0x30
	BRAsyncImageControl *_leftImageControl;	// 52 = 0x34
	BRAsyncImageControl *_rightImageControl;	// 56 = 0x38
}
@property(readonly, assign, nonatomic) BRAsyncImageControl *backgroundImageControl;	// G=0x34c804fd; @synthesize=_backgroundImageControl
@property(copy, nonatomic) NSString *centerText;	// G=0x34c80301; S=0x34c80331; 
@property(readonly, assign, nonatomic) BRAsyncImageControl *leftImageControl;	// G=0x34c8050d; @synthesize=_leftImageControl
@property(readonly, assign, nonatomic) BRAsyncImageControl *rightImageControl;	// G=0x34c8051d; @synthesize=_rightImageControl
- (id)init;	// 0x34c7ff91
- (id)_centerTextAttributes;	// 0x34c8052d
- (void)_imageLoadedNotification:(id)notification;	// 0x34c80551
- (void)_setHiddenOnSubcontrols:(BOOL)subcontrols;	// 0x34c805f1
// declared property getter: - (id)backgroundImageControl;	// 0x34c804fd
// declared property getter: - (id)centerText;	// 0x34c80301
- (void)dealloc;	// 0x34c8019d
- (void)getReady;	// 0x34c80241
- (BOOL)isReady;	// 0x34c80299
- (void)layoutSubcontrols;	// 0x34c8037d
// declared property getter: - (id)leftImageControl;	// 0x34c8050d
// declared property getter: - (id)rightImageControl;	// 0x34c8051d
// declared property setter: - (void)setCenterText:(id)text;	// 0x34c80331
@end

