/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRSingleton.h"
#import "AppleTV-Structs.h"

@class NSInvocation, NSThread, NSConditionLock;

@interface ATVHIDThread : BRSingleton {
@private
	NSThread *_hidThread;	// 4 = 0x4
	CFRunLoopRef _runLoop;	// 8 = 0x8
	NSConditionLock *_startLock;	// 12 = 0xc
	CFRunLoopSourceRef _invocationRunLoopSource;	// 16 = 0x10
	NSInvocation *_pendingInvocation;	// 20 = 0x14
	NSConditionLock *_invocationLock;	// 24 = 0x18
}
+ (void)setSingleton:(id)singleton;	// 0x34c3c285
+ (id)singleton;	// 0x34c3c279
- (id)init;	// 0x34c3c291
- (void)_hidThreadLoop;	// 0x34c3c5c5
- (void)_invocationHandler;	// 0x34c3c785
- (void)dealloc;	// 0x34c3c381
- (BOOL)invokeOnHIDThread:(id)thread;	// 0x34c3c3d9
@end

