/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVMusicStoreAuthenticationResources.h"


@interface ATVHomeShareAuthenticationResources : ATVMusicStoreAuthenticationResources {
}
+ (void)initialize;	// 0x34c6e5d1
- (id)accountNameFootnote;	// 0x34c6e6a5
- (id)accountNameInstructions;	// 0x34c6e67d
- (id)accountNameTitle;	// 0x34c6e655
- (id)accountPasswordTitle;	// 0x34c6e6a9
- (id)behaviorIdentifierForTextHistoryStorage;	// 0x34c6e7b1
- (id)behaviorsForTextHistoryDisplay;	// 0x34c6e7ed
- (id)clientIdentifierForTextHistoryStorage;	// 0x34c6e7a5
- (id)clientsForTextHistoryDisplay;	// 0x34c6e7c1
- (id)defaultPasswordKey;	// 0x34c6e6d1
- (id)defaultUserName;	// 0x34c6e705
- (id)defaultUserNameKey;	// 0x34c6e6dd
- (id)titleImage;	// 0x34c6e6e9
@end

