/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVFavorite.h"
#import "AppleTV-Structs.h"

@class NSString;

@interface ATVInternetRadioFavorite : ATVFavorite {
@private
	NSString *_stationID;	// 16 = 0x10
	NSString *_collectionTitle;	// 20 = 0x14
}
@property(retain) id category;	// G=0x34c571d9; S=0x34c571e9; converted property
@property(retain) NSString *stationID;	// G=0x34c57341; S=0x34c57309; converted property
+ (void)_stationFoundInCategory:(id)category;	// 0x34c56d8d
+ (id)favoriteFromAsset:(id)asset;	// 0x34c56f51
+ (id)favoriteFromMediaItem:(ATVMediaItemRef)mediaItem;	// 0x34c56fd1
+ (void)initialize;	// 0x34c56d21
- (id)initWithDictionary:(id)dictionary;	// 0x34c57015
- (id)_initWithMediaItem:(ATVMediaItemRef)mediaItem;	// 0x34c574a1
- (void)_setItemIdForTitle:(id)title genre:(id)genre;	// 0x34c57585
// converted property getter: - (id)category;	// 0x34c571d9
- (void)dealloc;	// 0x34c570ad
- (id)description;	// 0x34c57175
- (void)encodeWithDictionary:(id)dictionary;	// 0x34c57105
- (BOOL)isPlayingOrPaused;	// 0x34c57351
- (id)mediaAsset;	// 0x34c57221
- (ATVMediaItemRef)mediaItemRef;	// 0x34c57305
// converted property setter: - (void)setCategory:(id)category;	// 0x34c571e9
// converted property setter: - (void)setStationID:(id)anId;	// 0x34c57309
// converted property getter: - (id)stationID;	// 0x34c57341
@end

