/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRControl.h"
#import "AppleTV-Structs.h"

@class BRImageControl, BRTextControl, ATVIPv4AddressSelectionWidget, NSArray;

__attribute__((visibility("hidden")))
@interface ATVIPv4AddressSelectionControl : BRControl {
@private
	NSArray *_octetBackgroundLayers;	// 44 = 0x2c
	NSArray *_digitLayers;	// 48 = 0x30
	NSArray *_dotLayers;	// 52 = 0x34
	BRImageControl *_arrowsLayer;	// 56 = 0x38
	ATVIPv4AddressSelectionWidget *_selectionWidget;	// 60 = 0x3c
	BRTextControl *_doneLayer;	// 64 = 0x40
	int _selection;	// 68 = 0x44
}
- (id)init;	// 0x34c5ac85
- (CGRect)_arrowsFrameForSelection:(int)selection;	// 0x34c5c619
- (id)_buildArrowsLayer;	// 0x34c5c039
- (id)_buildDigitLayers;	// 0x34c5be71
- (id)_buildDoneLayer;	// 0x34c5c0e5
- (id)_buildDotLayers;	// 0x34c5bf55
- (id)_buildOctetBackgroundLayers;	// 0x34c5bd51
- (CGRect)_cellFrameForSelection:(int)selection;	// 0x34c5c7ed
- (CGRect)_digitFrameForSelection:(int)selection;	// 0x34c5c6fd
- (float)_layoutUIWithHeight:(float)height;	// 0x34c5c1b9
- (CGRect)_selectionWidgetFrameForSelection:(int)selection;	// 0x34c5c579
- (void)_setDigitHighlighted:(BOOL)highlighted atIndex:(int)index;	// 0x34c5cad1
- (void)_setDigitValue:(int)value atIndex:(int)index;	// 0x34c5cb95
- (void)_setSelection:(int)selection;	// 0x34c5c971
- (float)_singleCellWidth;	// 0x34c5c91d
- (id)_textEntryGlyphAttributes;	// 0x34c5cc9d
- (id)_textEntryGlyphGrayAttributes;	// 0x34c5ccbd
- (id)accessibilityLabel;	// 0x34c5cce1
- (id)accessibilityTraits;	// 0x34c5cd65
- (void)controlWasActivated;	// 0x34c5af19
- (void)dealloc;	// 0x34c5ae79
- (BOOL)decrementSelection;	// 0x34c5b53d
- (BOOL)doneButtonSelected;	// 0x34c5ba51
- (BOOL)incrementSelection;	// 0x34c5b225
- (id)ipAddress;	// 0x34c5b88d
- (BOOL)moveSelectionLeft;	// 0x34c5b159
- (BOOL)moveSelectionRight;	// 0x34c5b089
- (CGRect)preferredFrameForScreenSize:(CGSize)screenSize;	// 0x34c5af6d
- (void)reset;	// 0x34c5ba79
- (void)setFrame:(CGRect)frame;	// 0x34c5bc6d
- (void)setIPAddress:(id)address;	// 0x34c5ba95
@end

