/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class BRImageControl;

__attribute__((visibility("hidden")))
@interface ATVImageListHeaderControl : BRControl {
@private
	BRImageControl *_image;	// 44 = 0x2c
}
@property(readonly, assign) BRImageControl *image;	// G=0x34ca8e0d; @synthesize=_image
- (id)init;	// 0x34ca8c65
- (id)accessibilityLabel;	// 0x34ca8ded
- (void)dealloc;	// 0x34ca8ccd
// declared property getter: - (id)image;	// 0x34ca8e0d
- (void)layoutSubcontrols;	// 0x34ca8d71
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x34ca8d11
@end

