/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVJSObject.h"
#import "AppleTV-Structs.h"
#import <Foundation/Foundation.h> // Unknown library


__attribute__((visibility("hidden")))
@interface ATVJSAuthContext : NSObject <ATVJSObject> {
@private
	OpaqueJSContext *_context;	// 4 = 0x4
	OpaqueJSValue *_jsObjectRef;	// 8 = 0x8
	id _notificationObject;	// 12 = 0xc
}
@property(assign, nonatomic) OpaqueJSValue *jsObjectRef;	// G=0x34cb6115; S=0x34cb6125; @synthesize=_jsObjectRef
@property(retain, nonatomic) id notificationObject;	// G=0x34cb6135; S=0x34cb6145; @synthesize=_notificationObject
- (id)initWithContext:(OpaqueJSContext *)context object:(id)object;	// 0x34cb5d71
- (void)dealloc;	// 0x34cb60d1
// declared property getter: - (OpaqueJSValue *)jsObjectRef;	// 0x34cb6115
// declared property getter: - (id)notificationObject;	// 0x34cb6135
// declared property setter: - (void)setJsObjectRef:(OpaqueJSValue *)ref;	// 0x34cb6125
// declared property setter: - (void)setNotificationObject:(id)object;	// 0x34cb6145
@end

