/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRBackgroundTask.h"

@class ATVKeyValueStore;

__attribute__((visibility("hidden")))
@interface ATVKeyValueStoreCleanupTask : BRBackgroundTask {
@private
	double _lastModifiedThreshold;	// 44 = 0x2c
	ATVKeyValueStore *_keyValueStore;	// 52 = 0x34
}
- (void)dealloc;	// 0x34c79255
- (BOOL)perform:(id)perform;	// 0x34c792e5
- (void)setKeyValueStore:(id)store;	// 0x34c79299
- (void)setLastModifiedThreshold:(double)threshold;	// 0x34c792d1
@end

