/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVMusicStoreControlPopulator.h"


__attribute__((visibility("hidden")))
@interface ATVMusicStoreSingleItemPopulator : ATVMusicStoreControlPopulator {
}
+ (BOOL)canHandleData:(id)data;	// 0x34c334d5
- (int)_trackCountForItem:(id)item;	// 0x34c33e0d
- (id)listRowForData:(id)data;	// 0x34c33541
@end

