/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRBaseMediaAsset.h"

@protocol BRMediaAsset;

__attribute__((visibility("hidden")))
@interface ATVMusicCoversMediaAsset : BRBaseMediaAsset {
@private
	id<BRMediaAsset> _asset;	// 8 = 0x8
}
+ (id)assetWrapperWithAsset:(id)asset;	// 0x34c5a329
- (id)initWithAsset:(id)asset;	// 0x34c5a36d
- (id)assetID;	// 0x34c5a401
- (void)dealloc;	// 0x34c5a3bd
- (id)imageProxy;	// 0x34c5a421
- (id)mediaType;	// 0x34c5a441
@end

