/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVCatalogAgent.h"
#import "AppleTV-Structs.h"
#import <Foundation/Foundation.h> // Unknown library


@interface ATVMusicStoreCatalogAgent : NSObject <ATVCatalogAgent> {
}
+ (void)_acquisitionFailed:(id)failed;	// 0x34c19f41
+ (void)_acquisitionSucceeded:(id)succeeded;	// 0x34c19e59
+ (id)_backgroundGradientImageForItem:(id)item;	// 0x34c1d3a1
+ (id)_backgroundImageForItem:(id)item;	// 0x34c1d381
+ (id)_backgroundImageForItem:(id)item imageName:(id)name;	// 0x34c1d3c1
+ (CGSize)_backgroundImageSizeForItem:(id)item inset:(float *)inset;	// 0x34c1d241
+ (void)_catalogControlRequestProcessed:(id)processed;	// 0x34c19a15
+ (id)_catalogPageControlForItem:(id)item;	// 0x34c1ae91
+ (id)_collectionControlsForPageItem:(id)pageItem requestedBy:(id)by dividerSeparated:(BOOL)separated;	// 0x34c1bded
+ (id)_controlForItem:(id)item;	// 0x34c1aa01
+ (void)_controlForMediaItem:(ATVMediaItemRef)mediaItem;	// 0x34c1adb5
+ (void)_controlForURL:(id)url identifier:(id)identifier merchant:(id)merchant;	// 0x34c1a8f9
+ (id)_createItemTypeMap;	// 0x34c18505
+ (id)_firstControlOfType:(Class)type inArray:(id)array;	// 0x34c1cd79
+ (id)_formattedPageContentCountString:(id)string;	// 0x34c1c731
+ (id)_headerControlsForPageItem:(id)pageItem;	// 0x34c1c289
+ (id)_listPageForItem:(id)item;	// 0x34c1b315
+ (id)_mediaTypeForStoreLink:(id)storeLink;	// 0x34c1a451
+ (id)_mediaTypeForStoreMediaCollectionType:(id)storeMediaCollectionType;	// 0x34c1a2d5
+ (id)_mediaTypeForStoreMediaType:(id)storeMediaType;	// 0x34c1a129
+ (id)_moreInfoHeaderControlsForPageItem:(id)pageItem;	// 0x34c1c479
+ (void)_playEventMediaAsset:(id)asset;	// 0x34c1a711
+ (void)_playVideoClip:(id)clip;	// 0x34c1a4ad
+ (void)_popToItemController:(id)itemController;	// 0x34c1a0e1
+ (id)_roomDescriptionControlsForPageItem:(id)pageItem;	// 0x34c1ce19
+ (id)_roomPageContainerForItem:(id)item withScroller:(id)scroller;	// 0x34c1b569
+ (id)_roomPageForItem:(id)item;	// 0x34c1b405
+ (id)_scrollerControlsFromHeaderControls:(id)headerControls collectionControls:(id)controls;	// 0x34c1c6ad
+ (id)_setupScroller;	// 0x34c1b105
+ (id)_supplementPageForItem:(id)item;	// 0x34c1b27d
+ (id)_tabbedPageForItem:(id)item;	// 0x34c1b959
+ (void)acquireItem:(id)item;	// 0x34c17b79
+ (id)allLeafItemsForItem:(id)item;	// 0x34c19469
+ (id)catalogHandler;	// 0x34c17a21
+ (void)checkForPurchases;	// 0x34c17b11
+ (id)configureRelatedControlsFromControl:(id)control style:(int)style;	// 0x34c197e5
+ (id)controlForItem:(id)item;	// 0x34c184f1
+ (void)controlForObject:(id)object;	// 0x34c181d1
+ (void)controlForObject:(id)object merchant:(id)merchant;	// 0x34c18209
+ (id)coverArtForItem:(id)item;	// 0x34c18fed
+ (id)coverArtURLForItem:(id)item featured:(BOOL)featured thumbnail:(BOOL)thumbnail;	// 0x34c191e5
+ (long)downloadItem:(id)item;	// 0x34c17d3d
+ (id)episodeArtURLForItem:(id)item;	// 0x34c192b9
+ (void)initialize;	// 0x34c17755
+ (BOOL)isItemFeatured:(id)featured;	// 0x34c19361
+ (BOOL)isItemOrdered:(id)ordered;	// 0x34c19389
+ (BOOL)isTemplateParameterSet:(id)set forItem:(id)item;	// 0x34c193b1
+ (long)itemIDForItem:(id)item;	// 0x34c18ebd
+ (int)itemType:(id)type;	// 0x34c18755
+ (id)mediaAssetForStoreOffer:(id)storeOffer;	// 0x34c1893d
+ (id)mediaTypeForItem:(id)item;	// 0x34c1889d
+ (void)playStoreItem:(id)item;	// 0x34c19605
+ (id)plistFromURLDocument:(id)urldocument;	// 0x34c1974d
+ (void)registerClass:(Class)aClass withTemplateName:(id)templateName;	// 0x34c17e45
+ (void)sendPingForItem:(id)item;	// 0x34c17f99
+ (void)setDownloadFunction:(/*function-pointer*/ void *)function;	// 0x34c17b6d
+ (void)setPurchaseFunction:(/*function-pointer*/ void *)function;	// 0x34c17b49
+ (void)setRentalFunction:(/*function-pointer*/ void *)function;	// 0x34c17b55
+ (void)setSubscribeFunction:(/*function-pointer*/ void *)function;	// 0x34c17b61
+ (BOOL)showAllTitles:(id)titles;	// 0x34c19311
+ (BOOL)showTitleAndSubtitle:(id)subtitle;	// 0x34c19339
+ (BOOL)storeVersionIsCompatibileForPageDictionary:(id)pageDictionary redirectURL:(id *)url;	// 0x34c180cd
+ (void)subscribeToItem:(id)item;	// 0x34c17d21
@end

