/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVMusicStoreBaseMetadataProvider.h"


__attribute__((visibility("hidden")))
@interface ATVMusicStoreMusicVideoMetadataProvider : ATVMusicStoreBaseMetadataProvider {
}
+ (void)_initializeAbbreviatedTransformers;	// 0x34c2e9f5
+ (void)_initializeDetailedTransformers;	// 0x34c2e8e9
+ (void)_initializeMappings:(id)mappings;	// 0x34c2e74d
+ (void)initialize;	// 0x34c2e4c9
- (void)_populateAbbreviatedMetadata:(id)metadata;	// 0x34c2eac1
- (void)_populateDetailedMetadata:(id)metadata;	// 0x34c2eda1
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x34c2e58d
- (void)populateMetadataForControl:(id)control;	// 0x34c2e675
@end

