/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVCatalogApplianceController.h"
#import "AppleTV-Structs.h"

@class BRControl, BRMediaShelfView, BRListControl, NSDictionary;

__attribute__((visibility("hidden")))
@interface ATVMusicStoreMoreInfoController : ATVCatalogApplianceController {
@private
	NSDictionary *_catalogItem;	// 96 = 0x60
	BRListControl *_list;	// 100 = 0x64
	BRControl *_previousPosterControl;	// 104 = 0x68
	BOOL _localListContentSelected;	// 108 = 0x6c
	BRMediaShelfView *_actionShelfControl;	// 112 = 0x70
	long _lastSelectedIndex;	// 116 = 0x74
}
- (id)initWithCatalogItem:(id)catalogItem;	// 0x34c299d5
- (id)_coverArtControl;	// 0x34c2ace9
- (void)_focusedActionChanged:(id)changed;	// 0x34c2a65d
- (id)_grid;	// 0x34c2aeb1
- (void)_listSelectionChanged:(id)changed;	// 0x34c2a3c9
- (void)_loadList;	// 0x34c29ff1
- (void)_loadMoreInfoItemContentFromURL:(id)url;	// 0x34c2aff9
- (void)_loadMoreInfoItemContentFromURLString:(id)urlstring;	// 0x34c2afc1
- (void)_moreInfoItemContentFeedReceived:(id)received;	// 0x34c2b119
- (BOOL)_selectionIsTopmostSelectable;	// 0x34c2a2bd
- (id)_summaryControl;	// 0x34c2a735
- (id)_summaryControlForItem:(id)item;	// 0x34c2a74d
- (id)accessibilityScreenContent;	// 0x34c29fc9
- (void)addControls;	// 0x34c2b411
- (BOOL)brEventAction:(id)action;	// 0x34c29bfd
- (void)controlWasActivated;	// 0x34c29ac5
- (void)controlWasDeactivated;	// 0x34c29b71
- (void)dealloc;	// 0x34c29a35
- (id)focusedControlForEvent:(id)event focusPoint:(CGPoint *)point;	// 0x34c29ced
- (void)layoutSubcontrols;	// 0x34c29ee9
- (void)refreshDirtyPage;	// 0x34c2b4ed
- (BOOL)shouldAllowControllerContent;	// 0x34c2b405
- (id)transitionType;	// 0x34c29ed9
- (void)updateContent:(id)content;	// 0x34c2b4b1
- (void)willEnterCompleteState;	// 0x34c2b3e1
@end

