/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVMusicStorePagedViewController.h"


__attribute__((visibility("hidden")))
@interface ATVMusicStoreSingleRowPagedViewController : ATVMusicStorePagedViewController {
}
- (long)_itemsPerPage;	// 0x34c6138d
- (long)grid:(id)grid indexForItemID:(id)itemID;	// 0x34c61385
- (id)grid:(id)grid itemIDAtIndex:(long)index;	// 0x34c6134d
- (long)numberOfColumnsInGrid:(id)grid;	// 0x34c61349
- (id)view;	// 0x34c61191
@end

