/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVCatalogApplianceController.h"
#import "BRTabControlDelegate.h"

@class BRControl, NSTimer, BRTabControl;

__attribute__((visibility("hidden")))
@interface ATVMusicStoreTabbedPageController : ATVCatalogApplianceController <BRTabControlDelegate> {
@private
	BRControl *_contentControl;	// 96 = 0x60
	BRTabControl *_tabControl;	// 100 = 0x64
	NSTimer *_activeTabSelectionChangedTimer;	// 104 = 0x68
	BOOL _showingWaitContent;	// 108 = 0x6c
	BOOL _initialTabContentLoaded;	// 109 = 0x6d
	BOOL _transitionInhibited;	// 110 = 0x6e
}
- (id)initWithContentControl:(id)contentControl tabControl:(id)control;	// 0x34c33ef9
- (void)_delayedTabSelectionTimerFired:(id)fired;	// 0x34c34165
- (id)_preferredTabSegmentInTab;	// 0x34c344c5
- (id)_scrollPlane;	// 0x34c3440d
- (id)_tabDictionary;	// 0x34c3443d
- (id)_tabName;	// 0x34c34495
- (void)dealloc;	// 0x34c3410d
- (id)errorContent;	// 0x34c343bd
- (BOOL)shouldAllowTransitionOnSwap;	// 0x34c343f5
- (BOOL)shouldShowWaitContent;	// 0x34c343a5
- (void)tabControl:(id)control didSelectTabItem:(id)item;	// 0x34c342bd
- (void)tabControl:(id)control willSelectTabItem:(id)item;	// 0x34c3435d
- (void)tabControlDidChangeNumberOfTabItems:(id)tabControl;	// 0x34c34361
- (id)waitContent;	// 0x34c34365
- (float)waitContentDelay;	// 0x34c343a1
- (void)willEnterCompleteState;	// 0x34c343e5
@end

