/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRController.h"

@class BRWaitPromptControl, NSTimer, ATVURLDocument, NSDictionary;

@interface ATVMusicStoreMoviePreviewController : BRController {
@private
	BRWaitPromptControl *_waitPrompt;	// 60 = 0x3c
	NSTimer *_timer;	// 64 = 0x40
	NSDictionary *_dictionary;	// 68 = 0x44
	ATVURLDocument *_document;	// 72 = 0x48
}
+ (id)previewControllerWithDictionary:(id)dictionary;	// 0x34c5ceb1
- (id)init;	// 0x34c5cef5
- (id)initWithStoreDictionary:(id)storeDictionary;	// 0x34c5cef9
- (void)_movieDataFetchRequestProcessed:(id)processed;	// 0x34c5d42d
- (void)_showPromptTimer:(id)timer;	// 0x34c5d75d
- (BOOL)brEventAction:(id)action;	// 0x34c5d791
- (void)controlWasActivated;	// 0x34c5d22d
- (void)controlWasDeactivated;	// 0x34c5d6f5
- (void)dealloc;	// 0x34c5d19d
@end

