/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRController.h"

@class BRMediaShelfView, BRBoxControl, BRMovieTrailerCollection, BRMovieTrailersProvider, BRDetailedMediaControl;

__attribute__((visibility("hidden")))
@interface ATVMovieTrailersDetailController : BRController {
@private
	BRMovieTrailersProvider *_provider;	// 60 = 0x3c
	BRMovieTrailerCollection *_trailer;	// 64 = 0x40
	BRDetailedMediaControl *_detailedControl;	// 68 = 0x44
	BRBoxControl *_relatedBox;	// 72 = 0x48
	BRMediaShelfView *_relatedShelf;	// 76 = 0x4c
}
@property(readonly, retain) BRMovieTrailerCollection *trailer;	// G=0x34ca669d; converted property
- (id)initWithProvider:(id)provider trailer:(id)trailer;	// 0x34ca64dd
- (void)_setActionControl;	// 0x34ca6a01
- (void)_setCopyrightText;	// 0x34ca6e09
- (void)_setImageProxy;	// 0x34ca6985
- (void)_setMetadataControl;	// 0x34ca6d4d
- (void)_setRelatedContent;	// 0x34ca6e85
- (void)_setupDetailControls;	// 0x34ca692d
- (id)accessibilityScreenContent;	// 0x34ca767d
- (BOOL)brEventAction:(id)action;	// 0x34ca67b5
- (void)dealloc;	// 0x34ca6611
- (BOOL)handleSelectionForActionShelf:(id)actionShelf;	// 0x34ca7525
- (BOOL)handleSelectionForRelatedShelf:(id)relatedShelf;	// 0x34ca7425
- (void)layoutSubcontrols;	// 0x34ca66ad
// converted property getter: - (id)trailer;	// 0x34ca669d
@end

