/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRProvider.h"
#import <Foundation/Foundation.h> // Unknown library

@class NSMutableArray, NSDictionary;

__attribute__((visibility("hidden")))
@interface ATVMusicStoreMoreInfoProvider : NSObject <BRProvider> {
@private
	NSDictionary *_catalogItem;	// 4 = 0x4
	NSMutableArray *_items;	// 8 = 0x8
}
+ (id)providerWithCatalogItem:(id)catalogItem;	// 0x34c2b745
- (id)initWithCatalogItem:(id)catalogItem;	// 0x34c2b779
- (id)_flattenMoreInfoSection:(id)section;	// 0x34c2ba05
- (void)_loadMoreInfoData;	// 0x34c2b93d
- (void)_loadMoreInfoFromURL:(id)url;	// 0x34c2baf9
- (void)_supplementalResponseReceived:(id)received;	// 0x34c2bc25
- (id)controlFactory;	// 0x34c2b8d9
- (id)dataAtIndex:(long)index;	// 0x34c2b919
- (long)dataCount;	// 0x34c2b8f9
- (void)dealloc;	// 0x34c2b859
- (id)hashForDataAtIndex:(long)index;	// 0x34c2b939
@end

