/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVMerchant.h"
#import "ATVMerchantRepresentativeFeed.h"
#import "AppleTV-Structs.h"


__attribute__((visibility("hidden")))
@interface ATVMerchant_Sedona : ATVMerchant <ATVMerchantRepresentativeFeed> {
}
+ (void)_initializeLibrary;	// 0x33911e39
+ (int)_libraryInitializationCondtionsYetToBeMet;	// 0x339112c9
+ (id)allocWithZone:(NSZone *)zone;	// 0x33911e5d
+ (void)initialize;	// 0x33911841
- (id)init;	// 0x33911b11
- (void)_authenticationSucceeded:(id)succeeded;	// 0x339113ed
- (void)_preferredAccountEstablished:(id)established;	// 0x33911431
- (void)_preferredAccountRemoved:(id)removed;	// 0x339114c1
- (id)brandImageForControl:(id)control fromDictionary:(id)dictionary;	// 0x33911f7d
- (BOOL)brandsControls;	// 0x339112c5
- (void)dealloc;	// 0x33911ae5
- (id)description;	// 0x339112b9
- (id)generateRequestForURL:(id)url headers:(id)headers method:(id)method;	// 0x339117f9
- (id)loadRepresentativeFeed;	// 0x33912039
- (id)localizedStringForKey:(id)key;	// 0x339121ed
- (id)merchantErrorForError:(id)error;	// 0x339115dd
@end

