/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library


__attribute__((visibility("hidden")))
@interface ATVMusicStoreControlPopulator : NSObject {
@private
	unsigned _matchOrder;	// 4 = 0x4
}
@property(readonly, assign) unsigned matchOrder;	// G=0x34c26079; @synthesize=_matchOrder
+ (BOOL)canHandleData:(id)data;	// 0x34c23ad1
- (id)init;	// 0x34c23b11
- (float)_shelfBoxTitleHeightForCollectionType:(id)collectionType featured:(BOOL)featured related:(BOOL)related;	// 0x34c26561
- (float)_shelfTitleWidthScaleForCollectionType:(id)collectionType featured:(BOOL)featured moreInfoContent:(BOOL)content showTitleAndSubtitle:(BOOL)subtitle showAllTitles:(BOOL)titles related:(BOOL)related;	// 0x34c266a1
- (float)_shelfWidthForData:(id)data;	// 0x34c265c5
- (id)buttonForData:(id)data;	// 0x34c23bbd
- (float)buttonHeightForData:(id)data;	// 0x34c25d1d
- (id)coverArtURLForData:(id)data thumbnail:(BOOL)thumbnail;	// 0x34c26089
- (id)gridForData:(id)data;	// 0x34c24f65
- (float)gridHeightForData:(id)data;	// 0x34c25f21
- (id)listForData:(id)data;	// 0x34c252d1
- (float)listHeightForData:(id)data;	// 0x34c25f25
- (id)listRowForData:(id)data;	// 0x34c25549
- (float)listRowHeightForData:(id)data;	// 0x34c25f29
- (id)mainMenuButtonForData:(id)data;	// 0x34c2463d
// declared property getter: - (unsigned)matchOrder;	// 0x34c26079
- (id)mediaPreviewControlForData:(id)data;	// 0x34c25a51
- (float)mediaPreviewHeightForData:(id)data;	// 0x34c26061
- (id)pagedViewForData:(id)data;	// 0x34c25cf1
- (float)pagedViewHeightForData:(id)data;	// 0x34c26065
- (id)placeholderImageForData:(id)data;	// 0x34c26179
- (id)placeholderImageForMenuItemData:(id)menuItemData;	// 0x34c264f1
- (id)placeholderImageForShelfData:(id)shelfData;	// 0x34c26389
- (id)playButtonEnabledMenuItem;	// 0x34c268ad
- (id)shelfForData:(id)data;	// 0x34c247ad
- (float)shelfHeightForData:(id)data;	// 0x34c25e11
@end

