/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRControl.h"
#import "AppleTV-Structs.h"

@class BRImageControl, BRTextControl, ATVMusicStoreOffer;

__attribute__((visibility("hidden")))
@interface ATVMusicStoreOfferControl : BRControl {
@private
	ATVMusicStoreOffer *_storeOffer;	// 44 = 0x2c
	BRTextControl *_topLineTextControl;	// 48 = 0x30
	BRTextControl *_bottomLineTextControl;	// 52 = 0x34
	BRImageControl *_hdImageControl;	// 56 = 0x38
	BRImageControl *_ddImageControl;	// 60 = 0x3c
	BRImageControl *_ccImageControl;	// 64 = 0x40
	BRImageControl *_digitalExtrasControl;	// 68 = 0x44
}
- (id)init;	// 0x34c2fe85
- (id)accessibilityLabel;	// 0x34c30bc1
- (void)dealloc;	// 0x34c2fec9
- (void)layoutSubcontrols;	// 0x34c30621
- (void)setClosedCaption:(BOOL)caption;	// 0x34c30401
- (void)setDolbyDigital:(BOOL)digital;	// 0x34c30331
- (void)setHasDigitalExtras:(BOOL)extras;	// 0x34c304d1
- (void)setWidescreen:(BOOL)widescreen andHD:(BOOL)hd;	// 0x34c2ff69
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x34c305a5
@end

