/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRUserPasswordAuthenticationResources.h"


@interface ATVMusicStoreAuthenticationResources : BRUserPasswordAuthenticationResources {
}
+ (void)initialize;	// 0x34c600ed
- (id)accountNameInstructions;	// 0x34c601cd
- (id)accountNameLabel;	// 0x34c601f5
- (id)accountNameTitle;	// 0x34c601a5
- (id)accountPasswordInstructions;	// 0x34c60245
- (id)accountPasswordLabel;	// 0x34c6026d
- (id)accountPasswordTitle;	// 0x34c6021d
- (id)authenticationFailureInstructions;	// 0x34c602d5
- (id)authenticationFailureTitle;	// 0x34c602ad
- (id)behaviorIdentifierForTextHistoryStorage;	// 0x34c603a9
- (id)behaviorsForTextHistoryDisplay;	// 0x34c603e5
- (id)clientIdentifierForTextHistoryStorage;	// 0x34c6039d
- (id)clientsForTextHistoryDisplay;	// 0x34c603b9
- (id)connectionString;	// 0x34c60171
- (id)defaultPasswordKey;	// 0x34c60295
- (id)defaultUserName;	// 0x34c602fd
- (id)defaultUserNameKey;	// 0x34c602a1
- (id)errorResolutionInstruction;	// 0x34c60411
@end

