/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class BRImageControl, BRTextControl;

__attribute__((visibility("hidden")))
@interface ATVMusicStoreRottenTomatoesRatingControl : BRControl {
@private
	BRImageControl *_freshnessImageControl;	// 44 = 0x2c
	BRTextControl *_percentageNumberControl;	// 48 = 0x30
	BRTextControl *_percentageGlyphControl;	// 52 = 0x34
}
+ (id)ratingControlWithItem:(id)item;	// 0x34c65245
- (id)initWithItem:(id)item;	// 0x34c65289
- (id)accessibilityLabel;	// 0x34c658f1
- (void)dealloc;	// 0x34c65561
- (void)layoutSubcontrols;	// 0x34c655c9
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x34c65895
@end

