/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRProvider.h"
#import <Foundation/Foundation.h> // Unknown library

@class ATVFavoritesControlFactory, NSDictionary;

__attribute__((visibility("hidden")))
@interface ATVMusicStoreFavoriteListItemProvider : NSObject <BRProvider> {
@private
	ATVFavoritesControlFactory *_factory;	// 4 = 0x4
	NSDictionary *_catalogItem;	// 8 = 0x8
}
+ (id)providerWithCatalogItem:(id)catalogItem;	// 0x34c27439
- (id)initWithCatalogItem:(id)catalogItem;	// 0x34c2746d
- (id)controlFactory;	// 0x34c27579
- (id)dataAtIndex:(long)index;	// 0x34c27551
- (long)dataCount;	// 0x34c27561
- (void)dealloc;	// 0x34c274ed
- (id)hashForDataAtIndex:(long)index;	// 0x34c27545
@end

