/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library

@class NSDictionary;

__attribute__((visibility("hidden")))
@interface ATVNameToClassMapper : NSObject {
@private
	NSDictionary *_nameToClass;	// 4 = 0x4
}
- (id)initWithPlist:(id)plist;	// 0x34c9aeb5
- (Class)classForName:(id)name;	// 0x34c9b045
- (void)dealloc;	// 0x34c9b001
@end

