/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRViewController.h"

@class NSDictionary, ATVMerchant;

__attribute__((visibility("hidden")))
@interface ATVOptionListController : BRViewController {
@private
	NSDictionary *_data;	// 64 = 0x40
	ATVMerchant *_merchant;	// 68 = 0x44
	BOOL eventHandled;	// 72 = 0x48
}
@property(readonly, assign) NSDictionary *data;	// G=0x34ca3899; @synthesize=_data
- (id)initWithDictionary:(id)dictionary;	// 0x34ca3439
- (BOOL)brEventAction:(id)action;	// 0x34ca3779
- (void)controlWasActivated;	// 0x34ca37f1
- (void)controlWasDeactivated;	// 0x34ca37b5
// declared property getter: - (id)data;	// 0x34ca3899
- (void)dealloc;	// 0x34ca36f9
- (void)wasPushed;	// 0x34ca3849
@end

