/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVAction.h"


__attribute__((visibility("hidden")))
@interface ATVPingAction : ATVAction {
}
- (void)invoke;	// 0x34c9a71d
@end

