/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRViewController.h"

@class NSTimer;

@interface ATVRebootWaitController : BRViewController {
@private
	NSTimer *_holdoffTimer;	// 64 = 0x40
	float _lastProgressPercent;	// 68 = 0x44
}
- (id)init;	// 0x34bee3f1
- (void)_holdOffScreenSaver:(id)saver;	// 0x34bee611
- (BOOL)brEventAction:(id)action;	// 0x34bee5a9
- (void)dealloc;	// 0x34bee515
- (id)secondaryProgressImagePath;	// 0x34bee5ad
- (void)setUpdatePercentage:(float)percentage;	// 0x34bee53d
- (void)wasDismissed;	// 0x34bee5d9
@end

