/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRControl.h"

@class BRMediaPlayer;

__attribute__((visibility("hidden")))
@interface ATVScreenSaverControl : BRControl {
@private
	BRMediaPlayer *_player;	// 44 = 0x2c
}
+ (id)screenSaverControlWithPlugin:(id)plugin screenSaverAutoFired:(BOOL)fired;	// 0x34c472e9
- (id)initWithPlugin:(id)plugin screenSaverAutoFired:(BOOL)fired;	// 0x34c47215
- (BOOL)_nextTrackAction:(id)action;	// 0x34c4772d
- (BOOL)_playPauseAction:(id)action;	// 0x34c476d5
- (void)_playerStateChanged:(id)changed;	// 0x34c47699
- (BOOL)_previousTrackAction:(id)action;	// 0x34c47791
- (void)_setNewPlayer:(id)player;	// 0x34c475dd
- (id)accessibilityLabel;	// 0x34c477f9
- (BOOL)brEventAction:(id)action;	// 0x34c4738d
- (void)controlWasActivated;	// 0x34c4747d
- (void)controlWasDeactivated;	// 0x34c474d9
- (void)dealloc;	// 0x34c47321
- (BOOL)isAccessibilityElement;	// 0x34c477f5
- (void)layoutSubcontrols;	// 0x34c47535
@end

