/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVMusicStoreBaseMetadataProvider.h"

@class ATVSedonaCatalogItem;

__attribute__((visibility("hidden")))
@interface ATVSedonaMovieMetadataProvider : ATVMusicStoreBaseMetadataProvider {
@private
	ATVSedonaCatalogItem *_sedonaItem;	// 12 = 0xc
}
+ (void)initialize;	// 0x34c6d905
+ (id)providerWithCatalogItem:(id)catalogItem;	// 0x34c6dc7d
- (id)init;	// 0x34c6dcb1
- (id)initWithCatalogItem:(id)catalogItem;	// 0x34c6dcc9
- (void)_populateActors:(id)actors;	// 0x34c6e2f1
- (void)_populateAudio:(id)audio;	// 0x34c6e541
- (void)_populateCategories:(id)categories;	// 0x34c6e431
- (void)_populateDirector:(id)director;	// 0x34c6e381
- (void)_populateMetadataDetails:(id)details;	// 0x34c6de1d
- (void)_populateMovieDetails:(id)details;	// 0x34c6dea1
- (void)_populateSubtitles:(id)subtitles;	// 0x34c6e4b1
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x34c6dd6d
- (void)dealloc;	// 0x34c6dd29
- (void)populateMetadataForControl:(id)control;	// 0x34c6dda5
@end

