/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library
#import "BRControlFactory.h"


__attribute__((visibility("hidden")))
@interface ATVSedonaQueueControlFactory : NSObject <BRControlFactory> {
}
+ (id)factory;	// 0x34c6f599
- (id)_menuItemForItem:(id)item currentControl:(id)control requestedBy:(id)by;	// 0x34c6f691
- (id)_previewForItem:(id)item currentControl:(id)control requestedBy:(id)by;	// 0x34c6f741
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x34c6f5bd
@end

