/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRSecureResource.h"
#import "BRController.h"

@class ATVSedonaAccount, NSString;

@interface ATVSedonaController : BRController <BRSecureResource> {
@private
	ATVSedonaAccount *_account;	// 60 = 0x3c
	NSString *_preferredURL;	// 64 = 0x40
	BOOL _autoPlay;	// 68 = 0x44
}
@property(assign, nonatomic) BOOL autoPlay;	// G=0x34c6ab25; S=0x34c6ab35; @synthesize=_autoPlay
+ (id)controller;	// 0x34c6a7d5
+ (id)controllerWithPreferredURL:(id)preferredURL;	// 0x34c6a7f9
- (id)init;	// 0x34c6a82d
- (id)initWithPreferredURL:(id)preferredURL;	// 0x34c6a8e5
// declared property getter: - (BOOL)autoPlay;	// 0x34c6ab25
- (void)controlWasActivated;	// 0x34c6a9ed
- (void)dealloc;	// 0x34c6a91d
- (BOOL)isNetworkDependent;	// 0x34c6a99d
- (void)requiredScope:(unsigned *)scope accountType:(id *)type;	// 0x34c6aaf1
// declared property setter: - (void)setAutoPlay:(BOOL)play;	// 0x34c6ab35
- (void)wasPushed;	// 0x34c6a9a1
@end

