/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRUserPasswordAuthenticationResources.h"


@interface ATVSedonaAuthenticationResources : BRUserPasswordAuthenticationResources {
}
- (id)accountNameInstructions;	// 0x34c6a675
- (id)accountNameLabel;	// 0x34c6a6a9
- (id)accountNameTitle;	// 0x34c6a6dd
- (id)accountPasswordTitle;	// 0x34c6a6e1
- (id)behaviorIdentifierForTextHistoryStorage;	// 0x34c6a76d
- (id)behaviorsForTextHistoryDisplay;	// 0x34c6a7a9
- (id)clientIdentifierForTextHistoryStorage;	// 0x34c6a75d
- (id)clientsForTextHistoryDisplay;	// 0x34c6a77d
- (id)connectionString;	// 0x34c6a641
- (id)defaultPasswordKey;	// 0x34c6a745
- (id)defaultUserNameKey;	// 0x34c6a751
- (id)titleImage;	// 0x34c6a6e5
@end

