/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "ATVMusicStoreCatalogAgent.h"


@interface ATVSedonaCatalogAgent : ATVMusicStoreCatalogAgent {
}
+ (void)_controlForURL:(id)url identifier:(id)identifier;	// 0x34c68b35
+ (id)_headerControlsForPageItem:(id)pageItem;	// 0x34c69215
+ (id)_scrollerControlsFromHeaderControls:(id)headerControls collectionControls:(id)controls;	// 0x34c69409
+ (id)catalogHandler;	// 0x34c68ad9
+ (id)mediaAssetForStoreOffer:(id)storeOffer;	// 0x34c68d4d
+ (void)playStoreItem:(id)item;	// 0x34c68c69
@end

