/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRSelectionHandler.h"
#import "ATVCatalogHandler.h"


__attribute__((visibility("hidden")))
@interface ATVSedonaCatalogHandler : ATVCatalogHandler <BRSelectionHandler> {
}
- (BOOL)handlePlayForControl:(id)control;	// 0x34c6cba1
- (BOOL)handleSelectionForControl:(id)control;	// 0x34c6c4d5
@end

