/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVMusicStoreBaseMetadataProvider.h"

@class ATVSedonaCatalogItem;

__attribute__((visibility("hidden")))
@interface ATVSedonaTVSeasonMetadataProvider : ATVMusicStoreBaseMetadataProvider {
@private
	ATVSedonaCatalogItem *_sedonaItem;	// 12 = 0xc
}
+ (void)initialize;	// 0x34c71939
+ (id)providerWithCatalogItem:(id)catalogItem;	// 0x34c71a11
- (id)init;	// 0x34c71a45
- (id)initWithCatalogItem:(id)catalogItem;	// 0x34c71a5d
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x34c71b01
- (void)dealloc;	// 0x34c71abd
- (void)populateMetadataForControl:(id)control;	// 0x34c71b39
@end

