/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library

@class NSMutableDictionary, NSMutableArray;

__attribute__((visibility("hidden")))
@interface ATVSWUpdateRecord : NSObject {
@private
	NSMutableDictionary *_currentVersions;	// 4 = 0x4
	NSMutableDictionary *_newVersions;	// 8 = 0x8
	NSMutableArray *_payloadURLs;	// 12 = 0xc
	NSMutableArray *_licenseURLs;	// 16 = 0x10
	NSMutableArray *_payloadLocalPaths;	// 20 = 0x14
	unsigned long long _totalDownloadSize;	// 24 = 0x18
	BOOL _autoUpdate;	// 32 = 0x20
	BOOL _forceFullUpdate;	// 33 = 0x21
}
@property(readonly, assign) BOOL autoUpdate;	// G=0x34c521dd; converted property
@property(assign) BOOL forceFullUpdate;	// G=0x34c520d1; S=0x34c520e1; converted property
@property(readonly, retain) NSMutableArray *licenseURLs;	// G=0x34c52231; converted property
@property(readonly, retain) NSMutableArray *payloadLocalPaths;	// G=0x34c5228d; converted property
@property(readonly, retain) NSMutableArray *payloadURLs;	// G=0x34c52205; converted property
@property(readonly, assign) unsigned long long totalDownloadSize;	// G=0x34c521ed; converted property
- (id)init;	// 0x34c51ef5
- (void)_addCurrentVersion:(id)version forType:(id)type;	// 0x34c5229d
- (void)_addDownloadSize:(unsigned long long)size;	// 0x34c522f5
- (void)_addLicenseURL:(id)url;	// 0x34c52389
- (void)_addNewVersion:(id)version forType:(id)type;	// 0x34c522c9
- (void)_addPayloadLocalPath:(id)path;	// 0x34c52359
- (void)_addPayloadURL:(id)url;	// 0x34c52329
- (void)_collectCurrentVersions;	// 0x34c523cd
- (void)_parseVersionData:(id)data;	// 0x34c523b9
- (void)addPayloadLocalPath:(id)path;	// 0x34c5225d
// converted property getter: - (BOOL)autoUpdate;	// 0x34c521dd
- (id)currentVersionOfType:(id)type;	// 0x34c5219d
- (void)dealloc;	// 0x34c52009
- (id)description;	// 0x34c520f1
// converted property getter: - (BOOL)forceFullUpdate;	// 0x34c520d1
// converted property getter: - (id)licenseURLs;	// 0x34c52231
- (id)newVersionOfType:(id)type;	// 0x34c521bd
- (int)numberOfUpdatesAvailable;	// 0x34c52151
// converted property getter: - (id)payloadLocalPaths;	// 0x34c5228d
// converted property getter: - (id)payloadURLs;	// 0x34c52205
- (void)setAutoTriggeredUpdate:(BOOL)update;	// 0x34c520c1
// converted property setter: - (void)setForceFullUpdate:(BOOL)update;	// 0x34c520e1
- (void)setVersionData:(id)data;	// 0x34c52095
// converted property getter: - (unsigned long long)totalDownloadSize;	// 0x34c521ed
- (BOOL)updateAvailableOfType:(id)type;	// 0x34c52171
@end

