/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRSingleton.h"

@class NSTimer, BRWindow, ATVScreenSaverPrefetchTask;

@interface ATVScreenSaverManager : BRSingleton {
@private
	NSTimer *_timer;	// 4 = 0x4
	double _interval;	// 8 = 0x8
	BRWindow *_window;	// 16 = 0x10
	long _state;	// 20 = 0x14
	BOOL _enabled;	// 24 = 0x18
	BOOL _screenSaverPosted;	// 25 = 0x19
	BOOL _handlingTimeoutChangeNotification;	// 26 = 0x1a
	ATVScreenSaverPrefetchTask *_prefetchTask;	// 28 = 0x1c
	BOOL _screenSaverAutoFired;	// 32 = 0x20
}
+ (id)screenSaverFaces;	// 0x34c47885
+ (id)screenSaverFacesCachePath;	// 0x34c47841
+ (void)setSingleton:(id)singleton;	// 0x34c478c1
+ (id)singleton;	// 0x34c478b5
- (id)init;	// 0x34c478cd
- (BOOL)_allowedToLoadPrincipalClassNamed:(id)loadPrincipalClassNamed;	// 0x34c48f9d
- (id)_control;	// 0x34c48691
- (void)_createTimer;	// 0x34c482e5
- (void)_dismissScreenSaver:(id)saver;	// 0x34c48759
- (void)_fadeFinished;	// 0x34c48025
- (void)_prefetchComplete:(id)complete;	// 0x34c48e49
- (void)_screenSaverArchiveChanged:(id)changed;	// 0x34c48a09
- (void)_screenSaverControllerActivate:(id)activate;	// 0x34c487d1
- (void)_screenSaverControllerDeactivate:(id)deactivate;	// 0x34c48811
- (void)_screenSaverFired:(id)fired;	// 0x34c483c9
- (void)_screenSaverIntervalChanged:(id)changed;	// 0x34c4885d
- (id)_screenSaverPlugInControl;	// 0x34c48471
- (void)_serverStatusChanged:(id)changed;	// 0x34c48b49
- (void)_startOneTimePrefetchTask:(id)task;	// 0x34c48c61
- (void)_startRepeatingPrefetchTask;	// 0x34c48d55
- (void)_stopPrefetchTask;	// 0x34c48e75
- (void)_updateActivity:(id)activity;	// 0x34c486e5
- (BOOL)_validateBundleAtPath:(id)path;	// 0x34c48f05
- (void)dealloc;	// 0x34c47ab9
- (void)enable;	// 0x34c47b65
- (id)screenSaverPathsFromDirectory:(id)directory;	// 0x34c47e6d
- (BOOL)screenSaverPrefetchActive;	// 0x34c48005
- (BOOL)screenSaverRequiresPrefetch;	// 0x34c47fa5
- (void)showScreenSaver;	// 0x34c47b91
@end

