/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRSingleton.h"


@interface ATVSettingsHelper : BRSingleton {
}
+ (void)setSingleton:(id)singleton;	// 0x34c4dc85
+ (id)singleton;	// 0x34c4dc79
- (id)init;	// 0x34c4dc91
- (void)dealloc;	// 0x34c4dcfd
- (BOOL)haveWeQuitSinceBoot;	// 0x34c4de35
- (BOOL)performObliterate;	// 0x34c4dd45
- (BOOL)performRestore;	// 0x34c4de31
- (BOOL)performUpdates:(id)updates;	// 0x34c4dd31
- (void)reboot;	// 0x34c4dec5
- (BOOL)setLowPowerMode:(BOOL)mode;	// 0x34c4dd2d
- (BOOL)setNetworkSettings:(id)settings forInterface:(int)interface;	// 0x34c4dd29
- (void)setSSHEnabled:(BOOL)enabled;	// 0x34c4ded9
- (BOOL)setSystemLanguage:(id)language;	// 0x34c4dd25
@end

