/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVSWUpdateRecord.h"


__attribute__((visibility("hidden")))
@interface ATVSWUpdateRecordV2 : ATVSWUpdateRecord {
@private
	unsigned long long _requiredSpace;	// 36 = 0x24
}
- (void)_parseVersionData:(id)data;	// 0x34c52f51
- (unsigned long long)requiredInstallationSpace;	// 0x34c52f39
@end

