/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRControl.h"
#import "AppleTV-Structs.h"

@class BRImageControl, BRAsyncImageControl, NSMutableArray, NSDictionary;

__attribute__((visibility("hidden")))
@interface ATVThunderGameCourtView : BRControl {
@private
	NSDictionary *_data;	// 44 = 0x2c
	BRAsyncImageControl *_court;	// 48 = 0x30
	BRControl *_courtContainer;	// 52 = 0x34
	BRImageControl *_courtGlass;	// 56 = 0x38
	NSMutableArray *_homePlayerCards;	// 60 = 0x3c
	NSMutableArray *_awayPlayerCards;	// 64 = 0x40
}
- (id)initWithDictionary:(id)dictionary;	// 0x34c8b295
- (id)accessibilityLabel;	// 0x34c8bd09
- (void)dealloc;	// 0x34c8b841
- (void)layoutSubcontrols;	// 0x34c8b90d
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x34c8b8e1
@end

