/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRControl.h"
#import "AppleTV-Structs.h"

@class BRTextControl, BRAsyncImageControl, NSString;
@protocol BRImageProxy;

__attribute__((visibility("hidden")))
@interface ATVThunderGameOverlayView : BRControl {
@private
	BRTextControl *_titleText;	// 44 = 0x2c
	BRControl *_divider;	// 48 = 0x30
	BRTextControl *_leftText;	// 52 = 0x34
	BRTextControl *_rightText;	// 56 = 0x38
	BRTextControl *_centerText;	// 60 = 0x3c
	BRAsyncImageControl *_leftImage;	// 64 = 0x40
	BRAsyncImageControl *_rightImage;	// 68 = 0x44
	BRControl *_centerBackgroundImageContainer;	// 72 = 0x48
	BRAsyncImageControl *_centerBackgroundImage;	// 76 = 0x4c
}
@property(retain) id<BRImageProxy> centerBackgroundImageProxy;	// G=0x34c92ef9; S=0x34c92f19; 
@property(copy) NSString *centerText;	// G=0x34c92e25; S=0x34c92e55; 
@property(retain) id<BRImageProxy> leftImageProxy;	// G=0x34c92eb9; S=0x34c92ed9; 
@property(copy) NSString *leftText;	// G=0x34c92cfd; S=0x34c92d2d; 
@property(retain) id<BRImageProxy> rightImageProxy;	// G=0x34c92f39; S=0x34c92f59; 
@property(copy) NSString *rightText;	// G=0x34c92d91; S=0x34c92dc1; 
@property(copy) NSString *titleText;	// G=0x34c92c69; S=0x34c92c99; 
- (id)init;	// 0x34c9230d
// declared property getter: - (id)centerBackgroundImageProxy;	// 0x34c92ef9
// declared property getter: - (id)centerText;	// 0x34c92e25
- (void)dealloc;	// 0x34c926c5
- (void)layoutSubcontrols;	// 0x34c927b1
// declared property getter: - (id)leftImageProxy;	// 0x34c92eb9
// declared property getter: - (id)leftText;	// 0x34c92cfd
// declared property getter: - (id)rightImageProxy;	// 0x34c92f39
// declared property getter: - (id)rightText;	// 0x34c92d91
// declared property setter: - (void)setCenterBackgroundImageProxy:(id)proxy;	// 0x34c92f19
// declared property setter: - (void)setCenterText:(id)text;	// 0x34c92e55
// declared property setter: - (void)setLeftImageProxy:(id)proxy;	// 0x34c92ed9
// declared property setter: - (void)setLeftText:(id)text;	// 0x34c92d2d
// declared property setter: - (void)setRightImageProxy:(id)proxy;	// 0x34c92f59
// declared property setter: - (void)setRightText:(id)text;	// 0x34c92dc1
// declared property setter: - (void)setTitleText:(id)text;	// 0x34c92c99
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x34c92799
// declared property getter: - (id)titleText;	// 0x34c92c69
@end

