/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "NSStreamDelegate.h"
#import <Foundation/Foundation.h> // Unknown library

@class NSInputStream, NSOutputStream, ATVTCPControlReceiver, NSMutableArray, NSMutableData, NSData;

__attribute__((visibility("hidden")))
@interface ATVTCPConnection : NSObject <NSStreamDelegate> {
@private
	id _delegate;	// 4 = 0x4
	NSData *_peerAddress;	// 8 = 0x8
	ATVTCPControlReceiver *_server;	// 12 = 0xc
	NSMutableArray *_requests;	// 16 = 0x10
	NSInputStream *_istream;	// 20 = 0x14
	NSOutputStream *_ostream;	// 24 = 0x18
	NSMutableData *_ibuffer;	// 28 = 0x1c
	NSMutableData *_obuffer;	// 32 = 0x20
	BOOL _isValid;	// 36 = 0x24
}
@property(assign) id delegate;	// G=0x34c45511; S=0x34c45521; converted property
@property(readonly, assign) BOOL isValid;	// G=0x34c45551; converted property
@property(readonly, retain) NSData *peerAddress;	// G=0x34c45531; converted property
@property(readonly, retain) ATVTCPControlReceiver *server;	// G=0x34c45541; converted property
- (id)init;	// 0x34c45369
- (id)initWithPeerAddress:(id)peerAddress inputStream:(id)stream outputStream:(id)stream3 forServer:(id)server;	// 0x34c45381
- (void)dealloc;	// 0x34c454bd
// converted property getter: - (id)delegate;	// 0x34c45511
- (void)invalidate;	// 0x34c45561
// converted property getter: - (BOOL)isValid;	// 0x34c45551
// converted property getter: - (id)peerAddress;	// 0x34c45531
- (BOOL)processIncomingBytes;	// 0x34c4567d
// converted property getter: - (id)server;	// 0x34c45541
// converted property setter: - (void)setDelegate:(id)delegate;	// 0x34c45521
- (void)stream:(id)stream handleEvent:(unsigned)event;	// 0x34c45715
@end

