/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRController.h"


@interface ATVThunderController : BRController {
}
+ (id)controller;	// 0x34c84849
+ (void)initialize;	// 0x34c847b9
- (id)init;	// 0x34c8486d
- (void)_bootstrapCompleteNotification:(id)notification;	// 0x34c84a51
- (void)dealloc;	// 0x34c84895
- (BOOL)isNetworkDependent;	// 0x34c848bd
- (void)wasPopped;	// 0x34c849fd
- (void)wasPushed;	// 0x34c848c1
@end

