/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRUserPasswordAuthenticationResources.h"


__attribute__((visibility("hidden")))
@interface ATVThunderAuthenticationResources : BRUserPasswordAuthenticationResources {
}
- (id)accountNameInstructions;	// 0x34c7e195
- (id)accountNameLabel;	// 0x34c7e1b1
- (id)accountNameTitle;	// 0x34c7e1cd
- (id)accountPasswordTitle;	// 0x34c7e1d1
- (id)behaviorIdentifierForTextHistoryStorage;	// 0x34c7e23d
- (id)behaviorsForTextHistoryDisplay;	// 0x34c7e279
- (id)clientIdentifierForTextHistoryStorage;	// 0x34c7e231
- (id)clientsForTextHistoryDisplay;	// 0x34c7e24d
- (id)connectionString;	// 0x34c7e179
- (id)defaultPasswordKey;	// 0x34c7e219
- (id)defaultUserNameKey;	// 0x34c7e225
- (id)titleImage;	// 0x34c7e1d5
@end

