/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVThunderXMLParser.h"
#import <Foundation/Foundation.h> // Unknown library

@class ATVThunderGame, NSMutableArray, NSString, NSDate, NSArray, NSDateFormatter;

__attribute__((visibility("hidden")))
@interface ATVThunderGamesByDayParser : NSObject <ATVThunderXMLParser> {
@private
	NSMutableArray *_daysGames;	// 4 = 0x4
	ATVThunderGame *_currentGame;	// 8 = 0x8
	NSString *_currentDate;	// 12 = 0xc
	NSDate *_currentGameDate;	// 16 = 0x10
	BOOL _anyLiveGames;	// 20 = 0x14
	NSDateFormatter *_dateReadingFormatter;	// 24 = 0x18
	NSDateFormatter *_gameTimeFormatter;	// 28 = 0x1c
}
@property(retain, nonatomic) NSArray *daysGames;	// G=0x34c827a5; S=0x34c827b5; @synthesize=_daysGames
- (id)init;	// 0x34c815e9
- (id)createStorePage;	// 0x34c81785
- (id)createStorePageForError:(int)error;	// 0x34c81fe1
// declared property getter: - (id)daysGames;	// 0x34c827a5
- (void)dealloc;	// 0x34c816f9
- (void)parser:(id)parser didEndElement:(id)element namespaceURI:(id)uri qualifiedName:(id)name;	// 0x34c8273d
- (void)parser:(id)parser didStartElement:(id)element namespaceURI:(id)uri qualifiedName:(id)name attributes:(id)attributes;	// 0x34c82101
// declared property setter: - (void)setDaysGames:(id)games;	// 0x34c827b5
@end

