/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRProvider.h"
#import "ATVSearchController.h"
#import "BRSelectionHandler.h"
#import "BRControlFactory.h"

@class NSArray;

@interface ATVTimeZoneChooserController : ATVSearchController <BRProvider, BRControlFactory, BRSelectionHandler> {
@private
	NSArray *_matchedCities;	// 132 = 0x84
}
+ (void)initialize;	// 0x34c9d65d
- (id)init;	// 0x34c9d6e1
- (id)controlFactory;	// 0x34c9d909
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x34c9d97d
- (id)dataAtIndex:(long)index;	// 0x34c9d92d
- (long)dataCount;	// 0x34c9d90d
- (void)dealloc;	// 0x34c9d7dd
- (BOOL)handleSelectionForControl:(id)control;	// 0x34c9da79
- (id)hashForDataAtIndex:(long)index;	// 0x34c9d94d
- (void)setMatchedCities:(id)cities;	// 0x34c9d8d1
- (void)wasPopped;	// 0x34c9d885
- (void)wasPushed;	// 0x34c9d821
@end

