/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRViewController.h"

@class ATVThunderStandingsView, NSDictionary;

__attribute__((visibility("hidden")))
@interface ATVThunderStandingsController : BRViewController {
@private
	ATVThunderStandingsView *_standingsView;	// 64 = 0x40
	NSDictionary *_data;	// 68 = 0x44
}
- (id)initWithDictionary:(id)dictionary;	// 0x34c8c57d
- (float)_headerWidthOfColumn:(long)column forTableView:(id)tableView;	// 0x34c8cfb5
- (float)_widthOfColumn:(long)column forTableView:(id)tableView;	// 0x34c8cef1
- (id)accessibilityLabel;	// 0x34c8ceb1
- (id)accessibilityNonFocusableElements;	// 0x34c8ced1
- (void)dealloc;	// 0x34c8c88d
- (float)headerHeightForTableView:(id)tableView;	// 0x34c8ce9d
- (BOOL)isAccessibilityElement;	// 0x34c8cead
- (long)numberOfColumnsInTableView:(id)tableView;	// 0x34c8c925
- (long)numberOfHeaderColumnsInTableView:(id)tableView;	// 0x34c8c965
- (long)numberOfRowsInTableView:(id)tableView;	// 0x34c8c8e5
- (id)tableView:(id)view headerForColumn:(long)column;	// 0x34c8cca9
- (float)tableView:(id)view heightForRow:(long)row;	// 0x34c8ce8d
- (id)tableView:(id)view itemForRow:(long)row inColumn:(long)column;	// 0x34c8c9a5
- (float)tableView:(id)view widthForColumn:(long)column;	// 0x34c8ce55
- (float)tableView:(id)view widthForHeaderColumn:(long)headerColumn;	// 0x34c8ce71
@end

