/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library

@class NSString, NSDate;

__attribute__((visibility("hidden")))
@interface ATVThunderGame : NSObject {
@private
	NSString *gameId;	// 4 = 0x4
	BOOL live;	// 8 = 0x8
	BOOL final;	// 9 = 0x9
	NSString *gameState;	// 12 = 0xc
	NSDate *startTime;	// 16 = 0x10
	NSDate *gameDate;	// 20 = 0x14
	NSString *gameClock;	// 24 = 0x18
	NSString *gamePeriod;	// 28 = 0x1c
	NSString *awayTeamAbbrev;	// 32 = 0x20
	NSString *awayTeamRecord;	// 36 = 0x24
	NSString *awayTeamScore;	// 40 = 0x28
	NSString *homeTeamAbbrev;	// 44 = 0x2c
	NSString *homeTeamRecord;	// 48 = 0x30
	NSString *homeTeamScore;	// 52 = 0x34
	BOOL blackout;	// 56 = 0x38
	BOOL onAir;	// 57 = 0x39
	BOOL archiveAvailable;	// 58 = 0x3a
	int archiveOffsetSec;	// 60 = 0x3c
}
@property(assign, nonatomic) BOOL archiveAvailable;	// G=0x34c839a9; S=0x34c839b9; @synthesize
@property(assign, nonatomic) int archiveOffsetSec;	// G=0x34c839c9; S=0x34c839d9; @synthesize
@property(retain, nonatomic) NSString *awayTeamAbbrev;	// G=0x34c83831; S=0x34c83841; @synthesize
@property(retain, nonatomic) NSString *awayTeamRecord;	// G=0x34c83865; S=0x34c83875; @synthesize
@property(retain, nonatomic) NSString *awayTeamScore;	// G=0x34c83899; S=0x34c838a9; @synthesize
@property(assign, nonatomic) BOOL blackout;	// G=0x34c83969; S=0x34c83979; @synthesize
@property(assign, nonatomic) BOOL final;	// G=0x34c8370d; S=0x34c8371d; @synthesize
@property(retain, nonatomic) NSString *gameClock;	// G=0x34c837c9; S=0x34c837d9; @synthesize
@property(retain, nonatomic) NSDate *gameDate;	// G=0x34c83795; S=0x34c837a5; @synthesize
@property(retain, nonatomic) NSString *gameId;	// G=0x34c836b9; S=0x34c836c9; @synthesize
@property(retain, nonatomic) NSString *gamePeriod;	// G=0x34c837fd; S=0x34c8380d; @synthesize
@property(retain, nonatomic) NSString *gameState;	// G=0x34c8372d; S=0x34c8373d; @synthesize
@property(retain, nonatomic) NSString *homeTeamAbbrev;	// G=0x34c838cd; S=0x34c838dd; @synthesize
@property(retain, nonatomic) NSString *homeTeamRecord;	// G=0x34c83901; S=0x34c83911; @synthesize
@property(retain, nonatomic) NSString *homeTeamScore;	// G=0x34c83935; S=0x34c83945; @synthesize
@property(assign, nonatomic) BOOL live;	// G=0x34c836ed; S=0x34c836fd; @synthesize
@property(assign, nonatomic) BOOL onAir;	// G=0x34c83989; S=0x34c83999; @synthesize
@property(retain, nonatomic) NSDate *startTime;	// G=0x34c83761; S=0x34c83771; @synthesize
+ (id)stringForPeriod:(int)period;	// 0x34c828e5
- (id)_accessibilityLabel;	// 0x34c839e9
// declared property getter: - (BOOL)archiveAvailable;	// 0x34c839a9
// declared property getter: - (int)archiveOffsetSec;	// 0x34c839c9
// declared property getter: - (id)awayTeamAbbrev;	// 0x34c83831
// declared property getter: - (id)awayTeamRecord;	// 0x34c83865
// declared property getter: - (id)awayTeamScore;	// 0x34c83899
// declared property getter: - (BOOL)blackout;	// 0x34c83969
- (id)createMediaAsset;	// 0x34c82955
- (id)createPlaySelectEventHandlerWithMediaAsset:(id)mediaAsset;	// 0x34c82e61
- (id)createStoreSportingEvent;	// 0x34c82f2d
- (id)createTopShelfPoster;	// 0x34c83321
- (void)dealloc;	// 0x34c827d9
// declared property getter: - (BOOL)final;	// 0x34c8370d
// declared property getter: - (id)gameClock;	// 0x34c837c9
// declared property getter: - (id)gameDate;	// 0x34c83795
// declared property getter: - (id)gameId;	// 0x34c836b9
// declared property getter: - (id)gamePeriod;	// 0x34c837fd
// declared property getter: - (id)gameState;	// 0x34c8372d
// declared property getter: - (id)homeTeamAbbrev;	// 0x34c838cd
// declared property getter: - (id)homeTeamRecord;	// 0x34c83901
// declared property getter: - (id)homeTeamScore;	// 0x34c83935
// declared property getter: - (BOOL)live;	// 0x34c836ed
// declared property getter: - (BOOL)onAir;	// 0x34c83989
// declared property setter: - (void)setArchiveAvailable:(BOOL)available;	// 0x34c839b9
// declared property setter: - (void)setArchiveOffsetSec:(int)sec;	// 0x34c839d9
// declared property setter: - (void)setAwayTeamAbbrev:(id)abbrev;	// 0x34c83841
// declared property setter: - (void)setAwayTeamRecord:(id)record;	// 0x34c83875
// declared property setter: - (void)setAwayTeamScore:(id)score;	// 0x34c838a9
// declared property setter: - (void)setBlackout:(BOOL)blackout;	// 0x34c83979
// declared property setter: - (void)setFinal:(BOOL)final;	// 0x34c8371d
// declared property setter: - (void)setGameClock:(id)clock;	// 0x34c837d9
// declared property setter: - (void)setGameDate:(id)date;	// 0x34c837a5
// declared property setter: - (void)setGameId:(id)anId;	// 0x34c836c9
// declared property setter: - (void)setGamePeriod:(id)period;	// 0x34c8380d
// declared property setter: - (void)setGameState:(id)state;	// 0x34c8373d
// declared property setter: - (void)setHomeTeamAbbrev:(id)abbrev;	// 0x34c838dd
// declared property setter: - (void)setHomeTeamRecord:(id)record;	// 0x34c83911
// declared property setter: - (void)setHomeTeamScore:(id)score;	// 0x34c83945
// declared property setter: - (void)setLive:(BOOL)live;	// 0x34c836fd
// declared property setter: - (void)setOnAir:(BOOL)air;	// 0x34c83999
// declared property setter: - (void)setStartTime:(id)time;	// 0x34c83771
// declared property getter: - (id)startTime;	// 0x34c83761
@end

