/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "NSXMLParserDelegate.h"
#import "BRUserPasswordAuthenticator.h"

@class NSMutableDictionary, NSMutableString, NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface ATVThunderAuthenticator : BRUserPasswordAuthenticator <NSXMLParserDelegate> {
@private
	BOOL _requestSucceded;	// 5 = 0x5
	NSMutableString *_currentProperty;	// 8 = 0x8
	NSMutableDictionary *_currentError;	// 12 = 0xc
	NSMutableArray *_currentErrors;	// 16 = 0x10
	NSString *_currentPrivilege;	// 20 = 0x14
	NSMutableArray *_currentPrivileges;	// 24 = 0x18
	NSMutableArray *_currentChoiceTeams;	// 28 = 0x1c
}
- (id)_URLRequestForURL:(id)url withFormData:(id)formData;	// 0x34ca0fc5
- (void)_configureProductType;	// 0x34ca12b9
- (void)_failAuthenticationWithError:(id)error;	// 0x34ca1239
- (void)_handleLocationResponse:(id)response;	// 0x34ca18ed
- (BOOL)_isAuthorizing;	// 0x34ca0f39
- (void)_notifyAccountIsAuthenticated;	// 0x34ca12a5
- (void)_receiveResponse:(id)response;	// 0x34ca10bd
- (void)_sendAuthenticationRequest;	// 0x34ca1441
- (void)_sendAuthorizationRequest;	// 0x34ca15a9
- (void)_sendLocationRequest;	// 0x34ca172d
- (void)_sendPing;	// 0x34ca1a69
- (void)dealloc;	// 0x34ca0ee5
- (void)parser:(id)parser didEndElement:(id)element namespaceURI:(id)uri qualifiedName:(id)name;	// 0x34ca1d99
- (void)parser:(id)parser didStartElement:(id)element namespaceURI:(id)uri qualifiedName:(id)name attributes:(id)attributes;	// 0x34ca1af9
- (void)parser:(id)parser foundCharacters:(id)characters;	// 0x34ca2085
- (BOOL)requiresPassword:(id *)password;	// 0x34ca0f5d
@end

