/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRURLDocument.h"
#import "AppleTV-Structs.h"


@interface ATVURLDocument : BRURLDocument {
@private
	id _requestBlock;	// 52 = 0x34
	id _propertyList;	// 56 = 0x38
}
@property(readonly, retain) id propertyList;	// G=0x34c3898d; converted property
+ (id)documentWithRequestBlock:(id)requestBlock;	// 0x34c37d55
- (id)initWithRequestBlock:(id)requestBlock;	// 0x34c37d89
- (id)URLRequest;	// 0x34c37e31
- (void)_deserializePlist;	// 0x34c38a51
- (void)_documentLoadedPhase2WithHandlerQueue:(dispatch_queue_s *)handlerQueue withCompletionHandler:(id)completionHandler;	// 0x34c384ad
- (void)_evaluateBootstrapScriptsInResource:(id)resource inContext:(id)context withCompletionHandler:(id)completionHandler;	// 0x34c387bd
- (void)_evaluatePlist;	// 0x34c39029
- (void)_evaluateScripts:(id)scripts withContext:(id)context withCompletionHandler:(id)completionHandler;	// 0x34c38665
- (id)_merchantFromFeed;	// 0x34c38ac9
- (void)_preProcessXML;	// 0x34c3899d
- (void)_processHeadElements:(id)elements;	// 0x34c38f45
- (void)_processNextHeadElement:(id)element merchant:(id)merchant completionHandler:(id)handler;	// 0x34c38b6d
- (void)dealloc;	// 0x34c37dd9
- (void)documentLoadedWithCompletionHandler:(id)completionHandler;	// 0x34c37ea1
// converted property getter: - (id)propertyList;	// 0x34c3898d
@end

