/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVStoreFavorite.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface ATVWishListFavorite : ATVStoreFavorite {
@private
	NSString *_adamID;	// 64 = 0x40
}
- (id)initWithDictionary:(id)dictionary;	// 0x34bf7b41
- (BOOL)_setupWithCatalogItem:(id)catalogItem;	// 0x34bf7939
- (void)dealloc;	// 0x34bf7ba9
- (void)encodeWithDictionary:(id)dictionary;	// 0x34bf7bed
- (id)itemID;	// 0x34bf7c41
- (void)remove;	// 0x34bf7cb9
- (BOOL)removeUponAcquisition;	// 0x34bf7c51
- (void)save;	// 0x34bf7c55
@end

