/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface AudioData : NSObject {
@private
	int flags;	// 4 = 0x4
	int pid;	// 8 = 0x8
	int audioFormat;	// 12 = 0xc
	int channelCount;	// 16 = 0x10
	int sampleCount;	// 20 = 0x14
	NSString *audioLanguageCode;	// 24 = 0x18
}
- (id)initWithBuffer:(id)buffer;	// 0x34de86d4
- (void)dealloc;	// 0x34de8674
- (int)getAudioFormat;	// 0x34de8624
- (id)getAudioLanguageCode;	// 0x34de8660
- (int)getChannelCount;	// 0x34de8638
- (int)getFlags;	// 0x34de85fc
- (int)getPID;	// 0x34de8610
- (int)getSampleCount;	// 0x34de864c
@end

