/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library


__attribute__((visibility("hidden")))
@interface Base64 : NSObject {
}
+ (id)decode:(id)decode;	// 0x34e0698c
+ (id)decode:(const char *)decode length:(int)length;	// 0x34e069f8
+ (id)encode:(id)encode;	// 0x34e06b68
+ (id)encode:(const char *)encode length:(int)length;	// 0x34e06bd0
+ (void)initialize;	// 0x34e06d44
@end

