/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRMediaShelfView.h"
#import "AppleTV-Structs.h"


__attribute__((visibility("hidden")))
@interface BRActionShelfControl : BRMediaShelfView {
@private
	int _style;	// 252 = 0xfc
	long _previousIndex;	// 256 = 0x100
}
@property(assign) int actionControlStyle;	// G=0x34cf33b5; S=0x34cf33a5; converted property
// converted property getter: - (int)actionControlStyle;	// 0x34cf33b5
- (id)focusedControlForEvent:(id)event focusPoint:(CGPoint *)point;	// 0x34cf32b9
// converted property setter: - (void)setActionControlStyle:(int)style;	// 0x34cf33a5
@end

