/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRSingleton.h"

@class NSString, NSMutableDictionary, NSMutableArray;

@interface BRAccountManager : BRSingleton {
@private
	NSString *_accountPath;	// 4 = 0x4
	NSString *_dataPath;	// 8 = 0x8
	NSMutableArray *_accounts;	// 12 = 0xc
	NSMutableDictionary *_accountTypes;	// 16 = 0x10
	NSMutableDictionary *_preferredAccounts;	// 20 = 0x14
	NSMutableArray *_pendingAccounts;	// 24 = 0x18
}
+ (void)initialize;	// 0x34d8d8e1
+ (void)setSingleton:(id)singleton;	// 0x34d8d8d5
+ (id)singleton;	// 0x34d8d8c9
- (id)init;	// 0x34d8d979
- (void)_accountDirty:(id)dirty;	// 0x34d8f2fd
- (void)_deleteAccount:(id)account;	// 0x34d8f205
- (void)_load;	// 0x34d8e9c5
- (id)_loadAccountFromFilePath:(id)filePath;	// 0x34d8f0dd
- (void)_save;	// 0x34d8ed65
- (void)_saveAccount:(id)account;	// 0x34d8eea5
- (void)_saveAccount:(id)account flushDiskImmediately:(BOOL)immediately;	// 0x34d8eebd
- (void)_savePrefs;	// 0x34d8f035
- (id)accountWithName:(id)name ofType:(id)type;	// 0x34d8e249
- (id)accountWithName:(id)name ofType:(id)type create:(BOOL)create;	// 0x34d8e269
- (id)accountsOfType:(id)type;	// 0x34d8e3ed
- (id)allAccounts;	// 0x34d8e3c1
- (void)clearPreferredAccountForType:(id)type;	// 0x34d8df11
- (void)dealloc;	// 0x34d8db11
- (void)evaluatePendingAccounts;	// 0x34d8dbd9
- (BOOL)isAccountManaged:(id)managed;	// 0x34d8e439
- (void)manageAccount:(id)account;	// 0x34d8e4f9
- (void)markAsPreferredAccount:(id)account;	// 0x34d8e049
- (id)preferredAccountForType:(id)type;	// 0x34d8ddc5
- (void)registerClass:(Class)aClass forType:(id)type;	// 0x34d8e845
- (void)removeAccount:(id)account;	// 0x34d8e645
@end

