/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import <Foundation/Foundation.h> // Unknown library


@interface BRAirportManager : NSObject {
}
+ (BOOL)associateWithNetwork:(id)network password:(id)password error:(id *)error;	// 0x34d9043d
+ (void)checkAirportPower;	// 0x34d8fccd
+ (void)collectWirelessNetworks;	// 0x34d8fea9
+ (void)collectWirelessNetworksWithSSID:(id)ssid;	// 0x34d8fec9
+ (WiFiDeviceClient *)copyCurrentWiFiDeviceClient;	// 0x34d8fe49
+ (id)currentWirelessBSSID;	// 0x34d90381
+ (int)currentWirelessChannel;	// 0x34d902f5
+ (void)forgetCurrentNetworkWithError:(id *)error;	// 0x34d90845
+ (void)forgetNetwork:(id)network error:(id *)error;	// 0x34d908d5
+ (void)forgetWiFiNetwork:(WiFiNetwork *)network error:(id *)error;	// 0x34d9090d
+ (float)getCurrentRawWirelessSignalStrength;	// 0x34d901f5
+ (int)getCurrentWirelessSignalStrength;	// 0x34d9028d
+ (int)getCurrentWirelessSignalStrengthForMaxBars:(unsigned char)maxBars;	// 0x34d902ad
+ (void)initialize;	// 0x34d8fb8d
+ (id)wirelessInterfaceName;	// 0x34d8fe11
@end

