/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library

@class NSArray, NSDictionary;

__attribute__((visibility("hidden")))
@interface BRApplianceCategoryListProvider : NSObject {
@private
	NSArray *_categories;	// 4 = 0x4
	NSDictionary *_attributes;	// 8 = 0x8
}
@property(retain) NSArray *categories;	// G=0x34cf6ae1; S=0x34cf6a41; converted property
@property(retain) id textAttributes;	// G=0x34cf6a31; S=0x34cf69f9; converted property
// converted property getter: - (id)categories;	// 0x34cf6ae1
- (long)categoryIndexForIdentifier:(id)identifier;	// 0x34cf6b61
- (void)dealloc;	// 0x34cf69a1
- (long)defaultCategoryIndex;	// 0x34cf6af1
- (id)list:(id)list menuItemForRowAtIndexPath:(id)indexPath;	// 0x34cf6be1
- (long)list:(id)list numberOfRowsInSection:(long)section;	// 0x34cf6c89
- (id)list:(id)list sectionHeaderForSection:(long)section;	// 0x34cf6cb1
- (long)numberOfSectionsInList:(id)list;	// 0x34cf6c85
// converted property setter: - (void)setCategories:(id)categories;	// 0x34cf6a41
// converted property setter: - (void)setTextAttributes:(id)attributes;	// 0x34cf69f9
// converted property getter: - (id)textAttributes;	// 0x34cf6a31
@end

