/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import <Foundation/Foundation.h> // Unknown library

@class NSAutoreleasePool, BREvent, NSMutableArray, NSTimer;
@protocol BRResponder;

@interface BRApplication : NSObject {
@private
	id _delegate;	// 4 = 0x4
	NSObject<BRResponder> *_firstResponder;	// 8 = 0x8
	BREvent *_currentEvent;	// 12 = 0xc
	NSTimer *_retriggerTimer;	// 16 = 0x10
	NSTimer *_b39PlayPauseHoldTimer;	// 20 = 0x14
	NSMutableArray *_eventQueue;	// 24 = 0x18
	NSAutoreleasePool *_runLoopPool;	// 28 = 0x1c
	CFRunLoopSourceRef _source;	// 32 = 0x20
	CFRunLoopRef _mainRunLoop;	// 36 = 0x24
	double _flushBeforeTimeStamp;	// 40 = 0x28
	long _retriggerCount;	// 48 = 0x30
	double _nextRetriggerDelay;	// 52 = 0x34
	BOOL _handlingEvent;	// 60 = 0x3c
	BOOL _isInModalLoop;	// 61 = 0x3d
	BOOL _eventsBlocked;	// 62 = 0x3e
	BOOL _delegateRetained;	// 63 = 0x3f
	BOOL _isTerminating;	// 64 = 0x40
	BOOL _b39PlayPauseHoldTimerFired;	// 65 = 0x41
}
@property(readonly, retain) BREvent *currentEvent;	// G=0x34d924bd; converted property
@property(assign) id delegate;	// G=0x34d923ad; S=0x34d92361; converted property
@property(retain) id firstResponder;	// G=0x34d924ad; S=0x34d9249d; converted property
@property(assign) BOOL ignorePlayPauseEvents;	// G=0x34d929f9; S=0x34d929d1; converted property
@property(assign) BOOL isInModalLoop;	// G=0x34d92761; S=0x34d92751; converted property
@property(readonly, assign) BOOL isTerminating;	// G=0x34d9248d; converted property
@property(readonly, assign) double nextRetriggerDelay;	// G=0x34d929b9; converted property
@property(readonly, assign) long retriggerCount;	// G=0x34d929a9; converted property
+ (id)sharedApplication;	// 0x34d9216d
- (id)init;	// 0x34d921b5
- (BOOL)_b39PlayPauseHoldTimerFired;	// 0x34d93945
- (void)_blockEvents;	// 0x34d92a1d
- (void)_drainRunLoopPool;	// 0x34d92ed1
- (void)_handleB39PlayPauseTimerFire:(id)fire;	// 0x34d93925
- (void)_handler;	// 0x34d92bd1
- (void)_registerForEvents;	// 0x34d9301d
- (void)_retriggerEvent:(id)event;	// 0x34d92f8d
- (void)_run;	// 0x34d92a75
- (void)_setB39PlayPauseHoldTimer:(id)timer;	// 0x34d938ed
- (void)_setRetainedDelegate:(id)delegate;	// 0x34d92fe1
- (void)_unblockEvents;	// 0x34d92a39
- (void)cancelRetriggerCurrentEvent;	// 0x34d92885
// converted property getter: - (id)currentEvent;	// 0x34d924bd
- (void)dealloc;	// 0x34d922e9
// converted property getter: - (id)delegate;	// 0x34d923ad
- (void)dispatchEventOnEventThread:(id)thread;	// 0x34d92635
- (void)emptyQueue;	// 0x34d92665
// converted property getter: - (id)firstResponder;	// 0x34d924ad
// converted property getter: - (BOOL)ignorePlayPauseEvents;	// 0x34d929f9
// converted property getter: - (BOOL)isInModalLoop;	// 0x34d92761
// converted property getter: - (BOOL)isTerminating;	// 0x34d9248d
// converted property getter: - (double)nextRetriggerDelay;	// 0x34d929b9
- (void)postEvent:(id)event;	// 0x34d924cd
// converted property getter: - (long)retriggerCount;	// 0x34d929a9
- (void)retriggerCurrentEvent;	// 0x34d92771
- (void)retriggerCurrentEventAfterDelay:(double)delay;	// 0x34d927ed
- (void)retriggerCurrentEventWithDecreasingDelay;	// 0x34d9278d
// converted property setter: - (void)setDelegate:(id)delegate;	// 0x34d92361
// converted property setter: - (void)setFirstResponder:(id)responder;	// 0x34d9249d
// converted property setter: - (void)setIgnorePlayPauseEvents:(BOOL)events;	// 0x34d929d1
// converted property setter: - (void)setIsInModalLoop:(BOOL)modalLoop;	// 0x34d92751
- (void)terminate;	// 0x34d923bd
@end

