/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class NSString, BRAsyncTask, BRWaitSpinnerControl, BRImage, BRImageControl;
@protocol BRImageProxy;

@interface BRAsyncImageControl : BRControl {
@private
	id<BRImageProxy> _imageProxy;	// 44 = 0x2c
	BRWaitSpinnerControl *_spinner;	// 48 = 0x30
	BRImage *_image;	// 52 = 0x34
	BRImage *_defaultImage;	// 56 = 0x38
	BRAsyncTask *_imageProcessingTask;	// 60 = 0x3c
	NSString *_imageID;	// 64 = 0x40
	BOOL _cropAndFill;	// 68 = 0x44
	BOOL _useLoadingSpinner;	// 69 = 0x45
	BOOL _loadFailure;	// 70 = 0x46
	BOOL _imageLoadRequested;	// 71 = 0x47
	BOOL _useLoadFailureImage;	// 72 = 0x48
	BOOL _loadOnActivation;	// 73 = 0x49
	BOOL _okToLoadImage;	// 74 = 0x4a
	BOOL _useFadeInAnimation;	// 75 = 0x4b
	int _requestedSize;	// 76 = 0x4c
	BRImageControl *_badgeImageControl;	// 80 = 0x50
	float _badgeUnfocusedOpacity;	// 84 = 0x54
	float _badgeFocusedOpacity;	// 88 = 0x58
	BOOL _upscalesImage;	// 92 = 0x5c
}
@property(retain) BRImage *image;	// G=0x34cf7a91; S=0x34cf7a7d; converted property
@property(retain) id imageProxy;	// G=0x34cf7a4d; S=0x34cf7a15; converted property
@property(assign, nonatomic) BOOL upscalesImage;	// G=0x34cf84a9; S=0x34cf84b9; @synthesize=_upscalesImage
+ (id)imageControlWithImage:(id)image;	// 0x34cf78ad
+ (id)imageControlWithImageProxy:(id)imageProxy;	// 0x34cf7811
- (id)initWithImage:(id)image;	// 0x34cf78f9
- (id)initWithImageProxy:(id)imageProxy;	// 0x34cf7851
- (void)_checkImageSize:(id)size;	// 0x34cf884d
- (void)_cropImage:(id)image;	// 0x34cf8d75
- (void)_enableFadeInAnimation;	// 0x34cf84c9
- (void)_enableSpinner;	// 0x34cf8579
- (void)_fetchCachedThumbnailImage;	// 0x34cf85ad
- (void)_fetchPreferredSizeImage;	// 0x34cf8709
- (id)_getImageFromImageManagerNamed:(id)imageManagerNamed withSize:(CGSize)size;	// 0x34cf8fb5
- (id)_imageOfSize:(int)size;	// 0x34cf8bfd
- (void)_imageTaskComplete:(id)complete;	// 0x34cf8f11
- (void)_imageUnavailable:(id)unavailable;	// 0x34cf90d9
- (void)_imageUpdated:(id)updated;	// 0x34cf9015
- (void)_scaleImage:(id)image;	// 0x34cf8e49
- (void)_setImage:(id)image;	// 0x34cf91a1
- (void)_setImageID:(id)anId;	// 0x34cf925d
- (void)_startImageProcessingTaskForImage:(id)image;	// 0x34cf89b9
- (void)_updateContents;	// 0x34cf9295
- (id)accessibilityLabel;	// 0x34cf81a1
- (id)accessibilityTraits;	// 0x34cf8171
- (void)cancelImageLoading;	// 0x34cf7ad5
- (void)controlWasActivated;	// 0x34cf7b85
- (void)controlWasDeactivated;	// 0x34cf7c4d
- (void)controlWasFocused;	// 0x34cf7cd5
- (void)controlWasUnfocused;	// 0x34cf7d25
- (void)dealloc;	// 0x34cf794d
// converted property getter: - (id)image;	// 0x34cf7a91
// converted property getter: - (id)imageProxy;	// 0x34cf7a4d
- (BOOL)isAccessibilityElement;	// 0x34cf819d
- (void)layoutSubcontrols;	// 0x34cf7f29
- (void)loadImage;	// 0x34cf7ab1
- (void)setBadgeImage:(id)image badgeUnfocusedOpacity:(float)opacity badgeFocusedOpacity:(float)opacity3;	// 0x34cf7dfd
- (void)setCropAndFill:(BOOL)fill;	// 0x34cf7dcd
- (void)setDefaultImage:(id)image;	// 0x34cf7d75
// converted property setter: - (void)setImage:(id)image;	// 0x34cf7a7d
// converted property setter: - (void)setImageProxy:(id)proxy;	// 0x34cf7a15
- (void)setLoadImageOnActivation:(BOOL)activation;	// 0x34cf7aa1
// declared property setter: - (void)setUpscalesImage:(BOOL)image;	// 0x34cf84b9
- (void)setUseFadeInAnimation:(BOOL)animation;	// 0x34cf7ded
- (void)setUseLoadFailureImage:(BOOL)image;	// 0x34cf7ddd
- (void)setUseLoadingSpinner:(BOOL)spinner;	// 0x34cf7dbd
// declared property getter: - (BOOL)upscalesImage;	// 0x34cf84a9
@end

