/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library

@class BRAsyncTaskContext, NSString, NSThread;

@interface BRAsyncTask : NSObject {
@private
	NSThread *_callingThread;	// 4 = 0x4
	id _target;	// 8 = 0x8
	SEL _selector;	// 12 = 0xc
	id _object;	// 16 = 0x10
	id _result;	// 20 = 0x14
	BRAsyncTaskContext *_context;	// 24 = 0x18
	int _state;	// 28 = 0x1c
	NSString *_identifier;	// 32 = 0x20
}
@property(readonly, retain) NSThread *callingThread;	// G=0x34dba191; converted property
@property(readonly, retain) BRAsyncTaskContext *context;	// G=0x34db9e19; converted property
@property(retain) NSString *identifier;	// G=0x34db9e61; S=0x34db9e29; converted property
@property(readonly, retain) id object;	// G=0x34db9e09; converted property
@property(readonly, retain) id result;	// G=0x34dba1b1; converted property
@property(readonly, assign) SEL selector;	// G=0x34db9de9; converted property
@property(assign) int state;	// G=0x34db9dd9; S=0x34dba1a1; converted property
@property(readonly, retain) id target;	// G=0x34db9df9; converted property
+ (void)_runTaskBlock:(id)block;	// 0x34db9c4d
+ (void)initialize;	// 0x34db9aa5
+ (id)taskWithBlock:(id)block;	// 0x34db9b89
+ (id)taskWithContext:(id)context withBlock:(id)block;	// 0x34db9bc9
+ (id)taskWithSelector:(SEL)selector onTarget:(id)target withObject:(id)object;	// 0x34db9b09
+ (id)taskWithSelector:(SEL)selector onTarget:(id)target withObject:(id)object withContext:(id)context;	// 0x34db9b35
+ (id)voidReturnValue;	// 0x34db9afd
- (id)_initWithSelector:(SEL)selector onTarget:(id)target withObject:(id)object withContext:(id)context;	// 0x34db9e71
// converted property getter: - (id)callingThread;	// 0x34dba191
- (void)cancel;	// 0x34db9da5
// converted property getter: - (id)context;	// 0x34db9e19
- (void)dealloc;	// 0x34db9c59
- (id)description;	// 0x34db9cd5
// converted property getter: - (id)identifier;	// 0x34db9e61
- (id)invoke;	// 0x34db9f1d
// converted property getter: - (id)object;	// 0x34db9e09
// converted property getter: - (id)result;	// 0x34dba1b1
- (void)run;	// 0x34db9d35
// converted property getter: - (SEL)selector;	// 0x34db9de9
// converted property setter: - (void)setIdentifier:(id)identifier;	// 0x34db9e29
// converted property setter: - (void)setState:(int)state;	// 0x34dba1a1
// converted property getter: - (int)state;	// 0x34db9dd9
// converted property getter: - (id)target;	// 0x34db9df9
@end

