/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library

@class BRAuthenticator;

@interface BRAuthenticationManager : NSObject {
@private
	id _authenticatorCreation;	// 4 = 0x4
	BRAuthenticator *_authenticator;	// 8 = 0x8
}
@property(readonly, retain) BRAuthenticator *authenticator;	// G=0x34d8f4dd; converted property
@property(retain) id preferredAccount;	// G=0x34d8f419; S=0x34d8f41d; converted property
+ (id)managerForAccountType:(id)accountType;	// 0x34d8f851
+ (void)registerManager:(id)manager forAccountType:(id)accountType;	// 0x34d8f74d
- (id)initWithAuthenticatorCreation:(id)authenticatorCreation;	// 0x34d8f34d
- (void)_authenticationControllerDidCancel:(id)_authenticationController;	// 0x34d8f70d
- (void)_checkAuthenticator:(id *)authenticator forAccount:(id)account scope:(unsigned)scope;	// 0x34d8f93d
- (id)_selectAccount;	// 0x34d8f669
- (id)_selectAuthenticatorWithAccount:(id)account scope:(unsigned)scope;	// 0x34d8f6ad
- (id)authenticationControllerForScope:(unsigned)scope;	// 0x34d8f515
// converted property getter: - (id)authenticator;	// 0x34d8f4dd
- (void)dealloc;	// 0x34d8f399
// converted property getter: - (id)preferredAccount;	// 0x34d8f419
// converted property setter: - (void)setPreferredAccount:(id)account;	// 0x34d8f41d
@end

