/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRAppliance.h"
#import <Foundation/Foundation.h> // Unknown library

@class NSArray;

@interface BRBaseAppliance : NSObject <BRAppliance> {
@private
	NSArray *_categories;	// 4 = 0x4
}
- (id)init;	// 0x34cc56e1
- (BOOL)_anySharesAvailable;	// 0x34cc639d
- (BOOL)_anyStoreCategoryExistsInMusicStoreCollection:(id)musicStoreCollection;	// 0x34cc6429
- (id)_applianceCategories;	// 0x34cc5e09
- (BOOL)_isCategoryWithIdentifier:(id)identifier memberOfMusicStoreCollection:(id)musicStoreCollection;	// 0x34cc6321
- (id)accessibilityLabel;	// 0x34cc5d55
- (id)alertControllerForNoContent;	// 0x34cc5c99
- (id)alertControllerForNoRemoteContent;	// 0x34cc5ced
- (id)applianceCategories;	// 0x34cc5a39
- (id)applianceCategoryDescriptions;	// 0x34cc5d89
- (id)applianceInfo;	// 0x34cc59ed
- (id)baseMediaType;	// 0x34cc58e1
- (id)categoryWithIdentifier:(id)identifier;	// 0x34cc5c11
- (id)controllerForIdentifier:(id)identifier args:(id)args;	// 0x34cc5b35
- (void)dealloc;	// 0x34cc5805
- (id)description;	// 0x34cc5871
- (BOOL)handleObjectSelection:(id)selection userInfo:(id)info;	// 0x34cc5b39
- (BOOL)handlePlay:(id)play userInfo:(id)info;	// 0x34cc5b3d
- (id)identifierForContentAlias:(id)contentAlias;	// 0x34cc5b31
- (id)musicStoreItemWithIdentifier:(id)identifier;	// 0x34cc5b41
- (int)noContentBRError;	// 0x34cc5ce5
- (int)noRemoteContentBRError;	// 0x34cc5d39
- (BOOL)previewError;	// 0x34cc5d41
- (id)previewErrorIconImage;	// 0x34cc5d4d
- (id)previewErrorSubtext;	// 0x34cc5d49
- (id)previewErrorText;	// 0x34cc5d45
- (void)reloadCategories;	// 0x34cc5dad
- (id)topShelfController;	// 0x34cc5d51
@end

