/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRSingleton.h"

@class NSTimer;

@interface BRBackgroundTaskManager : BRSingleton {
@private
	int _numberOfCurrentBackgroundProcesses;	// 4 = 0x4
	double _lastUserActivity;	// 8 = 0x8
	NSTimer *_backgroundProcessSuppressionTimer;	// 16 = 0x10
	NSTimer *_heavyBackgroundProcessSuppresionTimer;	// 20 = 0x14
}
+ (BOOL)backgroundTasksRunning;	// 0x34d93b11
+ (void)finishedBackgroundProcessing;	// 0x34d939c1
+ (void)finishedFileCopy:(id)copy;	// 0x34d93acd
+ (void)finishedMediaSyncing;	// 0x34d93a2d
+ (void)holdOffBackgroundTasks;	// 0x34d93955
+ (BOOL)mediaSyncInProgress;	// 0x34d93a75
+ (BOOL)okToDoBackgroundProcessing;	// 0x34d93979
+ (void)setSingleton:(id)singleton;	// 0x34d93b65
+ (id)singleton;	// 0x34d93b59
+ (void)startedFileCopy:(id)copy;	// 0x34d93a89
+ (void)startingBackgroundProcessing;	// 0x34d9399d
+ (void)startingMediaSyncing;	// 0x34d939e5
+ (double)timeSinceLastUserAction;	// 0x34d93b35
- (id)init;	// 0x34d93b71
- (BOOL)_backgroundTasksRunning;	// 0x34d93fe9
- (void)_finishedBackgroundProcessing;	// 0x34d93fd5
- (void)_holdOffBackgroundTasks;	// 0x34d93c65
- (void)_holdOffHeavyBackgroundTasks;	// 0x34d93d31
- (BOOL)_okToDoBackgroundProcessing;	// 0x34d93e99
- (void)_sendResumeBackgroundProcessingNotification;	// 0x34d93ef5
- (void)_sendResumeHeavyBackgroundProcessingNotification;	// 0x34d93f7d
- (void)_sendStopBackgroundProcessingNotification;	// 0x34d93eb1
- (void)_sendStopHeavyBackgroundProcessingNotification;	// 0x34d93f39
- (void)_setOKToDoBackgroundProcessing:(id)doBackgroundProcessing;	// 0x34d93df5
- (void)_setOKToDoHeavyBackgroundProcessing:(id)doHeavyBackgroundProcessing;	// 0x34d93e2d
- (void)_startingBackgroundProcessing;	// 0x34d93fc1
- (double)_timeSinceLastUserAction;	// 0x34d94001
- (void)_updateActivity:(id)activity;	// 0x34d9403d
- (void)dealloc;	// 0x34d93c11
@end

