/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class BRTextControl, NSArray, BRImage, BRImageControl;

@interface BRButtonControl : BRControl {
@private
	int _style;	// 44 = 0x2c
	BRImageControl *_imageControl;	// 48 = 0x30
	BRImageControl *_badgeControl;	// 52 = 0x34
	BRTextControl *_titleControl;	// 56 = 0x38
	BRTextControl *_subtitleControl;	// 60 = 0x3c
	BRImageControl *_overlayImageControl;	// 64 = 0x40
	BRImageControl *_backgroundImageControl;	// 68 = 0x44
	BRImageControl *_bottomBackgroundImageControl;	// 72 = 0x48
	BRImage *_image;	// 76 = 0x4c
	BRImage *_highlightedImage;	// 80 = 0x50
	NSArray *_subcontrolOrder;	// 84 = 0x54
	BOOL _subcontrolsNeedSorting;	// 88 = 0x58
	BOOL _buttonEnabled;	// 89 = 0x59
}
@property(retain) id badgeImage;	// G=0x34d5b705; S=0x34d5b62d; converted property
@property(retain) BRImage *highlightedImage;	// G=0x34d5b851; S=0x34d5b809; converted property
@property(retain) BRImage *image;	// G=0x34d5b60d; S=0x34d5b5c5; converted property
@property(retain) id subtitle;	// G=0x34d5b5a5; S=0x34d5b4a9; converted property
@property(retain) id title;	// G=0x34d5b489; S=0x34d5b38d; converted property
+ (id)actionButtonWithImage:(id)image subtitle:(id)subtitle badge:(id)badge;	// 0x34d5ad81
+ (id)actionButtonWithTitle:(id)title subtitle:(id)subtitle badge:(id)badge;	// 0x34d5ade5
+ (id)dashedActionButtonWithTitle:(id)title subtitle:(id)subtitle selectable:(BOOL)selectable;	// 0x34d5ae89
+ (id)dialogButtonWithTitle:(id)title;	// 0x34d5ae49
+ (id)glossyButtonWithTitle:(id)title;	// 0x34d5aeed
- (id)init;	// 0x34d5ac15
- (id)_addFadeAnimationToLayer:(id)layer forKey:(id)key;	// 0x34d5964d
- (void)_addOpacityFadeAnimationIfNeededToControl:(id)control;	// 0x34d59721
- (void)_addSortedControl:(id)control;	// 0x34d598bd
- (void)_focusWasChanged;	// 0x34d59cd5
- (void)_layoutActionSublayers;	// 0x34d59fa5
- (void)_layoutDashedSublayers;	// 0x34d5a705
- (void)_layoutDialogSublayers;	// 0x34d59db5
- (void)_layoutGlossySublayers;	// 0x34d5aa19
- (id)_nonFocusedOpacityForControlNamed:(id)controlNamed;	// 0x34d59379
- (void)_setBackgroundHighlightImage:(id)image;	// 0x34d599a1
- (void)_setBottomBackgroundHighlightImage:(id)image;	// 0x34d59a65
- (void)_setControlOrderArray:(id)array;	// 0x34d5abbd
- (void)_setNonAttributedSubtitle:(id)subtitle;	// 0x34d595bd
- (void)_setNonAttributedTitle:(id)title;	// 0x34d594f9
- (void)_updateAllFocusOpacities;	// 0x34d59851
- (void)_updateBackgroundDialogImages;	// 0x34d59b29
- (void)_updateFocusOpacityOfControl:(id)control;	// 0x34d597ad
- (void)_updateImageLayer;	// 0x34d59ba9
- (id)accessibilityLabel;	// 0x34d5b9f9
- (id)accessibilityTraits;	// 0x34d5ba81
// converted property getter: - (id)badgeImage;	// 0x34d5b705
- (void)controlWasActivated;	// 0x34d5b8b1
- (void)controlWasFocused;	// 0x34d59d3d
- (void)controlWasUnfocused;	// 0x34d59d79
- (void)dealloc;	// 0x34d5ac71
// converted property getter: - (id)highlightedImage;	// 0x34d5b851
// converted property getter: - (id)image;	// 0x34d5b60d
- (BOOL)isAccessibilityElement;	// 0x34d5b9f5
- (void)layoutSubcontrols;	// 0x34d5b8ed
- (id)overayImage;	// 0x34d5b7e9
// converted property setter: - (void)setBadgeImage:(id)image;	// 0x34d5b62d
- (void)setButtonEnabled:(BOOL)enabled;	// 0x34d5b861
- (void)setButtonStyle:(int)style;	// 0x34d5af3d
// converted property setter: - (void)setHighlightedImage:(id)image;	// 0x34d5b809
// converted property setter: - (void)setImage:(id)image;	// 0x34d5b5c5
- (void)setNonAttributedSubtitle:(id)subtitle;	// 0x34d5bac1
- (void)setNonAttributedTitle:(id)title;	// 0x34d5baad
- (void)setOverlayImage:(id)image;	// 0x34d5b725
// converted property setter: - (void)setSubtitle:(id)subtitle;	// 0x34d5b4a9
// converted property setter: - (void)setTitle:(id)title;	// 0x34d5b38d
// converted property getter: - (id)subtitle;	// 0x34d5b5a5
// converted property getter: - (id)title;	// 0x34d5b489
@end

