/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library

@class NSString, NSMutableDictionary;

@interface BRCappedFileCache : NSObject {
@private
	unsigned long long _maxSize;	// 4 = 0x4
	unsigned long long _currentSize;	// 12 = 0xc
	unsigned long long _purgeThreshold;	// 20 = 0x14
	unsigned long _purgeCount;	// 28 = 0x1c
	NSString *_cachePath;	// 32 = 0x20
	BOOL _purgingCache;	// 36 = 0x24
	NSMutableDictionary *_files;	// 40 = 0x28
}
@property(readonly, assign) unsigned long long currentSize;	// G=0x34dbd791; converted property
@property(readonly, assign) unsigned long long maxSize;	// G=0x34dbd7a9; converted property
@property(assign) unsigned long purgeCount;	// G=0x34dbd82d; S=0x34dbd83d; converted property
@property(assign) unsigned long long purgeThreshold;	// G=0x34dbd7c1; S=0x34dbd7d9; converted property
- (id)initForPath:(id)path withMaxSize:(unsigned long long)maxSize;	// 0x34dbd57d
- (void)_clearCacheFolder;	// 0x34dbe181
- (id)_generateCacheFilePathForKey:(id)key extension:(id)extension;	// 0x34dbdfcd
- (void)_incrementCacheSize:(unsigned long long)size;	// 0x34dbe08d
- (void)_maintainCacheSize:(id)size;	// 0x34dbe1f5
- (void)_terminateNotification:(id)notification;	// 0x34dbe4e5
- (id)addFileForKey:(id)key size:(unsigned long long)size extension:(id)extension;	// 0x34dbda61
// converted property getter: - (unsigned long long)currentSize;	// 0x34dbd791
- (void)dealloc;	// 0x34dbd701
- (id)filePathForKey:(id)key;	// 0x34dbd84d
// converted property getter: - (unsigned long long)maxSize;	// 0x34dbd7a9
// converted property getter: - (unsigned long)purgeCount;	// 0x34dbd82d
// converted property getter: - (unsigned long long)purgeThreshold;	// 0x34dbd7c1
- (void)removedFileWithKey:(id)key;	// 0x34dbddb5
// converted property setter: - (void)setPurgeCount:(unsigned long)count;	// 0x34dbd83d
// converted property setter: - (void)setPurgeThreshold:(unsigned long long)threshold;	// 0x34dbd7d9
@end

