/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library
#import "AppleTV-Structs.h"


@interface BRChapterUtilities : NSObject {
}
+ (unsigned)chapterGroupCountForMediaAsset:(id)mediaAsset;	// 0x34dad585
+ (unsigned)chapterGroupCountForMediaItem:(ATVMediaItemRef)mediaItem;	// 0x34dad64d
+ (id)mediaAsset:(id)asset chapterGroupAtIndex:(unsigned)index;	// 0x34dad609
+ (BOOL)mediaAsset:(id)asset hasChapterGroupAtIndex:(unsigned)index;	// 0x34dad5c5
+ (id)mediaItem:(ATVMediaItemRef)item chapterGroupAtIndex:(unsigned)index;	// 0x34dad655
+ (BOOL)mediaItem:(ATVMediaItemRef)item hasChapterGroupAtIndex:(unsigned)index;	// 0x34dad651
@end

