/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library

@class NSString, NSArray, NSDate;

@interface BRChapterGroup : NSObject {
@private
	NSString *_groupName;	// 4 = 0x4
	NSArray *_chapters;	// 8 = 0x8
	NSString *_refreshURL;	// 12 = 0xc
	unsigned _refreshIntervalInSeconds;	// 16 = 0x10
	NSDate *_startDate;	// 20 = 0x14
	BOOL _showChapterMarkers;	// 24 = 0x18
	BOOL _showDescriptionOnChapterSkip;	// 25 = 0x19
}
@property(readonly, assign) NSArray *chapters;	// G=0x34dad2b5; @synthesize=_chapters
@property(readonly, assign) NSString *groupName;	// G=0x34dad2a5; @synthesize=_groupName
@property(readonly, assign) unsigned refreshIntervalInSeconds;	// G=0x34dad305; @synthesize=_refreshIntervalInSeconds
@property(retain) NSString *refreshURL;	// G=0x34dad2c5; S=0x34dad2dd; @synthesize=_refreshURL
@property(readonly, assign) BOOL showChapterMarkers;	// G=0x34dad325; @synthesize=_showChapterMarkers
@property(readonly, assign) BOOL showDescriptionOnChapterSkip;	// G=0x34dad335; @synthesize=_showDescriptionOnChapterSkip
@property(readonly, assign) NSDate *startDate;	// G=0x34dad315; @synthesize=_startDate
- (id)initWithFeedDictionary:(id)feedDictionary;	// 0x34dad1cd
- (id)initWithGroupName:(id)groupName feedDictionary:(id)dictionary;	// 0x34dad05d
- (id)_chaptersFromFeedDictionary:(id)feedDictionary;	// 0x34dad345
- (unsigned)chapterCount;	// 0x34dad281
// declared property getter: - (id)chapters;	// 0x34dad2b5
- (void)dealloc;	// 0x34dad205
// declared property getter: - (id)groupName;	// 0x34dad2a5
// declared property getter: - (unsigned)refreshIntervalInSeconds;	// 0x34dad305
// declared property getter: - (id)refreshURL;	// 0x34dad2c5
// declared property setter: - (void)setRefreshURL:(id)url;	// 0x34dad2dd
// declared property getter: - (BOOL)showChapterMarkers;	// 0x34dad325
// declared property getter: - (BOOL)showDescriptionOnChapterSkip;	// 0x34dad335
// declared property getter: - (id)startDate;	// 0x34dad315
@end

