/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library

@class NSString, NSDate;

@interface BRChapter : NSObject {
@private
	NSString *_name;	// 4 = 0x4
	NSString *_description;	// 8 = 0x8
	NSString *_identifier;	// 12 = 0xc
	double _startTime;	// 16 = 0x10
	double _endTime;	// 24 = 0x18
	NSDate *_startDate;	// 32 = 0x20
	NSDate *_endDate;	// 36 = 0x24
}
@property(retain, nonatomic) NSString *description;	// G=0x34dacf35; S=0x34dacf45; @synthesize=_description
@property(retain, nonatomic) NSDate *endDate;	// G=0x34dad029; S=0x34dad039; @synthesize=_endDate
@property(assign, nonatomic) double endTime;	// G=0x34dacfc9; S=0x34dacfe1; @synthesize=_endTime
@property(retain, nonatomic) NSString *identifier;	// G=0x34dacf69; S=0x34dacf79; @synthesize=_identifier
@property(retain, nonatomic) NSString *name;	// G=0x34dacf01; S=0x34dacf11; @synthesize=_name
@property(retain, nonatomic) NSDate *startDate;	// G=0x34dacff5; S=0x34dad005; @synthesize=_startDate
@property(assign, nonatomic) double startTime;	// G=0x34dacf9d; S=0x34dacfb5; @synthesize=_startTime
+ (id)chapterWithAssetID:(id)assetID startDate:(id)date endDate:(id)date3;	// 0x34dacb59
+ (id)chapterWithAssetID:(id)assetID startTime:(double)time endTime:(double)time3;	// 0x34dacb11
- (id)initWithAssetID:(id)assetID startDate:(id)date endDate:(id)date3;	// 0x34dacc5d
- (id)initWithAssetID:(id)assetID startTime:(double)time endTime:(double)time3;	// 0x34dacb99
- (BOOL)containsDate:(id)date;	// 0x34dace69
- (BOOL)containsTime:(double)time;	// 0x34dacd9d
- (void)dealloc;	// 0x34dacd15
// declared property getter: - (id)description;	// 0x34dacf35
// declared property getter: - (id)endDate;	// 0x34dad029
// declared property getter: - (double)endTime;	// 0x34dacfc9
// declared property getter: - (id)identifier;	// 0x34dacf69
- (id)imageProxy;	// 0x34dacefd
- (void)invalidate;	// 0x34dacd99
// declared property getter: - (id)name;	// 0x34dacf01
// declared property setter: - (void)setDescription:(id)description;	// 0x34dacf45
// declared property setter: - (void)setEndDate:(id)date;	// 0x34dad039
// declared property setter: - (void)setEndTime:(double)time;	// 0x34dacfe1
// declared property setter: - (void)setIdentifier:(id)identifier;	// 0x34dacf79
// declared property setter: - (void)setName:(id)name;	// 0x34dacf11
// declared property setter: - (void)setStartDate:(id)date;	// 0x34dad005
// declared property setter: - (void)setStartTime:(double)time;	// 0x34dacfb5
// declared property getter: - (id)startDate;	// 0x34dacff5
// declared property getter: - (double)startTime;	// 0x34dacf9d
@end

