/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRController.h"


__attribute__((visibility("hidden")))
@interface BRContentController : BRController {
}
- (id)accessibilityLabel;	// 0x34cc7f21
- (BOOL)isAccessibilityElement;	// 0x34cc7ea5
- (void)layoutSubcontrols;	// 0x34cc7df9
@end

