/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRBaseMenuItemLayerPopulator.h"


@interface BRCollectionMenuItemPopulator : BRBaseMenuItemLayerPopulator {
}
+ (BOOL)canHandleObject:(id)object;	// 0x34d80bd9
- (id)_folderItemTypes;	// 0x34d814f9
- (id)allowedTypesPredicate;	// 0x34d81129
- (id)menuItem;	// 0x34d80c09
- (float)menuItemHeightForObject:(id)object delegate:(id)delegate;	// 0x34d80f7d
- (unsigned)numItemsInCollection:(id)collection hasOnlySongs:(BOOL *)songs;	// 0x34d811cd
- (id)numItemsString;	// 0x34d8106d
@end

