/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRTransitionControl.h"


__attribute__((visibility("hidden")))
@interface BRCrossfadeTransitionControl : BRTransitionControl {
}
- (void)_transitionInCompleted:(id)completed;	// 0x34d502a9
- (void)_transitionOutCompleted:(id)completed;	// 0x34d502fd
- (void)_updateContentForTransitionState;	// 0x34d5036d
- (void)setTransitionedIn:(BOOL)anIn;	// 0x34d50251
@end

