/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class NSTimer, NSDictionary;
@protocol BRProvider, BRCyclerDelegate, BRCyclerDataSource;

@interface BRCyclerControl : BRControl {
@private
	id<BRProvider> _provider;	// 44 = 0x2c
	double _interval;	// 48 = 0x30
	double _startInterval;	// 56 = 0x38
	long _index;	// 64 = 0x40
	long _startIndex;	// 68 = 0x44
	BOOL _returnsToStart;	// 72 = 0x48
	NSTimer *_crossFadeTimer;	// 76 = 0x4c
	BRControl *_control;	// 80 = 0x50
	NSDictionary *_subcontrolMetadata;	// 84 = 0x54
	BOOL _initialDisplayOccurred;	// 88 = 0x58
	id<BRCyclerDataSource> _dataSource;	// 92 = 0x5c
	id<BRCyclerDelegate> _delegate;	// 96 = 0x60
	BOOL _startsOnActivate;	// 100 = 0x64
}
@property(assign, nonatomic) id<BRCyclerDataSource> dataSource;	// G=0x34d00a35; S=0x34d00495; @synthesize=_dataSource
@property(assign, nonatomic) id<BRCyclerDelegate> delegate;	// G=0x34d00a45; S=0x34d00a55; @synthesize=_delegate
@property(assign) double interval;	// G=0x34d007d9; S=0x34d00761; converted property
@property(assign) BOOL returnsToStart;	// G=0x34d00751; S=0x34d00741; converted property
@property(assign) long startIndex;	// G=0x34d00731; S=0x34d006d1; converted property
@property(assign) double startInterval;	// G=0x34d00805; S=0x34d007f1; converted property
@property(assign, nonatomic) BOOL startsOnActivate;	// G=0x34d00a65; S=0x34d00a75; @synthesize=_startsOnActivate
@property(readonly, retain) NSDictionary *subcontrolMetadata;	// G=0x34d00855; converted property
+ (id)cyclerWithProvider:(id)provider;	// 0x34d002cd
- (id)init;	// 0x34d0030d
- (id)initWithProvider:(id)provider;	// 0x34d0034d
- (void)_commonInit;	// 0x34d00f59
- (void)_crossFade:(id)fade;	// 0x34d00b49
- (void)_providerUpdated:(id)updated;	// 0x34d00a85
- (void)_returnToStart;	// 0x34d00f11
- (void)_startCrossFadeTimer;	// 0x34d00e1d
- (void)_stopCrossFadeTimer;	// 0x34d00ed9
- (id)accessibilityLabel;	// 0x34d009a9
- (void)controlWasActivated;	// 0x34d004f5
- (void)controlWasDeactivated;	// 0x34d0056d
- (void)controlWasFocused;	// 0x34d005b9
- (void)controlWasUnfocused;	// 0x34d0063d
- (void)cycle;	// 0x34d00719
// declared property getter: - (id)dataSource;	// 0x34d00a35
- (void)dealloc;	// 0x34d00405
// declared property getter: - (id)delegate;	// 0x34d00a45
// converted property getter: - (double)interval;	// 0x34d007d9
- (void)layoutSubcontrols;	// 0x34d00959
- (id)preferredActionForKey:(id)key;	// 0x34d00865
// converted property getter: - (BOOL)returnsToStart;	// 0x34d00751
// declared property setter: - (void)setDataSource:(id)source;	// 0x34d00495
// declared property setter: - (void)setDelegate:(id)delegate;	// 0x34d00a55
// converted property setter: - (void)setInterval:(double)interval;	// 0x34d00761
// converted property setter: - (void)setReturnsToStart:(BOOL)start;	// 0x34d00741
// converted property setter: - (void)setStartIndex:(long)index;	// 0x34d006d1
// converted property setter: - (void)setStartInterval:(double)interval;	// 0x34d007f1
// declared property setter: - (void)setStartsOnActivate:(BOOL)activate;	// 0x34d00a75
- (void)setSubcontrolMetaData:(id)data;	// 0x34d0081d
- (void)start;	// 0x34d00705
// converted property getter: - (long)startIndex;	// 0x34d00731
// converted property getter: - (double)startInterval;	// 0x34d00805
// declared property getter: - (BOOL)startsOnActivate;	// 0x34d00a65
// converted property getter: - (id)subcontrolMetadata;	// 0x34d00855
@end

