/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRViewController.h"

@class BRMediaMenuView, NSTimer, NSArray;

@interface BRDataQueryController : BRViewController {
@private
	id _serverID;	// 64 = 0x40
	unsigned long _dataClientType;	// 68 = 0x44
	ATVDataClientRef _dataClient;	// 72 = 0x48
	BRMediaMenuView *_mediaMenuView;	// 76 = 0x4c
	NSArray *_data;	// 80 = 0x50
	ATVMediaQueryRef _preDataQuery;	// 84 = 0x54
	ATVMediaQueryRef _dataQuery;	// 88 = 0x58
	ATVMediaQueryRef _previewQuery;	// 92 = 0x5c
	NSTimer *_spinnerTimer;	// 96 = 0x60
	BOOL _showingSpinner;	// 100 = 0x64
	void *_dataItemToSelect;	// 104 = 0x68
	ATVMediaQueryRef _playQuery;	// 108 = 0x6c
	BOOL _handlingDataClientUpdate;	// 112 = 0x70
	BOOL _refreshNeeded;	// 113 = 0x71
	BOOL _reloadListViewNeeded;	// 114 = 0x72
	NSTimer *_serverFoundWaitTimer;	// 116 = 0x74
	BOOL attemptConnectionOnServerRemove;	// 120 = 0x78
}
@property(assign, nonatomic) BOOL attemptConnectionOnServerRemove;	// G=0x34ccb761; S=0x34ccb771; @synthesize
@property(readonly, retain) NSArray *data;	// G=0x34ccb31d; converted property
@property(readonly, assign) ATVDataClientRef dataClient;	// G=0x34ccb40d; converted property
@property(readonly, assign) unsigned long dataClientType;	// G=0x34ccb3fd; converted property
@property(assign) void *dataItemToSelect;	// G=0x34ccb491; S=0x34ccb461; converted property
@property(readonly, retain) BRMediaMenuView *mediaMenuView;	// G=0x34ccb30d; converted property
@property(readonly, retain) id serverID;	// G=0x34ccb3ed; converted property
- (id)init;	// 0x34ccaae9
- (id)initWithServerID:(id)serverID dataClientType:(unsigned long)type;	// 0x34ccab0d
- (void)_dataClientConnectionHandler:(id)handler;	// 0x34ccc6c5
- (void)_dataClientConnectionHandlerWithObject:(id)object;	// 0x34ccc56d
- (void)_dataClientDataUpdated:(id)updated;	// 0x34ccca2d
- (void)_dataClientStatusChanged:(id)changed;	// 0x34ccc9d9
- (void)_dataQueryComplete;	// 0x34ccc0ed
- (void)_dataServerConnectionHandler:(id)handler;	// 0x34ccc8c9
- (void)_dataServerFailedToConnect:(id)connect;	// 0x34ccc931
- (void)_dataServersChangedHandler:(id)handler;	// 0x34cccb95
- (void)_displayErrorForQuery:(ATVMediaQueryRef)query;	// 0x34ccbd85
- (void)_displayFailedToConnect;	// 0x34ccbef5
- (void)_executeDataQuery;	// 0x34ccc271
- (void)_executePreDataQuery;	// 0x34ccc191
- (void)_handleDataQueryCompletion;	// 0x34ccb84d
- (BOOL)_isDataServerEqual:(ATVDataServerRef)equal;	// 0x34cccf0d
- (void)_mediaItemPropertySetNotification:(id)notification;	// 0x34cccb0d
- (void)_playQueryComplete;	// 0x34ccc171
- (void)_preDataQueryComplete;	// 0x34ccbfd1
- (void)_previewQueryComplete;	// 0x34ccc129
- (void)_serverFoundWaitHandler:(id)handler;	// 0x34cccff1
- (void)_setDataClient:(ATVDataClientRef)client;	// 0x34ccbc75
- (void)_setDataQuery:(ATVMediaQueryRef)query;	// 0x34ccc441
- (void)_setPlayQuery:(ATVMediaQueryRef)query;	// 0x34ccc4b1
- (void)_setPreDataQuery:(ATVMediaQueryRef)query;	// 0x34ccc409
- (void)_setPreviewQuery:(ATVMediaQueryRef)query;	// 0x34ccc479
- (void)_showSpinner;	// 0x34ccbb3d
- (void)_showSpinner:(BOOL)spinner delay:(BOOL)delay;	// 0x34ccb781
- (void)_updateDisabledStateForMenusInList:(id)list;	// 0x34ccb9d9
- (id)accessibilityScreenContent;	// 0x34ccb731
// declared property getter: - (BOOL)attemptConnectionOnServerRemove;	// 0x34ccb761
- (id)controllerIdentifier;	// 0x34ccc50d
- (ATVMediaQueryRef)createDataQuery;	// 0x34ccc4f1
- (ATVMediaQueryRef)createPlayQueryForIndexPath:(id)indexPath;	// 0x34ccc535
- (ATVMediaQueryRef)createPreDataQuery;	// 0x34ccc4e9
- (ATVMediaQueryRef)createPreviewQueryForIndexPath:(id)indexPath;	// 0x34ccc4fd
// converted property getter: - (id)data;	// 0x34ccb31d
// converted property getter: - (ATVDataClientRef)dataClient;	// 0x34ccb40d
- (id)dataClientName;	// 0x34ccb41d
// converted property getter: - (unsigned long)dataClientType;	// 0x34ccb3fd
- (BOOL)dataClientUpdated:(ATVDataClientRef)updated;	// 0x34ccc565
- (void *)dataItemAtIndexPath:(id)indexPath;	// 0x34ccc509
// converted property getter: - (void *)dataItemToSelect;	// 0x34ccb491
- (BOOL)dataQueryComplete:(ATVMediaQueryRef)complete;	// 0x34ccc4f5
- (ATVDataServerRef)dataServer;	// 0x34ccb441
- (BOOL)dataServerConnectionChanged:(ATVDataServerRef)changed;	// 0x34ccc569
- (void)dealloc;	// 0x34ccac0d
- (id)defaultIndexPathToSelect;	// 0x34ccc4f9
- (id)errorControlForQuery:(ATVMediaQueryRef)query;	// 0x34ccc561
- (id)errorForNoContent;	// 0x34ccc53d
- (id)identifier;	// 0x34ccad85
- (id)indexPathForDataItem:(void *)dataItem;	// 0x34ccc505
- (void)list:(id)list didFocusItemAtIndexPath:(id)indexPath;	// 0x34ccb4a9
- (void)list:(id)list didPlayItemAtIndexPath:(id)indexPath;	// 0x34ccb591
- (id)list:(id)list menuItemForRowAtIndexPath:(id)indexPath;	// 0x34ccb4a5
- (long)list:(id)list numberOfRowsInSection:(long)section;	// 0x34ccb4a1
// converted property getter: - (id)mediaMenuView;	// 0x34ccb30d
- (void)playQueryComplete:(ATVMediaQueryRef)complete;	// 0x34ccc539
- (BOOL)preDataQueryComplete:(id)complete;	// 0x34ccc4ed
- (id)previewForItems:(id)items;	// 0x34ccb66d
- (BOOL)previewQueryComplete:(ATVMediaQueryRef)complete;	// 0x34ccc501
- (void)restartDataQueryProcess;	// 0x34ccb641
// converted property getter: - (id)serverID;	// 0x34ccb3ed
// declared property setter: - (void)setAttemptConnectionOnServerRemove:(BOOL)remove;	// 0x34ccb771
// converted property setter: - (void)setDataItemToSelect:(void *)select;	// 0x34ccb461
- (void)setServerID:(id)anId dataClientType:(unsigned long)type;	// 0x34ccb32d
- (void)wasExhumed;	// 0x34ccb25d
- (void)wasPopped;	// 0x34ccb159
- (void)wasPushed;	// 0x34ccada5
@end

