/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class NSAttributedString;

@interface BRDividerControl : BRControl {
@private
	NSAttributedString *_label;	// 44 = 0x2c
	float _brightness;	// 48 = 0x30
	float _alignmentFactor;	// 52 = 0x34
	float _lineThickness;	// 56 = 0x38
	float _startOffset;	// 60 = 0x3c
	float _endOffset;	// 64 = 0x40
	BOOL _drawsLine;	// 68 = 0x44
	float _startOffsetText;	// 72 = 0x48
	int _dividerOrientation;	// 76 = 0x4c
	int _dividerHeightStyle;	// 80 = 0x50
}
@property(assign) float brightness;	// G=0x34d063d1; S=0x34d063c1; converted property
@property(assign) int dividerHeightStyle;	// G=0x34d064b5; S=0x34d06495; converted property
@property(assign) int dividerOrientation;	// G=0x34d06485; S=0x34d0644d; converted property
@property(assign) BOOL drawsLine;	// G=0x34d063f1; S=0x34d063e1; converted property
@property(retain) NSAttributedString *label;	// G=0x34d05db9; S=0x34d05cf1; converted property
- (id)init;	// 0x34d05be1
- (id)accessibilityLabel;	// 0x34d064c5
// converted property getter: - (float)brightness;	// 0x34d063d1
- (void)dealloc;	// 0x34d05cad
// converted property getter: - (int)dividerHeightStyle;	// 0x34d064b5
// converted property getter: - (int)dividerOrientation;	// 0x34d06485
- (void)drawInContext:(CGContextRef)context;	// 0x34d05fd5
// converted property getter: - (BOOL)drawsLine;	// 0x34d063f1
- (BOOL)isAccessibilityElement;	// 0x34d064e5
// converted property getter: - (id)label;	// 0x34d05db9
- (float)recommendedHeight;	// 0x34d05f39
- (float)recommendedWidth;	// 0x34d05fc5
- (void)setAlignmentFactor:(float)factor;	// 0x34d05dd9
// converted property setter: - (void)setBrightness:(float)brightness;	// 0x34d063c1
// converted property setter: - (void)setDividerHeightStyle:(int)style;	// 0x34d06495
// converted property setter: - (void)setDividerOrientation:(int)orientation;	// 0x34d0644d
// converted property setter: - (void)setDrawsLine:(BOOL)line;	// 0x34d063e1
- (void)setEndOffset:(float)offset;	// 0x34d05e71
// converted property setter: - (void)setLabel:(id)label;	// 0x34d05cf1
- (void)setLabel:(id)label withAttributes:(id)attributes;	// 0x34d05d35
- (void)setLineThickness:(float)thickness;	// 0x34d05ebd
- (void)setStartOffset:(float)offset;	// 0x34d05e25
- (void)setStartOffsetText:(float)text;	// 0x34d06401
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x34d05ef1
@end

