/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library

@class BRWindow, NSString, BRControl;

@interface BRDialog : NSObject {
@private
	BRWindow *_window;	// 4 = 0x4
	BRControl *_control;	// 8 = 0x8
	NSString *_identifier;	// 12 = 0xc
}
@property(readonly, retain) BRControl *control;	// G=0x34d942ed; converted property
@property(readonly, retain) NSString *identifier;	// G=0x34d9431d; converted property
+ (void)dismissDialogWithIdentifier:(id)identifier;	// 0x34d94ab9
+ (void)initialize;	// 0x34d940a5
+ (BOOL)isDialogCurrentlyPosted;	// 0x34d94695
+ (BOOL)isDialogPostedWithIdentifier:(id)identifier;	// 0x34d94639
+ (void)postDialogWithControl:(id)control identifier:(id)identifier;	// 0x34d946bd
+ (void)postDialogWithControl:(id)control identifier:(id)identifier style:(int)style opaque:(BOOL)opaque;	// 0x34d944bd
+ (void)postModalDialog:(id)dialog;	// 0x34d9471d
+ (void)postModalDialogWithControl:(id)control identifier:(id)identifier;	// 0x34d946dd
+ (void)postModalDialogWithControl:(id)control identifier:(id)identifier style:(int)style opaque:(BOOL)opaque;	// 0x34d94951
+ (void)postModalDialogWithController:(id)controller identifier:(id)identifier;	// 0x34d946fd
+ (void)postModalDialogWithController:(id)controller identifier:(id)identifier style:(int)style opaque:(BOOL)opaque;	// 0x34d949b5
- (id)initWithControl:(id)control identifier:(id)identifier style:(int)style opaque:(BOOL)opaque;	// 0x34d940fd
- (void)_dialogStackBankrupt:(id)bankrupt;	// 0x34d94d6d
- (void)_transitionCompleted:(id)completed;	// 0x34d94d9d
// converted property getter: - (id)control;	// 0x34d942ed
- (void)dealloc;	// 0x34d94249
// converted property getter: - (id)identifier;	// 0x34d9431d
- (void)transitionIn;	// 0x34d9434d
- (void)transitionOut;	// 0x34d943c9
@end

