/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRControl.h"
#import "AppleTV-Structs.h"


@interface BRDropShadowControl : BRControl {
@private
	BRControl *_content;	// 44 = 0x2c
	int _shadowStyle;	// 48 = 0x30
	float _sizeFactor;	// 52 = 0x34
}
@property(retain) BRControl *content;	// G=0x34d07cd1; S=0x34d07c59; converted property
@property(assign) float shadowSizeFactor;	// G=0x34d07c49; S=0x34d07c11; converted property
@property(assign) int shadowStyle;	// G=0x34d07c01; S=0x34d07bd9; converted property
- (id)init;	// 0x34d07b3d
- (void)_updateImages;	// 0x34d07f65
// converted property getter: - (id)content;	// 0x34d07cd1
- (void)dealloc;	// 0x34d07b95
- (void)layoutSubcontrols;	// 0x34d07ce1
// converted property setter: - (void)setContent:(id)content;	// 0x34d07c59
// converted property setter: - (void)setShadowSizeFactor:(float)factor;	// 0x34d07c11
// converted property setter: - (void)setShadowStyle:(int)style;	// 0x34d07bd9
// converted property getter: - (float)shadowSizeFactor;	// 0x34d07c49
// converted property getter: - (int)shadowStyle;	// 0x34d07c01
@end

