/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library

@class NSDictionary;

@interface BREvent : NSObject {
@private
	NSDictionary *_eventDictionary;	// 4 = 0x4
	int _action;	// 8 = 0x8
	double _timeStamp;	// 12 = 0xc
	int _value;	// 20 = 0x14
	unsigned _originator;	// 24 = 0x18
	BOOL _allowRetrigger;	// 28 = 0x1c
	BOOL _retrigger;	// 29 = 0x1d
}
@property(readonly, assign) BOOL allowRetrigger;	// G=0x34ce88a9; converted property
@property(readonly, retain) NSDictionary *eventDictionary;	// G=0x34ce8899; converted property
@property(readonly, assign) unsigned originator;	// G=0x34ce8889; converted property
@property(readonly, assign) double timeStamp;	// G=0x34ce8871; converted property
@property(readonly, assign) int value;	// G=0x34ce8841; converted property
+ (id)eventWithAction:(int)action value:(int)value;	// 0x34ce8209
+ (id)eventWithAction:(int)action value:(int)value atTime:(double)time;	// 0x34ce8241
+ (id)eventWithAction:(int)action value:(int)value atTime:(double)time originator:(unsigned)originator;	// 0x34ce8285
+ (id)eventWithAction:(int)action value:(int)value atTime:(double)time originator:(unsigned)originator eventDictionary:(id)dictionary allowRetrigger:(BOOL)retrigger;	// 0x34ce82cd
+ (id)eventWithEvent:(id)event originator:(unsigned)originator;	// 0x34ce83b1
+ (id)eventWithEvent:(id)event originator:(unsigned)originator eventDictionary:(id)dictionary allowRetrigger:(BOOL)retrigger;	// 0x34ce8321
- (id)initWithAction:(int)action value:(int)value;	// 0x34ce8465
- (id)initWithAction:(int)action value:(int)value atTime:(double)time;	// 0x34ce8495
- (id)initWithAction:(int)action value:(int)value atTime:(double)time originator:(unsigned)originator;	// 0x34ce84bd
- (id)initWithAction:(int)action value:(int)value atTime:(double)time originator:(unsigned)originator eventDictionary:(id)dictionary allowRetrigger:(BOOL)retrigger;	// 0x34ce84f1
// converted property getter: - (BOOL)allowRetrigger;	// 0x34ce88a9
- (void)dealloc;	// 0x34ce858d
- (id)description;	// 0x34ce85d1
// converted property getter: - (id)eventDictionary;	// 0x34ce8899
- (BOOL)isEqual:(id)equal;	// 0x34ce87b1
- (void)makeRetriggerEvent;	// 0x34ce8861
// converted property getter: - (unsigned)originator;	// 0x34ce8889
- (int)remoteAction;	// 0x34ce8831
- (BOOL)retriggerEvent;	// 0x34ce8851
// converted property getter: - (double)timeStamp;	// 0x34ce8871
// converted property getter: - (int)value;	// 0x34ce8841
@end

