/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"


__attribute__((visibility("hidden")))
@interface BRFadeMaskLayer : BRControl {
@private
	float _topFadeHeight;	// 44 = 0x2c
	float _bottomFadeHeight;	// 48 = 0x30
	float _leftFadeWidth;	// 52 = 0x34
	float _rightFadeWidth;	// 56 = 0x38
	CGFunctionRef _shadingFunction;	// 60 = 0x3c
}
@property(assign) float bottomFadeHeight;	// G=0x34d7b5f9; S=0x34d7b5c1; converted property
@property(assign) float leftFadeWidth;	// G=0x34d7b641; S=0x34d7b609; converted property
@property(assign) float rightFadeWidth;	// G=0x34d7b689; S=0x34d7b651; converted property
@property(assign) float topFadeHeight;	// G=0x34d7b5b1; S=0x34d7b579; converted property
- (id)init;	// 0x34d7b4b5
// converted property getter: - (float)bottomFadeHeight;	// 0x34d7b5f9
- (void)dealloc;	// 0x34d7b539
- (void)drawInContext:(CGContextRef)context;	// 0x34d7b699
// converted property getter: - (float)leftFadeWidth;	// 0x34d7b641
// converted property getter: - (float)rightFadeWidth;	// 0x34d7b689
// converted property setter: - (void)setBottomFadeHeight:(float)height;	// 0x34d7b5c1
- (void)setEnableMaskAnimation:(BOOL)animation;	// 0x34d7b8b9
// converted property setter: - (void)setLeftFadeWidth:(float)width;	// 0x34d7b609
// converted property setter: - (void)setRightFadeWidth:(float)width;	// 0x34d7b651
// converted property setter: - (void)setTopFadeHeight:(float)height;	// 0x34d7b579
// converted property getter: - (float)topFadeHeight;	// 0x34d7b5b1
@end

