/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRImageControl.h"

@class BRImage;

@interface BRFocusableImageControl : BRImageControl {
@private
	BRImage *_focusedImage;	// 60 = 0x3c
	BRImage *_unfocusedImage;	// 64 = 0x40
	BRImage *_disabledImage;	// 68 = 0x44
	BOOL _dimsWhenDisabled;	// 72 = 0x48
	BOOL _disabled;	// 73 = 0x49
}
@property(assign) BOOL dimsWhenDisabled;	// G=0x34d082d9; S=0x34d082ad; converted property
@property(assign) BOOL disabled;	// G=0x34d08245; S=0x34d08211; converted property
@property(retain) BRImage *disabledImage;	// G=0x34d0829d; S=0x34d08255; converted property
@property(retain) BRImage *focusedImage;	// G=0x34d081a9; S=0x34d08161; converted property
@property(retain) BRImage *unfocusedImage;	// G=0x34d08201; S=0x34d081b9; converted property
- (void)_updateDim;	// 0x34d084c1
- (void)_updateImage;	// 0x34d08415
- (void)controlWasFocused;	// 0x34d082e9
- (void)controlWasUnfocused;	// 0x34d08339
- (void)dealloc;	// 0x34d080f9
// converted property getter: - (BOOL)dimsWhenDisabled;	// 0x34d082d9
// converted property getter: - (BOOL)disabled;	// 0x34d08245
// converted property getter: - (id)disabledImage;	// 0x34d0829d
// converted property getter: - (id)focusedImage;	// 0x34d081a9
- (id)preferredActionForKey:(id)key;	// 0x34d08389
// converted property setter: - (void)setDimsWhenDisabled:(BOOL)disabled;	// 0x34d082ad
// converted property setter: - (void)setDisabled:(BOOL)disabled;	// 0x34d08211
// converted property setter: - (void)setDisabledImage:(id)image;	// 0x34d08255
// converted property setter: - (void)setFocusedImage:(id)image;	// 0x34d08161
// converted property setter: - (void)setUnfocusedImage:(id)image;	// 0x34d081b9
// converted property getter: - (id)unfocusedImage;	// 0x34d08201
@end

