/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRSingleton.h"

@class NSDictionary;

__attribute__((visibility("hidden")))
@interface BRFontCache : BRSingleton {
@private
	CGSize _displaySize;	// 4 = 0x4
	NSDictionary *_cache;	// 12 = 0xc
}
+ (void)setSingleton:(id)singleton;	// 0x34dc2f31
+ (id)singleton;	// 0x34dc2f25
- (id)init;	// 0x34dc2f3d
- (CTFontRef)_createFontForAttributes:(id)attributes;	// 0x34dc3209
- (id)addRealFontsToAttributedString:(id)attributedString;	// 0x34dc2fe9
- (CTFontRef)createFontForRowHeight:(float)rowHeight fontName:(id)name;	// 0x34dc30b5
- (void)dealloc;	// 0x34dc2fa5
- (void)setDisplaySize:(CGSize)size;	// 0x34dc31a5
@end

