/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRControl.h"
#import "AppleTV-Structs.h"

@class BRMarqueeStack;

__attribute__((visibility("hidden")))
@interface BRFrontControl : BRControl {
@private
	BRMarqueeStack *_marqueeStack;	// 44 = 0x2c
}
- (void)dealloc;	// 0x34d29929
- (void)setMarqueeStack:(id)stack;	// 0x34d2996d
@end

