/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRController.h"

@class NSString, NSMutableArray;
@protocol BRFullScreenPhotoControllerDelegate, BRPhotoProviderForCollection;

@interface BRFullScreenPhotoController : BRController {
@private
	long _startIndex;	// 60 = 0x3c
	long _currentIndex;	// 64 = 0x40
	id<BRPhotoProviderForCollection> _provider;	// 68 = 0x44
	id<BRFullScreenPhotoControllerDelegate> _delegate;	// 72 = 0x48
	BOOL _isNetworkDependent;	// 76 = 0x4c
	BOOL _syncEventOccurred;	// 77 = 0x4d
	NSMutableArray *_prefetchImageIDs;	// 80 = 0x50
	NSString *_lastPrefetchAssetID;	// 84 = 0x54
	BOOL _initialLayoutCompleted;	// 88 = 0x58
	int _startTouchXPosition;	// 92 = 0x5c
	float _curTouchOffset;	// 96 = 0x60
	BOOL _imagePrefetchDisabled;	// 100 = 0x64
	long _numPrefetchInProgress;	// 104 = 0x68
}
@property(readonly, assign) long currentIndex;	// G=0x34cdddcd; converted property
@property(assign) BOOL imagePrefetchDisabled;	// G=0x34cdde4d; S=0x34cdde35; converted property
@property(assign) BOOL isNetworkDependent;	// G=0x34cdde25; S=0x34cdde15; converted property
@property(readonly, assign, nonatomic) id<BRPhotoProviderForCollection> provider;	// G=0x34cde1f1; @synthesize=_provider
+ (id)fullScreenPhotoControllerForProvider:(id)provider startIndex:(long)index;	// 0x34cdd9d9
- (id)initWithProvider:(id)provider startIndex:(long)index;	// 0x34cdda21
- (void)_handleSelection;	// 0x34cde429
- (void)_nextSlide;	// 0x34cde329
- (void)_nextSlideWithTransition;	// 0x34cde3b1
- (void)_playerStateChanged:(id)changed;	// 0x34cdebb9
- (void)_prefetchImageWritten:(id)written;	// 0x34cdec41
- (void)_prefetchNextImage;	// 0x34cde981
- (void)_previousSlide;	// 0x34cde36d
- (void)_previousSlideWithTransition;	// 0x34cde3ed
- (void)_setImageLayerTargetBounds;	// 0x34cde201
- (long)_switchToImageControlForIndex:(long)index usingSwipeTransition:(BOOL)transition;	// 0x34cde621
- (id)accessibilityLabel;	// 0x34cddb21
- (BOOL)brEventAction:(id)action;	// 0x34cdde5d
- (void)controlWasActivated;	// 0x34cddcc1
- (void)controlWasDeactivated;	// 0x34cddd2d
// converted property getter: - (long)currentIndex;	// 0x34cdddcd
- (void)dealloc;	// 0x34cddc1d
// converted property getter: - (BOOL)imagePrefetchDisabled;	// 0x34cdde4d
- (BOOL)isAccessibilityElement;	// 0x34cddb1d
// converted property getter: - (BOOL)isNetworkDependent;	// 0x34cdde25
- (BOOL)isValidAfterDataUpdate;	// 0x34cddd7d
- (void)layoutSubcontrols;	// 0x34cde0c5
// declared property getter: - (id)provider;	// 0x34cde1f1
- (void)reload;	// 0x34cde1b5
- (void)setControllerDelegate:(id)delegate;	// 0x34cddddd
// converted property setter: - (void)setImagePrefetchDisabled:(BOOL)disabled;	// 0x34cdde35
// converted property setter: - (void)setIsNetworkDependent:(BOOL)dependent;	// 0x34cdde15
@end

