/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRSingleton.h"

@protocol BRHomeShareHandler;

@interface BRHomeShareManager : BRSingleton {
@private
	Class _homeShareHandlerClass;	// 4 = 0x4
	id<BRHomeShareHandler> _handlerInstance;	// 8 = 0x8
}
+ (void)setSingleton:(id)singleton;	// 0x34d96059
+ (id)singleton;	// 0x34d9604d
- (void)disableHomeSharing;	// 0x34d961a5
- (void)enableHomeSharingWithAccountName:(id)accountName andPassword:(id)password;	// 0x34d96179
- (id)handler;	// 0x34d962ad
- (BOOL)hasHomeShareAccount;	// 0x34d961ed
- (id)homeShareAccount;	// 0x34d96211
- (id)homeSharingGroupIDIsEnabled:(id *)enabled;	// 0x34d96151
- (BOOL)isHomeSharingEnabled;	// 0x34d961c9
- (unsigned long long)machineIDForServer:(ATVDataServerRef)server;	// 0x34d96285
- (long)pairForHomeShareStreamingWithHost:(ATVDataServerRef)host;	// 0x34d96235
- (unsigned long long)pairingGUIDForServer:(ATVDataServerRef)server;	// 0x34d9625d
- (void)registerHandlerClass:(Class)aClass;	// 0x34d96065
@end

