/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import <Foundation/Foundation.h> // Unknown library

@class NSLock, NSMutableDictionary, BRAsyncTaskContext, NSMutableArray, NSString;

@interface BRImageManager : NSObject {
@private
	unsigned long long _maxCacheSize;	// 4 = 0x4
	unsigned long long _cacheSize;	// 12 = 0xc
	unsigned long long _maxCacheCount;	// 20 = 0x14
	unsigned long long _cacheCount;	// 28 = 0x1c
	unsigned long long _cacheSizePurgeThreshhold;	// 36 = 0x24
	BOOL _cachePurging;	// 44 = 0x2c
	BOOL _purgeCacheOnLoadAndQuit;	// 45 = 0x2d
	NSString *_imageCachePath;	// 48 = 0x30
	NSMutableDictionary *_images;	// 52 = 0x34
	NSMutableDictionary *_remoteImageRequests;	// 56 = 0x38
	NSLock *_remoteImageLock;	// 60 = 0x3c
	NSMutableArray *_jobQueue;	// 64 = 0x40
	NSMutableDictionary *_pendingCachedImagesToFlush;	// 68 = 0x44
	BOOL _processJobs;	// 72 = 0x48
	BRAsyncTaskContext *_loadTaskContext;	// 76 = 0x4c
	BRAsyncTaskContext *_writeTaskContext;	// 80 = 0x50
	NSMutableArray *_activeDelegates;	// 84 = 0x54
	int _pruneCount;	// 88 = 0x58
}
+ (id)fullScreenImageResizingOptions;	// 0x34dc5a5d
+ (id)generalPurposeManager;	// 0x34dc6151
+ (id)screenSaverManager;	// 0x34dc6281
+ (id)trickPlayManager;	// 0x34dc636d
- (id)initWithCachePath:(id)cachePath purgeCacheOnLoadAndQuit:(BOOL)quit maxCacheSizeInMB:(unsigned long long)mb maxCacheCount:(unsigned long long)count cacheSizePurgeThreshholdInMB:(unsigned long long)mb5 pruneCount:(int)count6;	// 0x34dc5add
- (void)_ATVDataImageAvailable:(id)available;	// 0x34dca589
- (void)_addLoadJobToQueue:(id)queue;	// 0x34dc8561
- (void)_addWriteJobToQueue:(id)queue withImageID:(id)imageID height:(int)height width:(int)width cropped:(BOOL)cropped;	// 0x34dc8059
- (id)_cachedCroppedImageKeyForImageID:(id)imageID forSize:(CGSize)size;	// 0x34dca3d9
- (id)_cachedCroppedImagePathForImageID:(id)imageID forSize:(CGSize)size;	// 0x34dca2d5
- (id)_cachedOriginalImagePathForImageID:(id)imageID;	// 0x34dca19d
- (id)_cachedResizedImageKeyForImageID:(id)imageID forSize:(CGSize)size;	// 0x34dca381
- (id)_cachedResizedImagePathForImageID:(id)imageID forSize:(CGSize)size;	// 0x34dca229
- (void)_decrementCacheSize:(unsigned long long)size;	// 0x34dc9ead
- (id)_defaultResizingImageOptions;	// 0x34dc927d
- (id)_extensionForImageID:(id)imageID;	// 0x34dca511
- (id)_imageFromWriteQueue:(id)writeQueue;	// 0x34dca431
- (void)_imageLoadFailed:(id)failed;	// 0x34dc9abd
- (void)_imageLoadSucceeded:(id)succeeded;	// 0x34dc978d
- (void)_incrementCacheSize:(unsigned long long)size;	// 0x34dc9d69
- (BOOL)_isLoadJobQueued:(id)queued;	// 0x34dc9eed
- (void)_maintainImageCache:(id)cache;	// 0x34dc94c1
- (void)_performLoadJob:(id)job;	// 0x34dc8815
- (void)_performWriteJob:(id)job;	// 0x34dc83d5
- (void)_postUnavailableImageNotification:(id)notification;	// 0x34dc9bed
- (void)_postUpdateNotification:(id)notification;	// 0x34dc9bbd
- (void)_postWriteCompletedNotification:(id)notification size:(CGSize)size cropped:(BOOL)cropped;	// 0x34dc9c51
- (void)_purgeRemoveDirectory:(BOOL)directory;	// 0x34dca745
- (id)_queuedLoadJobWithName:(id)name;	// 0x34dc9f85
- (void)_removeCacheFile:(id)file;	// 0x34dc943d
- (void)_removeLoadJobFromQueue:(id)queue;	// 0x34dc8701
- (void)_removeRemoteImageRequestNamed:(id)named;	// 0x34dc92fd
- (void)_removeWriteJobFromQueue:(id)queue;	// 0x34dc82f5
- (void)_startLoadJob:(id)job;	// 0x34dc8681
- (void)_startWriteJob:(id)job;	// 0x34dc826d
- (void)_terminateNotification:(id)notification;	// 0x34dca0cd
- (BOOL)_updateExistingImageRecord:(id)record;	// 0x34dc8bf9
- (id)_writeIDForImageID:(id)imageID cropped:(BOOL)cropped size:(CGSize)size;	// 0x34dca129
- (void)_writeImage:(id)image named:(id)named forSize:(CGSize)size cropped:(BOOL)cropped;	// 0x34dc8cfd
- (id)absolutePathForImageID:(id)imageID;	// 0x34dc7fe9
- (id)cachePath;	// 0x34dc802d
- (float)cacheSize;	// 0x34dc803d
- (void)cancelWriteForImageWithURL:(id)url imageID:(id)anId;	// 0x34dc6845
- (void)dealloc;	// 0x34dc6055
- (id)downSampleImage:(id)image name:(id)name scaledToSize:(CGSize)size writeToDisk:(BOOL)disk;	// 0x34dc7645
- (BOOL)hasRemoteImageBeenRequestedForMediaID:(id)mediaID;	// 0x34dc7d55
- (id)imageNameFromURL:(id)url;	// 0x34dc65c9
- (id)imageNamed:(id)named;	// 0x34dc73b9
- (id)imageNamed:(id)named croppedToSize:(CGSize)size create:(BOOL)create;	// 0x34dc6ea9
- (id)imageNamed:(id)named scaledToSize:(CGSize)size;	// 0x34dc7381
- (BOOL)isImageAvailable:(id)available;	// 0x34dc6459
- (BOOL)isImageAvailable:(id)available croppedToSize:(CGSize)size;	// 0x34dc6591
- (BOOL)isImageAvailable:(id)available scaledToSize:(CGSize)size;	// 0x34dc6559
- (BOOL)isImageWritten:(id)written;	// 0x34dc6545
- (id)loadImageFromURL:(id)url headerFields:(id)fields decryptionAgent:(id)agent;	// 0x34dc68a5
- (void)moveImageFromPath:(id)path imageID:(id)anId;	// 0x34dc6b39
- (void)purge;	// 0x34dc8015
- (void)purgeAndRemoveDirectory;	// 0x34dc7ffd
- (void)purgeRemoteRequest;	// 0x34dc7ead
- (BOOL)receiveRemoteImageURL:(id)url forID:(id)anId;	// 0x34dc7a69
- (BOOL)receiveRemoteImageURL:(id)url forID:(id)anId withResizingOptions:(id)resizingOptions;	// 0x34dc7aa1
- (void)receivedRemoteITunesImage:(id)image forID:(id)anId;	// 0x34dc7931
- (void)receivedRemoteImage:(id)image forID:(id)anId;	// 0x34dc7c19
- (void)remoteImageRequestForMediaID:(id)mediaID;	// 0x34dc7791
- (void)writeCroppedImage:(id)image named:(id)named;	// 0x34dc6add
- (id)writeEncryptedImageFromURL:(id)url;	// 0x34dc6675
- (void)writeImage:(id)image named:(id)named;	// 0x34dc69d1
- (void)writeImage:(id)image named:(id)named asynchronous:(BOOL)asynchronous;	// 0x34dc69f1
- (id)writeImageFromImageProxy:(id)imageProxy;	// 0x34dc65f5
- (id)writeImageFromURL:(id)url;	// 0x34dc6655
- (id)writeImageFromURL:(id)url decryptionAgent:(id)agent;	// 0x34dc66c1
- (id)writeImageFromURL:(id)url headerFields:(id)fields decryptionAgent:(id)agent;	// 0x34dc66e1
- (id)writeImageFromURL:(id)url imageID:(id)anId headerFields:(id)fields decryptionAgent:(id)agent;	// 0x34dc6705
- (void)writeScaledImage:(id)image named:(id)named withSize:(CGSize)size;	// 0x34dc6a45
@end

