/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRProvider.h"
#import <Foundation/Foundation.h> // Unknown library

@class NSArray;

@interface BRImageProxyProvider : NSObject <BRProvider> {
@private
	NSArray *_images;	// 4 = 0x4
}
+ (id)providerWithAssets:(id)assets;	// 0x34cdf76d
+ (id)providerWithImageProxies:(id)imageProxies;	// 0x34cdf6e9
- (id)initWithAssets:(id)assets;	// 0x34cdf7a1
- (id)initWithImageProxies:(id)imageProxies;	// 0x34cdf71d
- (id)controlFactory;	// 0x34cdf835
- (id)dataAtIndex:(long)index;	// 0x34cdf859
- (long)dataCount;	// 0x34cdf839
- (void)dealloc;	// 0x34cdf7f1
- (id)hashForDataAtIndex:(long)index;	// 0x34cdf8f1
@end

