/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class NSString, BRImage;

@interface BRImageControl : BRControl {
@private
	BRImage *_image;	// 44 = 0x2c
	BOOL _renderingImage;	// 48 = 0x30
	BOOL _autoDownsample;	// 49 = 0x31
	NSString *_artworkIdentifier;	// 52 = 0x34
	BOOL _sizeIgnoresPixelBounds;	// 56 = 0x38
}
@property(assign) BOOL automaticDownsample;	// G=0x34d10e55; S=0x34d10dd1; converted property
@property(retain) BRImage *image;	// G=0x34d10d65; S=0x34d10c91; converted property
- (void)_imageUpdated:(id)updated;	// 0x34d11049
- (id)accessibilityLabel;	// 0x34d110e1
- (float)aspectRatio;	// 0x34d10db1
// converted property getter: - (BOOL)automaticDownsample;	// 0x34d10e55
- (void)dealloc;	// 0x34d10c11
- (void)drawInContext:(CGContextRef)context;	// 0x34d10f09
// converted property getter: - (id)image;	// 0x34d10d65
- (CGSize)pixelBounds;	// 0x34d10d75
- (void)setArtworkIdentifier:(id)identifier;	// 0x34d10e65
// converted property setter: - (void)setAutomaticDownsample:(BOOL)downsample;	// 0x34d10dd1
// converted property setter: - (void)setImage:(id)image;	// 0x34d10c91
- (void)setImageAsContents:(id)contents;	// 0x34d10ce9
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x34d10fc9
@end

