/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRITunesUtilities.h"
#import "BRSingleton.h"


@interface BRITunesLibraryUtilitiesAccess : BRSingleton <BRITunesUtilities> {
@private
	id<BRITunesUtilities> _utilitiesDelegate;	// 4 = 0x4
}
+ (void)setSingleton:(id)singleton;	// 0x34dccbc5
+ (id)singleton;	// 0x34dccbb9
- (BOOL)attemptAuthorizationForAsset:(id)asset error:(id *)error;	// 0x34dccc4d
- (void)dealloc;	// 0x34dccbd1
- (void)deauthorizeAssetIfNecessary:(id)necessary;	// 0x34dccc75
- (id)iTunesCompareAscending:(BOOL)ascending withKey:(id)key;	// 0x34dccd01
- (id)iTunesCompareAscending:(BOOL)ascending withKey:(id)key fallbackSortSelector:(SEL)selector;	// 0x34dccc95
- (int)iTunesCompareString:(id)string toString:(id)string2;	// 0x34dccd41
- (id)keyBagPathForMachineID:(unsigned long long)machineID;	// 0x34dccda9
- (unsigned long)randomPlaylistIndex:(unsigned long)index;	// 0x34dccd89
- (id)rentalGUID;	// 0x34dccdd1
- (void)setITunesUtilitiesDelegate:(id)delegate;	// 0x34dccc15
- (id)sortStringForString:(id)string;	// 0x34dccd21
- (id)urlSuitableForPlayback:(id)playback;	// 0x34dccd69
@end

