/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRInputMethod.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface BRJapaneseInputMethod : BRInputMethod {
@private
	NSString *_mostRecentCandidateBaseCharacter;	// 32 = 0x20
}
- (id)_keyboardsForTextEntryStyle:(int)textEntryStyle;	// 0x34d38149
- (id)candidates;	// 0x34d38145
- (void)dealloc;	// 0x34d380b5
- (BOOL)inputText:(id)text;	// 0x34d38141
- (id)isoLanguageCode;	// 0x34d38105
- (id)name;	// 0x34d380f9
- (BOOL)usesCandidateDisplayForKeyboard:(id)keyboard;	// 0x34d38111
@end

