/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRKeyboard.h"

@class BRWaitSpinnerControl;

__attribute__((visibility("hidden")))
@interface BRKeyboardRomanSquare : BRKeyboard {
@private
	BRWaitSpinnerControl *_spinner;	// 32 = 0x20
}
- (float)_actionKeysContainerBaseGap:(id)gap resolutionScale:(float)scale;	// 0x34d3f021
- (CGSize)_actionKeysContainerSize:(id)size resolutionScale:(float)scale;	// 0x34d3efdd
- (id)_keyboardDataFileName;	// 0x34d3e95d
- (id)_mainKeyRowWithKeys:(id)keys index:(int)index;	// 0x34d3e999
- (float)_mainKeysContainerBaseGap:(id)gap resolutionScale:(float)scale;	// 0x34d3efc1
- (CGSize)_mainKeysContainerSize:(id)size resolutionScale:(float)scale;	// 0x34d3ef7d
- (float)_mainKeysVerticalSpacing;	// 0x34d3e9fd
- (CGSize)_minTextEntryControlSize:(id)size resolutionScale:(float)scale;	// 0x34d3edd9
- (int)_numberOfColumnsForMainKeyRowIndex:(int)mainKeyRowIndex;	// 0x34d3e98d
- (int)_numberOfMainKeyRows;	// 0x34d3e989
- (float)_preferredGlyphHeight:(id)height;	// 0x34d3e97d
- (float)_preferredGlyphWidth:(id)width;	// 0x34d3e975
- (id)_spinner;	// 0x34d3f041
- (long)_startingIndexOfActionKeysInKeyRowData;	// 0x34d3f03d
- (float)_tabControlBaseGap:(id)gap resolutionScale:(float)scale;	// 0x34d3ef61
- (void)_tagBottomKeyRow:(id)row;	// 0x34d3e985
- (float)_textFieldBackgroundBaseGap:(id)gap resolutionScale:(float)scale;	// 0x34d3ef45
- (CGSize)_textFieldBackgroundSize:(id)size resolutionScale:(float)scale;	// 0x34d3eeed
- (float)_topMostUIElementGap:(id)gap resolutionScale:(float)scale;	// 0x34d3eed1
- (id)actionDictionaryForKeyControl:(id)keyControl;	// 0x34d3e885
- (id)actionKeyRows;	// 0x34d3e4fd
- (id)actionKeysContainer;	// 0x34d3e53d
- (id)attributesForTextFieldLabel;	// 0x34d3e4d9
- (id)bottomRow;	// 0x34d3e52d
- (BOOL)canShowLanguageSwitchButton;	// 0x34d3e881
- (id)customizedTextEntryFieldControls;	// 0x34d3e465
- (void)customizedTextFieldControlsWereRemoved;	// 0x34d3e4b1
- (void)dealloc;	// 0x34d3e3b1
- (id)focusedControlAndRow:(id *)row;	// 0x34d3e805
- (void)setFocusToDefaultSwitchKeyboardGlyph:(id)defaultSwitchKeyboardGlyph;	// 0x34d3e74d
- (CGRect)spinnerFrame:(id)frame resolutionScale:(float)scale;	// 0x34d3ecf9
- (void)startSpinning;	// 0x34d3e3f5
- (void)stopSpinning;	// 0x34d3e42d
- (CGRect)tabControlFrame:(id)frame resolutionScale:(float)scale;	// 0x34d3ec01
- (CGRect)textFieldBackgroundFrame:(id)frame resolutionScale:(float)scale;	// 0x34d3ea05
- (CGRect)textFieldFrame:(id)frame resolutionScale:(float)scale;	// 0x34d3ea8d
@end

