/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRControl.h"
#import "AppleTV-Structs.h"


__attribute__((visibility("hidden")))
@interface BRKeyboardActionControl : BRControl {
@private
	CGSize _characterControlSize;	// 44 = 0x2c
}
- (id)init;	// 0x34d38209
- (id)accessibilityLabel;	// 0x34d38579
- (id)accessibilityTraits;	// 0x34d3854d
- (CGRect)focusCursorFrame;	// 0x34d38251
- (BOOL)isAccessibilityElement;	// 0x34d38549
- (void)layoutSubcontrols;	// 0x34d38401
- (void)setCharacterControlSize:(CGSize)size;	// 0x34d382a5
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x34d382fd
- (id)wrappedControl;	// 0x34d382b9
@end

