/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRKeyboardRomanLogIn.h"


__attribute__((visibility("hidden")))
@interface BRKeyboardRomanLogInUpperCase : BRKeyboardRomanLogIn {
}
- (id)accessibilityLabel;	// 0x34d47b91
- (id)name;	// 0x34d47b81
- (id)switchToThisKeyboardIdentifier;	// 0x34d47b59
@end

