/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRKeyboardJapaneseRomanSquare.h"


__attribute__((visibility("hidden")))
@interface BRKeyboardJapaneseRomanSymbols : BRKeyboardJapaneseRomanSquare {
}
- (id)actionDictionaryForKeyControl:(id)keyControl;	// 0x34d3d34d
- (id)name;	// 0x34d3d1a1
- (void)setFocusToDefaultSwitchKeyboardGlyph:(id)defaultSwitchKeyboardGlyph;	// 0x34d3d1b1
@end

