/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import <Foundation/Foundation.h> // Unknown library

@class BRControl, NSString, BRScrollControl, NSDictionary;

__attribute__((visibility("hidden")))
@interface BRKeyboard : NSObject {
@private
	BRControl *_baseKeyControl;	// 4 = 0x4
	NSString *_name;	// 8 = 0x8
	int _baseKeyboardType;	// 12 = 0xc
	BOOL _shouldShowLanguageSwitchButton;	// 16 = 0x10
	BOOL _canWrapHorizontally;	// 17 = 0x11
	BOOL _canWrapVertically;	// 18 = 0x12
	BOOL _constrainCursorToPopupKeyboard;	// 19 = 0x13
	NSDictionary *_rawKeyboardData;	// 20 = 0x14
	BRScrollControl *_mainKeysContainer;	// 24 = 0x18
	BRControl *_actionKeysRow;	// 28 = 0x1c
}
@property(retain) id actionKeysContainer;	// G=0x34d38bfd; S=0x34d38c0d; converted property
@property(retain) BRControl *baseKeyControl;	// G=0x34d38a2d; S=0x34d38a1d; converted property
@property(assign) BOOL canWrapHorizontally;	// G=0x34d389c5; S=0x34d389d5; converted property
@property(assign) BOOL canWrapVertically;	// G=0x34d389e5; S=0x34d389f5; converted property
@property(readonly, retain) BRScrollControl *mainKeysContainer;	// G=0x34d38b25; converted property
@property(readonly, retain) NSString *name;	// G=0x34d38a3d; converted property
@property(assign) BOOL shouldShowLanguageSwitchButton;	// G=0x34d392e1; S=0x34d392d1; converted property
- (id)init;	// 0x34d3879d
- (id)initWithBaseKeyControl:(id)baseKeyControl;	// 0x34d388b5
- (void)_accessibilityApplyImageLabel:(id)label name:(id)name;	// 0x34d3aa1d
- (float)_actionKeysContainerBaseGap:(id)gap resolutionScale:(float)scale;	// 0x34d3c35d
- (CGSize)_actionKeysContainerSize:(id)size resolutionScale:(float)scale;	// 0x34d3c349
- (float)_candidatesBackgroundBaseGap:(id)gap resolutionScale:(float)scale;	// 0x34d3c2c1
- (CGSize)_candidatesBackgroundSize:(id)size resolutionScale:(float)scale;	// 0x34d3c2ad
- (CGSize)_candidatesContainerInset:(id)inset resolutionScale:(float)scale;	// 0x34d3c26d
- (id)_controlForData:(id)data;	// 0x34d3abc1
- (CGColorRef)_createColorFromDictionary:(id)dictionary;	// 0x34d3a96d
- (id)_filterRawKeyboardData:(id)data;	// 0x34d39f3d
- (id)_glyphDataForImage:(id)image;	// 0x34d3aa35
- (id)_glyphDataForStrings:(id)strings attributes:(id)attributes;	// 0x34d3a5d1
- (id)_glyphDataForTextString:(id)textString attributes:(id)attributes;	// 0x34d3a3f9
- (id)_keyRowData;	// 0x34d3a199
- (id)_keyRows;	// 0x34d3b189
- (id)_keyboardDataFileName;	// 0x34d39d85
- (id)_mainKeyRowPlane;	// 0x34d3b681
- (id)_mainKeyRowWithKeys:(id)keys index:(int)index;	// 0x34d3b639
- (float)_mainKeysContainerBaseGap:(id)gap resolutionScale:(float)scale;	// 0x34d3c345
- (CGSize)_mainKeysContainerSize:(id)size resolutionScale:(float)scale;	// 0x34d3c331
- (float)_mainKeysVerticalSpacing;	// 0x34d3b6ed
- (CGSize)_minTextEntryControlSize:(id)size resolutionScale:(float)scale;	// 0x34d3c23d
- (int)_numberOfColumnsForMainKeyRowIndex:(int)mainKeyRowIndex;	// 0x34d3b4a1
- (int)_numberOfMainKeyRows;	// 0x34d3b49d
- (id)_optionCharactersForKeyboardInput;	// 0x34d3b11d
- (float)_playPauseMessageBaseGap:(id)gap resolutionScale:(float)scale;	// 0x34d3c3b5
- (CGSize)_playPauseMessageSize:(id)size resolutionScale:(float)scale;	// 0x34d3c361
- (Class)_popupKeyboardClass;	// 0x34d3b6f5
- (id)_popupKeyboardDataFileName;	// 0x34d39d81
- (BOOL)_popupKeyboardValidForGlyph:(id)glyph;	// 0x34d3a829
- (float)_preferredGlyphHeight:(id)height;	// 0x34d3b119
- (CGSize)_preferredGlyphSize:(id)size;	// 0x34d3b715
- (float)_preferredGlyphWidth:(id)width;	// 0x34d3b115
- (id)_processGlyphDataChunk:(id)chunk;	// 0x34d3a281
- (id)_rawKeyboardData;	// 0x34d39dc5
- (int)_scrollDirectionForMainKeys;	// 0x34d3b6f1
- (float)_tabControlBaseGap:(id)gap resolutionScale:(float)scale;	// 0x34d3c32d
- (CGSize)_tabControlSize:(id)size resolutionScale:(float)scale;	// 0x34d3c2c5
- (void)_tagBottomKeyRow:(id)row;	// 0x34d3b46d
- (float)_textFieldBackgroundBaseGap:(id)gap resolutionScale:(float)scale;	// 0x34d3c269
- (CGSize)_textFieldBackgroundSize:(id)size resolutionScale:(float)scale;	// 0x34d3c255
- (float)_topMostUIElementGap:(id)gap resolutionScale:(float)scale;	// 0x34d3c251
- (id)actionDictionaryForCustomControl:(id)customControl;	// 0x34d3970d
- (id)actionDictionaryForKeyControl:(id)keyControl;	// 0x34d392f5
- (id)actionKeyRows;	// 0x34d38ab9
// converted property getter: - (id)actionKeysContainer;	// 0x34d38bfd
- (CGRect)actionKeysContainerFrame:(id)frame resolutionScale:(float)scale;	// 0x34d3ba99
- (id)allPopupkeyboardsCharacterSet;	// 0x34d39a09
- (id)attributesForTextFieldLabel;	// 0x34d38999
// converted property getter: - (id)baseKeyControl;	// 0x34d38a2d
- (id)bottomRow;	// 0x34d38b01
- (BOOL)canShowLanguageSwitchButton;	// 0x34d392f1
// converted property getter: - (BOOL)canWrapHorizontally;	// 0x34d389c5
// converted property getter: - (BOOL)canWrapVertically;	// 0x34d389e5
- (CGRect)candidatesBackgroundFrame:(id)frame resolutionScale:(float)scale;	// 0x34d3bad9
- (CGRect)candidatesContainerFrame:(id)frame resolutionScale:(float)scale;	// 0x34d3bb19
- (id)customizeTextEntryControls:(id)controls;	// 0x34d38979
- (id)customizedTextEntryFieldControls;	// 0x34d38969
- (void)customizedTextFieldControlsWereRemoved;	// 0x34d38975
- (void)dealloc;	// 0x34d388e9
- (BOOL)focusIsAtRightEdge;	// 0x34d38f25
- (id)focusedControlAndRow:(id *)row;	// 0x34d38f71
- (id)focusedControlForActionKeysContainer:(id)actionKeysContainer;	// 0x34d390f9
- (id)focusedControlForRow:(id)row;	// 0x34d390e1
- (CGPoint)focusedRowAndOffsetIndex;	// 0x34d39111
- (BOOL)handleEvent:(id)event;	// 0x34d39725
- (id)keyboardCharacterSet;	// 0x34d39841
- (BOOL)keyboardFocusIsAtEdge:(int)edge;	// 0x34d38c4d
- (CGSize)keyboardSize:(id)size;	// 0x34d3b8ad
- (void)layoutCustomControls:(id)controls resolutionScale:(float)scale;	// 0x34d38995
- (id)mainKeyRows;	// 0x34d38a49
// converted property getter: - (id)mainKeysContainer;	// 0x34d38b25
- (CGRect)mainKeysContainerFrame:(id)frame resolutionScale:(float)scale;	// 0x34d3bab9
- (int)mapVisualIndex:(int)index toRow:(id)row;	// 0x34d392c9
// converted property getter: - (id)name;	// 0x34d38a3d
- (int)numberOfKeyboardsForCurrentKeyboardType;	// 0x34d38a15
- (id)popupKeyboardForKeyControl:(id)keyControl baseKeyboardType:(int)type textEntryControl:(id)control;	// 0x34d38dd5
- (BOOL)popupKeyboardShouldBeRightAlignedForKey:(id)popupKeyboard;	// 0x34d38f1d
- (BOOL)popupKeyboardShouldRemainDisplayedAfterCharacterSelection;	// 0x34d38f21
- (float)popupKeyboardWidth:(id)width;	// 0x34d38e55
- (void)removeCustomizedTextEntryControls:(id)controls;	// 0x34d38991
- (BOOL)requiresTextFieldLabel;	// 0x34d39711
// converted property setter: - (void)setActionKeysContainer:(id)container;	// 0x34d38c0d
// converted property setter: - (void)setBaseKeyControl:(id)control;	// 0x34d38a1d
- (void)setBaseKeyboardType:(int)type;	// 0x34d38a05
// converted property setter: - (void)setCanWrapHorizontally:(BOOL)horizontally;	// 0x34d389d5
// converted property setter: - (void)setCanWrapVertically:(BOOL)vertically;	// 0x34d389f5
- (void)setConstrainCursorToPopupKeyboard:(BOOL)popupKeyboard;	// 0x34d39715
- (void)setFocusToDefaultGlyph;	// 0x34d38d49
- (void)setFocusToDefaultSwitchKeyboardGlyph:(id)defaultSwitchKeyboardGlyph;	// 0x34d38dd1
- (void)setFocusedControlWithVisualIndex:(int)visualIndex forRow:(id)row;	// 0x34d39085
- (BOOL)setFocusedRowAndOffsetIndex:(CGPoint)index;	// 0x34d391b1
// converted property setter: - (void)setShouldShowLanguageSwitchButton:(BOOL)showLanguageSwitchButton;	// 0x34d392d1
- (BOOL)shouldAcceptFocus;	// 0x34d38d45
// converted property getter: - (BOOL)shouldShowLanguageSwitchButton;	// 0x34d392e1
- (CGRect)spinnerFrame:(id)frame resolutionScale:(float)scale;	// 0x34d3c21d
- (void)startSpinning;	// 0x34d3896d
- (void)stopSpinning;	// 0x34d38971
- (BOOL)supportsTextEntryHistory;	// 0x34d38a19
- (id)switchToThisKeyboardIdentifier;	// 0x34d38965
- (CGRect)tabControlFrame:(id)frame resolutionScale:(float)scale;	// 0x34d3c0f1
- (BOOL)textEntryControlShouldHandleActionKeysEvents;	// 0x34d38c49
- (BOOL)textEntryControlShouldHandleMainKeysEvents;	// 0x34d38c45
- (CGRect)textFieldBackgroundFrame:(id)frame resolutionScale:(float)scale;	// 0x34d3bdad
- (CGRect)textFieldFrame:(id)frame resolutionScale:(float)scale;	// 0x34d3bfcd
- (CGRect)textFieldLabelFrame:(id)frame resolutionScale:(float)scale;	// 0x34d3bbf5
- (id)topRow;	// 0x34d38abd
- (int)visualIndexOfControlWithName:(id)name forRow:(id)row;	// 0x34d39005
- (int)visualIndexOfFocusedControlForRow:(id)row;	// 0x34d38fc9
@end

