/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRMenuView.h"
#import "AppleTV-Structs.h"

@class BRMediaPlayer, BRControl, BRImageControl, BRPhotoMediaCollection, NSString, NSArray;

__attribute__((visibility("hidden")))
@interface BRMarimbaMenuView : BRMenuView {
@private
	BRMediaPlayer *_slideshowPhotoPlayer;	// 76 = 0x4c
	BRImageControl *_listBackgroundControl;	// 80 = 0x50
	BRControl *_slideshowPreview;	// 84 = 0x54
	BRPhotoMediaCollection *_collection;	// 88 = 0x58
	NSArray *_slideshowThemeIdentifierKeys;	// 92 = 0x5c
	NSString *_nextSlideshowTheme;	// 96 = 0x60
	NSString *_newlyRequestedTheme;	// 100 = 0x64
	BRControl *_fadeThroughBlackShroudControl;	// 104 = 0x68
	BOOL _themeSwitchInFlight;	// 108 = 0x6c
	BOOL _playerVisualsChanged;	// 109 = 0x6d
	BOOL _fadeThroughBlackControlNeedsLayout;	// 110 = 0x6e
}
- (id)initWithMediaCollection:(id)mediaCollection;	// 0x34d5db59
- (void)_beginTransitionToNewTheme;	// 0x34d5e995
- (void)_fadeInAnimationCompleted:(id)animationCompleted;	// 0x34d5eddd
- (void)_fadeOutAnimationCompleted:(id)completed;	// 0x34d5eb49
- (void)_finishTransitionToNewTheme;	// 0x34d5eca9
- (void)_insertSlideshowPreview;	// 0x34d5e8a9
- (void)_marimbaLayerTransitionIsFinished:(id)finished;	// 0x34d5e981
- (void)_playerVisualsChanged:(id)changed;	// 0x34d5e7bd
- (void)_prepareToBeginTransitionToNewTheme;	// 0x34d5e919
- (void)_removeSlideshowPreview;	// 0x34d5e835
- (void)controlWasActivated;	// 0x34d5de19
- (void)controlWasDeactivated;	// 0x34d5dfe9
- (id)currentTheme;	// 0x34d5e425
- (id)currentTransitions;	// 0x34d5e4f5
- (void)dealloc;	// 0x34d5dd29
- (void)layoutSubcontrols;	// 0x34d5e025
- (id)musicServerID;	// 0x34d5e67d
- (void)playSlideshow;	// 0x34d5e139
- (id)playlistID;	// 0x34d5e631
- (void)setLoopPhotos:(BOOL)photos;	// 0x34d5e78d
- (void)setMusicServerID:(id)anId playlistID:(id)anId2 playlistRef:(ATVMediaCollectionRef)ref;	// 0x34d5e531
- (void)setMuted:(BOOL)muted;	// 0x34d5e229
- (void)setTimePerSlide:(double)slide;	// 0x34d5e6ed
- (void)stopSlideshow;	// 0x34d5e171
- (void)switchToNewMenu;	// 0x34d5e6c9
- (BOOL)switchToTheme:(id)theme;	// 0x34d5e249
- (void)switchToTransition:(id)transition;	// 0x34d5e461
- (void)toggleSlideshowPlayback;	// 0x34d5e1e9
@end

