/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRControl.h"
#import "AppleTV-Structs.h"

@class BRTextControl;

@interface BRMainMenuShelfErrorControl : BRControl {
@private
	BRTextControl *_text;	// 44 = 0x2c
	BRTextControl *_subtext;	// 48 = 0x30
}
@property(retain) BRTextControl *subtext;	// G=0x34d1de29; S=0x34d1dddd; converted property
@property(retain) BRTextControl *text;	// G=0x34d1ddad; S=0x34d1dd61; converted property
- (id)init;	// 0x34d1dc59
- (id)_subtextAttributes;	// 0x34d1e065
- (id)_textAttributes;	// 0x34d1df09
- (id)accessibilityLabel;	// 0x34d1e1c1
- (void)dealloc;	// 0x34d1dd09
- (void)layoutSubcontrols;	// 0x34d1de59
// converted property setter: - (void)setSubtext:(id)subtext;	// 0x34d1dddd
// converted property setter: - (void)setText:(id)text;	// 0x34d1dd61
// converted property getter: - (id)subtext;	// 0x34d1de29
// converted property getter: - (id)text;	// 0x34d1ddad
@end

