/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class BRTextControl, BRImageControl;

@interface BRMetadataTitleControl : BRControl {
@private
	BRTextControl *_title;	// 44 = 0x2c
	BRTextControl *_titleSubtext;	// 48 = 0x30
	BRImageControl *_rating;	// 52 = 0x34
	BRImageControl *_rightImage;	// 56 = 0x38
	BOOL _ratingSnapsToTitle;	// 60 = 0x3c
	float _rightImageHeight;	// 64 = 0x40
}
- (id)init;	// 0x34d27841
- (id)accessibilityLabel;	// 0x34d28209
- (void)dealloc;	// 0x34d279d5
- (void)layoutSubcontrols;	// 0x34d27d01
- (CGSize)renderedSize;	// 0x34d27c41
- (void)setRating:(id)rating;	// 0x34d27b35
- (void)setRatingSnapsToTitle:(BOOL)title;	// 0x34d27ba9
- (void)setRightImage:(id)image;	// 0x34d27bd5
- (void)setRightImageFixedHeight:(float)height;	// 0x34d27c09
- (void)setTitle:(id)title;	// 0x34d27a51
- (void)setTitleSubtext:(id)subtext;	// 0x34d27ac1
@end

