/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRImageLoader.h"


__attribute__((visibility("hidden")))
@interface BRMediaParadeProvider : BRImageLoader {
@private
	unsigned _artworkNeedsDeletterboxing : 1;	// 68 = 0x44
}
- (id)finalFormForImage:(id)image;	// 0x34d227cd
- (BOOL)isImageFinalForm:(id)form;	// 0x34d22859
- (void)setDeletterboxAssetArtwork:(BOOL)artwork;	// 0x34d2283d
@end

