/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library

@class NSString, NSDictionary, BRImage;

@interface BRMerchantInfo : NSObject {
@private
	NSDictionary *_vendorBag;	// 4 = 0x4
	BOOL _enabled;	// 8 = 0x8
	NSString *featureName;	// 12 = 0xc
	NSDictionary *metadata;	// 16 = 0x10
	NSDictionary *resources;	// 20 = 0x14
	NSDictionary *authResources;	// 24 = 0x18
}
@property(retain, nonatomic) NSDictionary *authResources;	// G=0x34db1b85; S=0x34db1b95; @synthesize
@property(readonly, assign, nonatomic) NSString *authType;	// G=0x34db19e1; 
@property(readonly, assign, nonatomic) NSString *bootstrapResourceURL;	// G=0x34db19a9; 
@property(readonly, assign, nonatomic) NSString *bootstrapResourceVersion;	// G=0x34db19c5; 
@property(assign) BOOL enabled;	// G=0x34db178d; S=0x34db17fd; @dynamic
@property(retain) NSString *featureName;	// G=0x34db1add; S=0x34db1af5; @synthesize
@property(readonly, assign, nonatomic) BRImage *menuIcon;	// G=0x34db1915; 
@property(readonly, assign, nonatomic) NSString *menuTitle;	// G=0x34db1871; 
@property(readonly, assign, nonatomic) NSString *merchantID;	// G=0x34db18f9; 
@property(retain, nonatomic) NSDictionary *metadata;	// G=0x34db1b1d; S=0x34db1b2d; @synthesize
@property(readonly, assign, nonatomic) int preferredOrder;	// G=0x34db188d; 
@property(retain, nonatomic) NSDictionary *resources;	// G=0x34db1b51; S=0x34db1b61; @synthesize
@property(readonly, assign, nonatomic) NSString *rootURL;	// G=0x34db1971; 
@property(readonly, assign, nonatomic) NSString *topShelfURL;	// G=0x34db198d; 
+ (id)infoWithMerchantIdentifier:(id)merchantIdentifier;	// 0x34db1501
+ (id)infoWithVendorBag:(id)vendorBag;	// 0x34db14cd
- (id)initWithMerchantIdentifier:(id)merchantIdentifier;	// 0x34db1611
- (id)initWithVendorBag:(id)vendorBag;	// 0x34db1535
- (void)_rehydrateDictionaries;	// 0x34db1aa1
- (void)_rehydrateDictionary:(id)dictionary forProperty:(id)property;	// 0x34db19fd
// declared property getter: - (id)authResources;	// 0x34db1b85
// declared property getter: - (id)authType;	// 0x34db19e1
// declared property getter: - (id)bootstrapResourceURL;	// 0x34db19a9
// declared property getter: - (id)bootstrapResourceVersion;	// 0x34db19c5
- (void)dealloc;	// 0x34db1705
// declared property getter: - (BOOL)enabled;	// 0x34db178d
// declared property getter: - (id)featureName;	// 0x34db1add
// declared property getter: - (id)menuIcon;	// 0x34db1915
// declared property getter: - (id)menuTitle;	// 0x34db1871
// declared property getter: - (id)merchantID;	// 0x34db18f9
// declared property getter: - (id)metadata;	// 0x34db1b1d
// declared property getter: - (int)preferredOrder;	// 0x34db188d
// declared property getter: - (id)resources;	// 0x34db1b51
// declared property getter: - (id)rootURL;	// 0x34db1971
// declared property setter: - (void)setAuthResources:(id)resources;	// 0x34db1b95
// declared property setter: - (void)setEnabled:(BOOL)enabled;	// 0x34db17fd
// declared property setter: - (void)setFeatureName:(id)name;	// 0x34db1af5
// declared property setter: - (void)setMetadata:(id)metadata;	// 0x34db1b2d
// declared property setter: - (void)setResources:(id)resources;	// 0x34db1b61
// declared property getter: - (id)topShelfURL;	// 0x34db198d
- (id)valueForUndefinedKey:(id)undefinedKey;	// 0x34db176d
@end

