/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class BRDescriptionOverlayControl, BRTextControl, BRTransportControl, BRWaitSpinnerControl;
@protocol BRMediaAsset;

__attribute__((visibility("hidden")))
@interface BRMediaPlayerWaitControl : BRControl {
@private
	id<BRMediaAsset> _asset;	// 44 = 0x2c
	BRDescriptionOverlayControl *_descriptionControl;	// 48 = 0x30
	BRTextControl *_loadingControl;	// 52 = 0x34
	BRWaitSpinnerControl *_loadingSpinner;	// 56 = 0x38
	BRTextControl *_readyToPlayInNMinsControl;	// 60 = 0x3c
	BRWaitSpinnerControl *_readyToPlayInNMinsSpinner;	// 64 = 0x40
	BRTextControl *_readyToPlayControl;	// 68 = 0x44
	BRTextControl *_authorizingControl;	// 72 = 0x48
	BRWaitSpinnerControl *_authorizingSpinner;	// 76 = 0x4c
	BRTransportControl *_transport;	// 80 = 0x50
}
- (id)initWithAsset:(id)asset;	// 0x34cf1a39
- (void)_addFadeAnimationToControl:(id)control;	// 0x34cf2831
- (void)dealloc;	// 0x34cf1ed9
- (void)layoutSubcontrols;	// 0x34cf234d
- (void)setAuthorizing;	// 0x34cf22a5
- (void)setReadyForPlayInNMins:(int)nmins;	// 0x34cf1fc1
- (void)setReadyToPlay;	// 0x34cf2225
@end

