/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library

@class NSString;

@interface BRMediaHostState : NSObject {
@private
	NSString *_description;	// 4 = 0x4
}
@property(readonly, retain) NSString *description;	// G=0x34da69cd; converted property
+ (id)available;	// 0x34da6465
+ (id)mountFailed;	// 0x34da674d
+ (id)mounted;	// 0x34da6655
+ (id)mounting;	// 0x34da655d
+ (id)unavailable;	// 0x34da636d
+ (id)unmounting;	// 0x34da6845
- (id)initWithDescription:(id)description;	// 0x34da693d
- (void)dealloc;	// 0x34da6989
// converted property getter: - (id)description;	// 0x34da69cd
- (id)mediaHostEvent:(id)event forMediaHost:(id)mediaHost;	// 0x34da69dd
@end

