/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class BRTextControl, BRDividerControl, NSArray, NSNumber, BRImageControl;

@interface BRMetadataLongDescriptionControl : BRControl {
@private
	BRTextControl *_titleLayer;	// 44 = 0x2c
	BRTextControl *_titleSubtextLayer;	// 48 = 0x30
	BRTextControl *_priceLayer;	// 52 = 0x34
	BRControl *_formatControl;	// 56 = 0x38
	BRTextControl *_releaseDateLayer;	// 60 = 0x3c
	BRTextControl *_lengthLayer;	// 64 = 0x40
	BRTextControl *_studioNameLayer;	// 68 = 0x44
	BRImageControl *_ratingImageLayer;	// 72 = 0x48
	BRControl *_userRatingControl;	// 76 = 0x4c
	BRImageControl *_topRightImageLayer;	// 80 = 0x50
	BRTextControl *_summaryLayer;	// 84 = 0x54
	BRTextControl *_copyrightLayer;	// 88 = 0x58
	NSNumber *_trackNumber;	// 92 = 0x5c
	BRDividerControl *_topDivider;	// 96 = 0x60
	BRDividerControl *_bottomDivider;	// 100 = 0x64
	NSArray *_metadataObjs;	// 104 = 0x68
	NSArray *_metadataLabels;	// 108 = 0x6c
	float _totalHeight;	// 112 = 0x70
	int _alignment;	// 116 = 0x74
	CGSize _artworkSize;	// 120 = 0x78
}
- (id)init;	// 0x34d24e05
- (void)_setCopyright:(id)copyright;	// 0x34d267e9
- (void)_setFormatControl:(id)control;	// 0x34d2622d
- (void)_setLength:(id)length;	// 0x34d2636d
- (void)_setMetadata:(id)metadata withLabels:(id)labels;	// 0x34d26755
- (void)_setPrice:(id)price;	// 0x34d2616d
- (void)_setRating:(id)rating;	// 0x34d264ed
- (void)_setReleaseDate:(id)date;	// 0x34d262ad
- (void)_setStudioName:(id)name;	// 0x34d2642d
- (void)_setSummary:(id)summary;	// 0x34d265dd
- (void)_setTitle:(id)title;	// 0x34d25ec1
- (void)_setTitleSubtext:(id)subtext;	// 0x34d25f81
- (void)_setTopRightImage:(id)image;	// 0x34d265bd
- (void)_setTrackNumber:(id)number;	// 0x34d26041
- (void)_setUserRatingControl:(id)control;	// 0x34d2653d
- (void)_themeMetricsChanged;	// 0x34d268a9
- (id)accessibilityScreenContent;	// 0x34d268b9
- (void)dealloc;	// 0x34d25169
- (void)layoutSubcontrols;	// 0x34d25781
- (CGSize)renderedSize;	// 0x34d25715
- (void)resetAllFields;	// 0x34d252f5
- (void)setAlignment:(int)alignment;	// 0x34d25e59
- (void)setArtworkSize:(CGSize)size;	// 0x34d25e69
- (void)setCopyright:(id)copyright;	// 0x34d256dd
- (void)setFormatControl:(id)control;	// 0x34d254d5
- (void)setLength:(id)length;	// 0x34d25545
- (void)setMetadata:(id)metadata withLabels:(id)labels;	// 0x34d256a5
- (void)setPrice:(id)price;	// 0x34d2549d
- (void)setRating:(id)rating;	// 0x34d255b5
- (void)setReleaseDate:(id)date;	// 0x34d2550d
- (void)setStudioName:(id)name;	// 0x34d2557d
- (void)setSummary:(id)summary;	// 0x34d2566d
- (void)setTitle:(id)title;	// 0x34d253f5
- (void)setTitleSubtext:(id)subtext;	// 0x34d2542d
- (void)setTopRightImage:(id)image;	// 0x34d25635
- (void)setTrackNumber:(id)number;	// 0x34d25465
- (void)setUserRatingControl:(id)control;	// 0x34d255ed
- (id)topRightImageControl;	// 0x34d25625
@end

