/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRContainerViewCell.h"
#import "BRControl.h"

@class NSMutableArray, NSTimer, NSDictionary;

@interface BRMediaShelfView : BRControl <BRContainerViewCell> {
@private
	id _dataSource;	// 44 = 0x2c
	id _delegate;	// 48 = 0x30
	NSDictionary *_controlActions;	// 52 = 0x34
	NSDictionary *_titleActions;	// 56 = 0x38
	BOOL _centered;	// 60 = 0x3c
	BOOL _scrollable;	// 61 = 0x3d
	NSRange _flatRange;	// 64 = 0x40
	CATransform3D _leftTransform;	// 72 = 0x48
	CATransform3D _rightTransform;	// 136 = 0x88
	NSMutableArray *_cells;	// 200 = 0xc8
	NSMutableArray *_titles;	// 204 = 0xcc
	NSTimer *_scrollTimer;	// 208 = 0xd0
	BOOL _scrolling;	// 212 = 0xd4
	int _collapsedState;	// 216 = 0xd8
	BOOL _ordered;	// 220 = 0xdc
	BOOL _needToReloadDataOnActivate;	// 221 = 0xdd
	long _numberOfItems;	// 224 = 0xe0
	NSRange _refillVisibleRange;	// 228 = 0xe4
	BOOL _restoreLastFocus;	// 236 = 0xec
	NSTimer *_forceDisplayTimer;	// 240 = 0xf0
	id _loadCompletionBlock;	// 244 = 0xf4
	BOOL _okToLoad;	// 248 = 0xf8
	BOOL _displayComplete;	// 249 = 0xf9
	long _columnCount;	// 252 = 0xfc
	float _horizontalGap;	// 256 = 0x100
	float _coverflowMargin;	// 260 = 0x104
}
@property(assign) BOOL centered;	// G=0x34cd4715; S=0x34cd46e9; converted property
@property(assign) int collapsedState;	// G=0x34cd4c6d; S=0x34cd4c45; converted property
@property(assign, nonatomic) long columnCount;	// G=0x34cd4f6d; S=0x34cd4465; @synthesize=_columnCount
@property(assign, nonatomic) float coverflowMargin;	// G=0x34cd4f8d; S=0x34cd4f9d; @synthesize=_coverflowMargin
@property(retain) id dataSource;	// G=0x34cd45e5; S=0x34cd4545; converted property
@property(assign) id delegate;	// G=0x34cd4605; S=0x34cd45f5; converted property
@property(retain) id focusedIndexPath;	// G=0x34cd4ae1; S=0x34cd4b51; converted property
@property(assign, nonatomic) float horizontalGap;	// G=0x34cd4f7d; S=0x34cd4495; @synthesize=_horizontalGap
@property(assign) BOOL ordered;	// G=0x34cd4751; S=0x34cd4725; converted property
@property(assign) BOOL scrollable;	// G=0x34cd46d9; S=0x34cd4699; converted property
- (id)init;	// 0x34cd40b5
- (long)_columnCount;	// 0x34cd506d
- (id)_controlActions;	// 0x34cd6aed
- (id)_controlsInRange:(NSRange)range oldRange:(NSRange)range2;	// 0x34cd6fb5
- (float)_coverflowMargin;	// 0x34cd5145
- (id)_createControlAtIndex:(int)index;	// 0x34cd6e61
- (id)_createControlsInRange:(NSRange)range;	// 0x34cd70fd
- (void)_displayCellsForce:(BOOL)force;	// 0x34cd7531
- (NSRange)_dividedRangeForRange:(NSRange)range andDirection:(int)direction;	// 0x34cd7969
- (unsigned)_dividerCountInRange:(NSRange)range;	// 0x34cd7ab5
- (unsigned)_firstScrollableIndex;	// 0x34cd52b9
- (void)_focusChanged:(id)changed;	// 0x34cd5205
- (void)_forceDisplayTimerFired:(id)fired;	// 0x34cd7701
- (float)_horizontalGap;	// 0x34cd50c9
- (long)_indexFromIndexPath:(id)indexPath;	// 0x34cd7f49
- (id)_indexPathFromIndex:(long)index sectionIndex:(long *)index2;	// 0x34cd7ff5
- (BOOL)_isDividerAtIndex:(long)index;	// 0x34cd7b01
- (unsigned)_lastScrollableIndex;	// 0x34cd5281
- (void)_layoutShelfContents;	// 0x34cd57ed
- (BOOL)_leftButtonEvent;	// 0x34cd5395
- (void)_loadControlWithStartIndex:(long)startIndex start:(BOOL)start;	// 0x34cd722d
- (void)_loadControlsInRange:(NSRange)range;	// 0x34cd7195
- (unsigned)_nextFocusableIndexInDirection:(int)direction;	// 0x34cd52c9
- (long)_numberOfItems;	// 0x34cd7e4d
- (void)_purgeControls;	// 0x34cd5025
- (void)_refillShelf;	// 0x34cd4fad
- (void)_reloadTitles;	// 0x34cd7b99
- (void)_removeSectionHeaderTitleControls;	// 0x34cd7dad
- (BOOL)_restorePersistentSavedSelection;	// 0x34cd772d
- (BOOL)_rightButtonEvent;	// 0x34cd533d
- (BOOL)_scrollInDirection:(int)direction;	// 0x34cd53ed
- (BOOL)_scrollIndexToVisible:(long)visible;	// 0x34cd57b1
- (BOOL)_scrollLeft;	// 0x34cd55bd
- (BOOL)_scrollRight;	// 0x34cd55a5
- (long)_sectionIndexForIndex:(long)index;	// 0x34cd8109
- (id)_setControlRange:(NSRange)range oldRange:(NSRange)range2;	// 0x34cd6edd
- (void)_setDimness:(float)dimness forLayer:(id)layer;	// 0x34cd69d1
- (void)_setFlatRange:(NSRange)range delayedLayout:(BOOL)layout;	// 0x34cd6d01
- (void)_stopForceDisplayTimer;	// 0x34cd76c1
- (id)_titleActions;	// 0x34cd7ca5
- (id)_updateFlatRangeForScrollDirection:(int)scrollDirection;	// 0x34cd6c65
- (void)_updatePersistentSavedSelection;	// 0x34cd784d
- (void)_updateSublayerTransform;	// 0x34cd56b1
- (NSRange)_visibleRange;	// 0x34cd55d5
- (id)accessibilityLabel;	// 0x34cd81bd
- (BOOL)brEventAction:(id)action;	// 0x34cd4761
- (void)cancelContainerViewLoad;	// 0x34cd4f1d
- (int)cellCount;	// 0x34cd4db5
// converted property getter: - (BOOL)centered;	// 0x34cd4715
// converted property getter: - (int)collapsedState;	// 0x34cd4c6d
// declared property getter: - (long)columnCount;	// 0x34cd4f6d
- (void)controlWasActivated;	// 0x34cd42ad
- (void)controlWasDeactivated;	// 0x34cd434d
// declared property getter: - (float)coverflowMargin;	// 0x34cd4f8d
- (long)dataCount;	// 0x34cd4615
// converted property getter: - (id)dataSource;	// 0x34cd45e5
- (void)dealloc;	// 0x34cd41f9
// converted property getter: - (id)delegate;	// 0x34cd4605
- (id)focusedControlForEvent:(id)event focusPoint:(CGPoint *)point;	// 0x34cd4d21
// converted property getter: - (id)focusedIndexPath;	// 0x34cd4ae1
// declared property getter: - (float)horizontalGap;	// 0x34cd4f7d
- (int)indexOfCell:(id)cell;	// 0x34cd4dd5
- (void)layoutSubcontrols;	// 0x34cd4c7d
- (void)loadWithCompletionBlock:(id)completionBlock;	// 0x34cd4e8d
// converted property getter: - (BOOL)ordered;	// 0x34cd4751
- (void)reloadData;	// 0x34cd44cd
// converted property getter: - (BOOL)scrollable;	// 0x34cd46d9
- (void)scrollingCompleted;	// 0x34cd4e55
- (id)selectedControl;	// 0x34cd4c31
// converted property setter: - (void)setCentered:(BOOL)centered;	// 0x34cd46e9
// converted property setter: - (void)setCollapsedState:(int)state;	// 0x34cd4c45
// declared property setter: - (void)setColumnCount:(long)count;	// 0x34cd4465
// declared property setter: - (void)setCoverflowMargin:(float)margin;	// 0x34cd4f9d
// converted property setter: - (void)setDataSource:(id)source;	// 0x34cd4545
// converted property setter: - (void)setDelegate:(id)delegate;	// 0x34cd45f5
// converted property setter: - (void)setFocusedIndexPath:(id)path;	// 0x34cd4b51
// declared property setter: - (void)setHorizontalGap:(float)gap;	// 0x34cd4495
- (void)setIgnoreLoadAndDisplayOnDemand;	// 0x34cd4f49
- (void)setIgnoreLoadAndDisplayOnDemandDisableAnimations:(BOOL)animations;	// 0x34cd4f59
// converted property setter: - (void)setOrdered:(BOOL)ordered;	// 0x34cd4725
- (void)setReadyToDisplay;	// 0x34cd4f45
// converted property setter: - (void)setScrollable:(BOOL)scrollable;	// 0x34cd4699
- (void)visibleScrollRectChanged;	// 0x34cd4df5
@end

