/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library
#import "AppleTV-Structs.h"

@class BRMerchantInfo, NSString;

@interface BRMerchant : NSObject {
@private
	NSString *_boundFeatureName;	// 4 = 0x4
	BRMerchantInfo *info;	// 8 = 0x8
}
@property(readonly, retain) NSString *boundFeatureName;	// G=0x34db11d9; converted property
@property(retain) BRMerchantInfo *info;	// G=0x34db148d; S=0x34db14a5; @synthesize
+ (id)flagstaff;	// 0x34c64705
+ (id)itms;	// 0x34c64685
+ (id)merchantForControl:(id)control;	// 0x34db0fd5
+ (id)merchantForControl:(id)control defaultMerchant:(id)merchant;	// 0x34db0fed
+ (id)merchantForObject:(id)object;	// 0x34db0d99
+ (id)merchantForObject:(id)object defaultMerchant:(id)merchant;	// 0x34db0db1
+ (id)merchantWithIdentifier:(id)identifier;	// 0x34db0d71
+ (void)registerMerchant:(id)merchant withIdentifier:(id)identifier;	// 0x34db0cc1
+ (id)registeredMerchants;	// 0x34db0d51
+ (id)sedona;	// 0x34c646ad
+ (id)thunder;	// 0x34c646d9
- (id)init;	// 0x34db1031
- (id)initWithCoder:(id)coder;	// 0x34db10c5
- (void)_updateMerchantInfo:(id)info;	// 0x34db1411
- (id)accountType;	// 0x34db119d
- (void)assignToControl:(id)control;	// 0x34db12ed
- (BOOL)assignToObject:(id)object;	// 0x34db11e9
- (void)bindToFeature:(id)feature;	// 0x34db11a1
// converted property getter: - (id)boundFeatureName;	// 0x34db11d9
- (Class)catalogAgent;	// 0x34c6472d
- (id)copyWithZone:(NSZone *)zone;	// 0x34db10c1
- (void)dealloc;	// 0x34db10cd
- (id)description;	// 0x34db114d
- (void)encodeWithCoder:(id)coder;	// 0x34db10c9
- (id)evaluatePlist:(id)plist;	// 0x34db140d
- (id)generateRequestForURL:(id)url headers:(id)headers method:(id)method;	// 0x34db131d
- (id)identifier;	// 0x34db1185
// declared property getter: - (id)info;	// 0x34db148d
- (id)localizedStringForKey:(id)key;	// 0x34db13fd
- (id)merchantErrorForError:(id)error;	// 0x34db1409
- (oneway void)release;	// 0x34db10b5
- (id)retain;	// 0x34db10b1
- (unsigned)retainCount;	// 0x34db10b9
// declared property setter: - (void)setInfo:(id)info;	// 0x34db14a5
@end

