/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BROptionDialog.h"

@class BRMediaHost;

__attribute__((visibility("hidden")))
@interface BRMediaHostDisconnectedDialog : BROptionDialog {
@private
	BRMediaHost *_mediaHost;	// 128 = 0x80
	unsigned _timerSatisfied : 1;	// 132 = 0x84
}
@property(retain) BRMediaHost *mediaHost;	// G=0x34d7984d; S=0x34d79815; converted property
- (id)initWithHost:(id)host;	// 0x34d795d9
- (void)_checkHostStatus:(id)status;	// 0x34d798c5
- (void)dealloc;	// 0x34d79749
- (void)goToSources;	// 0x34d7978d
// converted property getter: - (id)mediaHost;	// 0x34d7984d
// converted property setter: - (void)setMediaHost:(id)host;	// 0x34d79815
- (void)wasPushed;	// 0x34d7985d
@end

