/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRMenuView.h"

@class NSString, BRControl, BRTextControl;

@interface BRMediaMenuView : BRMenuView {
@private
	BRControl *_preview;	// 76 = 0x4c
	NSString *_previewLabel;	// 80 = 0x50
	BRControl *_listHeader;	// 84 = 0x54
	BRTextControl *_listErrorText;	// 88 = 0x58
}
@property(retain) BRControl *listHeader;	// G=0x34d5f07d; S=0x34d5f00d; converted property
@property(retain) BRControl *preview;	// G=0x34d5efb5; S=0x34d5ef45; converted property
@property(retain) NSString *previewLabel;	// G=0x34d5effd; S=0x34d5efc5; converted property
- (id)accessibilityLabel;	// 0x34d5f5a5
- (id)accessibilityScreenContent;	// 0x34d5f5c5
- (BOOL)brEventAction:(id)action;	// 0x34d5f1b9
- (void)dealloc;	// 0x34d5eec9
- (void)layoutSubcontrols;	// 0x34d5f229
// converted property getter: - (id)listHeader;	// 0x34d5f07d
// converted property getter: - (id)preview;	// 0x34d5efb5
// converted property getter: - (id)previewLabel;	// 0x34d5effd
- (void)setListErrorText:(id)text;	// 0x34d5f08d
// converted property setter: - (void)setListHeader:(id)header;	// 0x34d5f00d
// converted property setter: - (void)setPreview:(id)preview;	// 0x34d5ef45
// converted property setter: - (void)setPreviewLabel:(id)label;	// 0x34d5efc5
@end

