/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRControl.h"
#import "AppleTV-Structs.h"


__attribute__((visibility("hidden")))
@interface BRMetadataDetailControl : BRControl {
}
- (id)accessibilityLabel;	// 0x34d0513d
- (void)addDetails:(id)details withLabel:(id)label;	// 0x34d04ea5
- (void)layoutSubcontrols;	// 0x34d04f29
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x34d05041
@end

