/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library

@class NSString;

@interface BRMediaHostEvent : NSObject {
@private
	NSString *_description;	// 4 = 0x4
}
@property(readonly, retain) NSString *description;	// G=0x34da635d; converted property
+ (id)mediaHostReady;	// 0x34da5a5d
+ (id)mediaProviderAdded;	// 0x34da587d
+ (id)mediaProviderLoadFailed;	// 0x34da5c3d
+ (id)mediaProviderLoaded;	// 0x34da5b4d
+ (id)mediaProviderRemoved;	// 0x34da596d
+ (id)mediaProviderUnloaded;	// 0x34da5e1d
+ (id)mediaProviderUnloading;	// 0x34da5d2d
+ (id)mount;	// 0x34da5ffd
+ (id)remove;	// 0x34da61dd
+ (id)reset;	// 0x34da5f0d
+ (id)unmount;	// 0x34da60ed
- (id)initWithDescription:(id)description;	// 0x34da62cd
- (void)dealloc;	// 0x34da6319
// converted property getter: - (id)description;	// 0x34da635d
@end

