/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library


__attribute__((visibility("hidden")))
@interface BRMovieRatingStringTransformer : NSValueTransformer {
}
+ (Class)transformedValueClass;	// 0x34dd97f9
- (id)transformedValue:(id)value;	// 0x34dd9819
@end

