/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRSingleton.h"
#import "AppleTV-Structs.h"

@class NSMutableDictionary, NSNumber, NSString, NSTimer, NSArray, NSDictionary;
@protocol BRMediaProvider;

@interface BRMusicStore : BRSingleton {
@private
	int _musicStoreLoadState;	// 4 = 0x4
	NSDictionary *_storeFrontsDictionary;	// 8 = 0x8
	NSDictionary *_storeFrontCodesDictionary;	// 12 = 0xc
	NSNumber *_storeFrontID;	// 16 = 0x10
	NSArray *_rootCollection;	// 20 = 0x14
	NSArray *_partnerData;	// 24 = 0x18
	id<BRMediaProvider> _provider;	// 28 = 0x1c
	BOOL _initializing;	// 32 = 0x20
	NSString *_selectedLanguageCode;	// 36 = 0x24
	NSString *_storeMainMenuPresentsKey;	// 40 = 0x28
	dispatch_queue_s *_urlBagQueue;	// 44 = 0x2c
	NSDictionary *_urlBag;	// 48 = 0x30
	NSTimer *_retryTimer;	// 52 = 0x34
	NSString *_platform;	// 56 = 0x38
	BOOL _initializePlatform;	// 60 = 0x3c
	NSMutableDictionary *_languageIDForLanguageCodeCache;	// 64 = 0x40
}
@property(retain) id currentStoreFrontID;	// G=0x34db1ff9; S=0x34db2411; converted property
@property(assign) int musicStoreLoadState;	// G=0x34db1df5; S=0x34db1e05; converted property
@property(readonly, retain) NSArray *rootCollection;	// G=0x34db3789; converted property
+ (void)setSingleton:(id)singleton;	// 0x34db1bb9
+ (id)singleton;	// 0x34db1bc5
- (id)init;	// 0x34db1bd1
- (id)URLBagEntryForKey:(id)key;	// 0x34db1e55
- (id)_acceptLanguage;	// 0x34db59e9
- (void)_bootstrapMusicStore;	// 0x34db3d1d
- (void)_bootstrapMusicStoreFromURL:(id)url;	// 0x34db3d39
- (id)_canonicalNameForMediaType:(id)mediaType;	// 0x34db3bd9
- (id)_currentStoreFrontsFilePath;	// 0x34db5659
- (id)_defaultStoreFrontsFilePath;	// 0x34db5631
- (id)_determineLanguageCodeForStoreFront:(id)storeFront;	// 0x34db5c69
- (void)_initializeGhostrider;	// 0x34db4e3d
- (BOOL)_initializeMusicStore;	// 0x34db4769
- (void)_initializeSedona;	// 0x34db4fdd
- (id)_languageIDForLanguageCode:(id)languageCode;	// 0x34db5b6d
- (BOOL)_loadRootCollection:(id)collection;	// 0x34db4891
- (void)_networkStateChanged:(id)changed;	// 0x34db50dd
- (void)_requestStoreFrontList;	// 0x34db51cd
- (void)_retryRootCollection:(id)collection;	// 0x34db4e19
- (void)_rootCollectionLoaded:(id)loaded;	// 0x34db4b05
- (void)_seedMusicStore:(id)store;	// 0x34db3e5d
- (BOOL)_seedMusicStoreWithDocument:(id)document;	// 0x34db441d
- (void)_seedRequestProcessed:(id)processed;	// 0x34db4135
- (void)_setCurrentStoreFrontID:(id)anId language:(id)language platform:(id)platform;	// 0x34db5931
- (void)_setRootCollection:(id)collection;	// 0x34db4c0d
- (void)_storeFrontListRequestProcessed:(id)processed;	// 0x34db5301
- (id)_storeFrontsDictionary;	// 0x34db5689
- (id)_storeLanguageID;	// 0x34db5a65
- (void)_storeLoadFailed:(id)failed;	// 0x34db3cad
- (void)_updateStoreFrontFromResponse:(id)response;	// 0x34db506d
- (id)_ytURLDictPath;	// 0x34db29c1
- (id)beaconingPuntRatio;	// 0x34db32dd
- (id)beaconingURLString;	// 0x34db3209
- (id)cacheBusterURLForURL:(id)url;	// 0x34db1ff5
- (id)commonHeaders;	// 0x34db3559
// converted property getter: - (id)currentStoreFrontID;	// 0x34db1ff9
- (id)currentStoreFrontISO3166Code;	// 0x34db225d
- (void)dealloc;	// 0x34db1cd1
- (void)decomposeCompositeStoreFrontHeader:(id)header;	// 0x34db2699
- (void)delayedRootCollectionReset;	// 0x34db3a39
- (id)downloadCapInSecondsSpeedtest;	// 0x34db3061
- (id)downloadMovieSpeedTestURLsArray;	// 0x34db2f8d
- (id)downloadSpeedTestPostResultsURLString;	// 0x34db3135
- (id)downloadSpeedTestURLsArray;	// 0x34db2eb9
- (id)keyValueStoreGetAllURLString;	// 0x34db33b1
- (id)keyValueStorePutAllURLString;	// 0x34db3485
// converted property getter: - (int)musicStoreLoadState;	// 0x34db1df5
- (id)provider;	// 0x34db27c9
- (void)purgeMusicStore;	// 0x34db290d
// converted property getter: - (id)rootCollection;	// 0x34db3789
- (id)rootCollectionForMediaType:(id)mediaType;	// 0x34db3839
// converted property setter: - (void)setCurrentStoreFrontID:(id)anId;	// 0x34db2411
- (void)setCurrentStoreFrontID:(id)anId language:(id)language;	// 0x34db2429
// converted property setter: - (void)setMusicStoreLoadState:(int)state;	// 0x34db1e05
- (id)storeFronts;	// 0x34db3b4d
- (id)storeHeadersDictionary;	// 0x34db3621
- (id)storeHeadersWithDsid;	// 0x34c390b1
- (id)storeMainMenuPresentsURLString;	// 0x34db2b39
- (id)storeRecommendationsURL;	// 0x34db2c19
- (id)storeRelatedMoviesURLString;	// 0x34db2d11
- (id)storeViewMovieURLString;	// 0x34db2de5
- (id)userAgent;	// 0x34db36ed
- (id)vendorBags;	// 0x34db3a15
- (id)ytAuthURLBase;	// 0x34db2a95
- (id)ytURLBase;	// 0x34db29f1
@end

