/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library
#import "BRControlFactory.h"


__attribute__((visibility("hidden")))
@interface BRNowPlayingControlFactory : NSObject <BRControlFactory> {
}
+ (void)_nowPlayingSelected;	// 0x34cf042d
+ (id)factory;	// 0x34ceff3d
- (id)_nowPlayingListItemForData:(id)data currentControl:(id)control;	// 0x34cf0119
- (id)_nowPlayingPosterItemForData:(id)data currentControl:(id)control;	// 0x34cf01bd
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x34ceff7d
@end

