/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class NSString, BRDotArrayControl, BRCursorControl, BRHeaderControl, BRImage, BRImageControl;

@interface BRPageStripView : BRControl {
@private
	id _dataSource;	// 44 = 0x2c
	id _delegate;	// 48 = 0x30
	BRHeaderControl *_headerControl;	// 52 = 0x34
	BRCursorControl *_cursor;	// 56 = 0x38
	BRDotArrayControl *_dotControl;	// 60 = 0x3c
	BRImageControl *_overlayImageControl;	// 64 = 0x40
	BRControl *_descControl;	// 68 = 0x44
	int _selectedIndex;	// 72 = 0x48
	BOOL _initialSetupComplete;	// 76 = 0x4c
	BOOL _reloadOnActivate;	// 77 = 0x4d
	BRControl *_prevPrevControl;	// 80 = 0x50
	BRControl *_prevControl;	// 84 = 0x54
	BRControl *_selectedControl;	// 88 = 0x58
	BRControl *_nextControl;	// 92 = 0x5c
	BRControl *_nextNextControl;	// 96 = 0x60
}
@property(assign, nonatomic) id dataSource;	// G=0x34ce977d; S=0x34ce90c1; @synthesize=_dataSource
@property(assign, nonatomic) id delegate;	// G=0x34ce978d; S=0x34ce979d; @synthesize=_delegate
@property(readonly, assign, nonatomic) BRDotArrayControl *dotControl;	// G=0x34ce97cd; @synthesize=_dotControl
@property(retain, nonatomic) BRImage *headerImage;	// G=0x34ce91bd; S=0x34ce9161; 
@property(retain, nonatomic) BRImage *overlayImage;	// G=0x34ce9101; S=0x34ce90e1; 
@property(assign, nonatomic) int selectedIndex;	// G=0x34ce97ad; S=0x34ce97bd; @synthesize=_selectedIndex
@property(copy, nonatomic) NSString *title;	// G=0x34ce9141; S=0x34ce9121; 
+ (id)pageStripView;	// 0x34ce8e81
- (id)init;	// 0x34ce8eb1
- (BOOL)_loadLeft;	// 0x34ce9c49
- (BOOL)_loadRight;	// 0x34cea19d
- (CGPoint)_nextNextPos;	// 0x34ceaa3d
- (CGPoint)_nextPos;	// 0x34cea9a9
- (CGPoint)_prevPos;	// 0x34cea8a5
- (CGPoint)_prevPrevPos;	// 0x34cea809
- (void)_removeNextNext:(id)next;	// 0x34ceaad5
- (void)_removePrevPrev:(id)prev;	// 0x34ceab11
- (CGPoint)_selectedPos;	// 0x34cea939
- (void)_setPagesTargetBounds;	// 0x34ce97dd
- (float)_xPosOffset;	// 0x34cea715
- (float)_yPosOffset;	// 0x34cea7a9
- (BOOL)brEventAction:(id)action;	// 0x34ce9295
// declared property getter: - (id)dataSource;	// 0x34ce977d
- (void)dealloc;	// 0x34ce8fd9
// declared property getter: - (id)delegate;	// 0x34ce978d
// declared property getter: - (id)dotControl;	// 0x34ce97cd
- (id)focusedControlForEvent:(id)event focusPoint:(CGPoint *)point;	// 0x34ce91dd
// declared property getter: - (id)headerImage;	// 0x34ce91bd
- (void)layoutSubcontrols;	// 0x34ce9675
// declared property getter: - (id)overlayImage;	// 0x34ce9101
- (void)reload;	// 0x34ce93d1
// declared property getter: - (int)selectedIndex;	// 0x34ce97ad
// declared property setter: - (void)setDataSource:(id)source;	// 0x34ce90c1
// declared property setter: - (void)setDelegate:(id)delegate;	// 0x34ce979d
// declared property setter: - (void)setHeaderImage:(id)image;	// 0x34ce9161
// declared property setter: - (void)setOverlayImage:(id)image;	// 0x34ce90e1
// declared property setter: - (void)setSelectedIndex:(int)index;	// 0x34ce97bd
// declared property setter: - (void)setTitle:(id)title;	// 0x34ce9121
// declared property getter: - (id)title;	// 0x34ce9141
@end

