/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class NSString, BRImage;

__attribute__((visibility("hidden")))
@interface BRPairingPinControl : BRControl {
@private
	BRImage *_boxImage;	// 44 = 0x2c
	NSString *_pin;	// 48 = 0x30
}
@property(retain) id PIN;	// G=0x34d2d311; S=0x34d2d1cd; converted property
- (id)init;	// 0x34d2d0cd
// converted property getter: - (id)PIN;	// 0x34d2d311
- (id)_layerForPINDigit:(id)pindigit;	// 0x34d2d4a1
- (id)accessibilityLabel;	// 0x34d2d44d
- (void)dealloc;	// 0x34d2d175
- (void)layoutSubcontrols;	// 0x34d2d321
// converted property setter: - (void)setPIN:(id)pin;	// 0x34d2d1cd
@end

