/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class BRTextControl, BRPasscodeSelectionWidget, NSArray, BRImageControl;

__attribute__((visibility("hidden")))
@interface BRPasscodeSelectionLayer : BRControl {
@private
	NSArray *_backgroundLayers;	// 44 = 0x2c
	NSArray *_digitLayers;	// 48 = 0x30
	NSArray *_bulletLayers;	// 52 = 0x34
	BRImageControl *_arrowsLayer;	// 56 = 0x38
	BRPasscodeSelectionWidget *_selectionWidget;	// 60 = 0x3c
	BRTextControl *_doneLayer;	// 64 = 0x40
	BOOL _isUserEditable;	// 68 = 0x44
	unsigned _numDigits;	// 72 = 0x48
	BOOL _hideDigits;	// 76 = 0x4c
	int _selection;	// 80 = 0x50
}
@property(retain) id passcode;	// G=0x34d8abb9; S=0x34d8aced; converted property
- (id)initWithNumDigits:(unsigned)numDigits userEditable:(BOOL)editable hideDigits:(BOOL)digits;	// 0x34d8a061
- (void)_adjustDigitVisibility:(id)visibility;	// 0x34d8c299
- (CGRect)_arrowsFrameForSelection:(int)selection;	// 0x34d8bbb5
- (id)_buildArrowsLayer;	// 0x34d8b615
- (id)_buildBackgroundLayers;	// 0x34d8b2a5
- (id)_buildBulletLayers;	// 0x34d8b4d9
- (id)_buildDigitLayers;	// 0x34d8b3bd
- (id)_buildDoneLayer;	// 0x34d8b6c1
- (CGRect)_cellFrameForSelection:(int)selection;	// 0x34d8bd81
- (CGRect)_digitFrameForSelection:(int)selection digit:(id)digit;	// 0x34d8bcb1
- (void)_hideDigitAtIndex:(int)index;	// 0x34d8c209
- (float)_layoutUIWithHeight:(float)height;	// 0x34d8b789
- (CGRect)_selectionWidgetFrameForSelection:(int)selection;	// 0x34d8bb11
- (void)_setDigitHighlighted:(BOOL)highlighted atIndex:(int)index;	// 0x34d8c079
- (void)_setDigitValue:(id)value atIndex:(int)index;	// 0x34d8c149
- (void)_setSelection:(int)selection;	// 0x34d8be75
- (id)accessibilityLabel;	// 0x34d8c2f5
- (id)accessibilityTraits;	// 0x34d8c449
- (void)dealloc;	// 0x34d8a2c1
- (BOOL)decrementSelection;	// 0x34d8a8e9
- (BOOL)digitsHidden;	// 0x34d8b0ad
- (BOOL)doneButtonSelected;	// 0x34d8aee1
- (void)hideDigits:(int)digits;	// 0x34d8b0bd
- (BOOL)incrementSelection;	// 0x34d8a6dd
- (BOOL)moveSelectionLeft;	// 0x34d8a60d
- (BOOL)moveSelectionRight;	// 0x34d8a52d
// converted property getter: - (id)passcode;	// 0x34d8abb9
- (CGRect)preferredFrameForScreenSize:(CGSize)screenSize;	// 0x34d8a361
- (void)reset;	// 0x34d8af29
- (void)setFrame:(CGRect)frame;	// 0x34d8afc9
// converted property setter: - (void)setPasscode:(id)passcode;	// 0x34d8aced
- (BOOL)setSelection:(int)selection;	// 0x34d8aae1
- (void)showDigits;	// 0x34d8b199
- (float)widthOfDigitsForScreenSize:(CGSize)screenSize;	// 0x34d8a4ad
@end

