/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRSingleton.h"

@protocol BRRatingInfoDatabase;

@interface BRParentalControlManager : BRSingleton {
@private
	id<BRRatingInfoDatabase> _ratingInfoDatabase;	// 4 = 0x4
}
@property(assign) BOOL accessControlEnabled;	// G=0x34d990e1; S=0x34d9903d; converted property
@property(assign) int accessModeForPurchase;	// G=0x34d99ed1; S=0x34d99e21; converted property
@property(retain) id defaultRatingSystemID;	// G=0x34d99231; S=0x34d991f5; converted property
@property(retain) id pin;	// G=0x34d991bd; S=0x34d99119; converted property
@property(retain) id ratingDatabase;	// G=0x34d992a1; S=0x34d99269; converted property
+ (void)setSingleton:(id)singleton;	// 0x34d99009
+ (id)singleton;	// 0x34d98ffd
+ (BOOL)storeAccessRestricted;	// 0x34d9a1c5
- (id)init;	// 0x34d99015
// converted property getter: - (BOOL)accessControlEnabled;	// 0x34d990e1
- (int)accessModeForAppliance:(id)appliance categoryIdentifier:(id)identifier;	// 0x34d997b9
- (int)accessModeForMediaType:(id)mediaType withRatingSystemID:(id)ratingSystemID withRank:(id)rank;	// 0x34d99c21
// converted property getter: - (int)accessModeForPurchase;	// 0x34d99ed1
- (void)clearAccessModeforAppliance:(id)appliance categoryIdentifier:(id)identifier;	// 0x34d992b1
- (int)computeAccessModeForAppliance:(id)appliance withCategoryIdentifier:(id)categoryIdentifier;	// 0x34d9a38d
- (int)computeAccessModeForAsset:(id)asset;	// 0x34d9a215
- (int)computeAccessModeForPurchase;	// 0x34d9a2e9
- (int)computeAccessModeForPurchaseWithMediaType:(id)mediaType withRatingSystemID:(id)ratingSystemID withRank:(id)rank isExplicit:(BOOL)anExplicit;	// 0x34d9a31d
// converted property getter: - (id)defaultRatingSystemID;	// 0x34d99231
- (int)explicitAccessModeForMediaType:(id)mediaType;	// 0x34d9a09d
// converted property getter: - (id)pin;	// 0x34d991bd
// converted property getter: - (id)ratingDatabase;	// 0x34d992a1
// converted property setter: - (void)setAccessControlEnabled:(BOOL)enabled;	// 0x34d9903d
- (void)setAccessMode:(int)mode forAppliance:(id)appliance categoryIdentifier:(id)identifier;	// 0x34d994a5
- (void)setAccessMode:(int)mode forMediaType:(id)mediaType withRatingSystemID:(id)ratingSystemID withThresholdRank:(id)thresholdRank;	// 0x34d99989
// converted property setter: - (void)setAccessModeForPurchase:(int)purchase;	// 0x34d99e21
// converted property setter: - (void)setDefaultRatingSystemID:(id)anId;	// 0x34d991f5
- (void)setExplicitAccessMode:(int)mode forMediaType:(id)mediaType;	// 0x34d99f19
// converted property setter: - (void)setPin:(id)pin;	// 0x34d99119
// converted property setter: - (void)setRatingDatabase:(id)database;	// 0x34d99269
- (id)thresholdForMediaType:(id)mediaType withRatingSystemID:(id)ratingSystemID;	// 0x34d9a3c9
@end

