/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRDataStoreProvider.h"


@interface BRPhotoDataStoreProvider : BRDataStoreProvider {
}
+ (id)providerWithDataStore:(id)dataStore controlFactory:(id)factory;	// 0x34d6e949
- (id)initWithDataStore:(id)dataStore controlFactory:(id)factory;	// 0x34d6e991
- (void)_updateDataValidity:(id)validity;	// 0x34d6ea59
- (void)dealloc;	// 0x34d6ea05
@end

