/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class NSString, BRTextControl, BRDividerControl, BRImageControl;

__attribute__((visibility("hidden")))
@interface BRPhotoBrowserHeaderControl : BRControl {
@private
	BRTextControl *_titleControl;	// 44 = 0x2c
	BRTextControl *_rightJustifiedTextControl;	// 48 = 0x30
	BRTextControl *_subtitleControl;	// 52 = 0x34
	BRImageControl *_icon;	// 56 = 0x38
	BRDividerControl *_divider;	// 60 = 0x3c
	NSString *_title;	// 64 = 0x40
	long _count;	// 68 = 0x44
	BOOL _displaysCount;	// 72 = 0x48
	float _iconVerticalOffset;	// 76 = 0x4c
}
@property(assign) long count;	// G=0x34d72e15; S=0x34d72dcd; converted property
@property(assign) BOOL displaysCount;	// G=0x34d72e65; S=0x34d72e25; converted property
@property(assign) float dividerBrightness;	// G=0x34d72f9d; S=0x34d72f7d; converted property
@property(retain) BRImageControl *icon;	// G=0x34d72f2d; S=0x34d72ef9; converted property
@property(assign) float iconVerticalOffset;	// G=0x34d72f6d; S=0x34d72f4d; converted property
@property(copy, nonatomic) NSString *rightJustifiedText;	// G=0x34d72d9d; S=0x34d72d49; 
@property(retain) id subtitle;	// G=0x34d72ec9; S=0x34d72e75; converted property
@property(retain) NSString *title;	// G=0x34d72d39; S=0x34d72b95; converted property
- (id)init;	// 0x34d729ad
// converted property getter: - (long)count;	// 0x34d72e15
- (void)dealloc;	// 0x34d72b09
// converted property getter: - (BOOL)displaysCount;	// 0x34d72e65
// converted property getter: - (float)dividerBrightness;	// 0x34d72f9d
// converted property getter: - (id)icon;	// 0x34d72f2d
// converted property getter: - (float)iconVerticalOffset;	// 0x34d72f6d
- (void)layoutSubcontrols;	// 0x34d7305d
- (id)photoBrowserHeader;	// 0x34d7296d
// declared property getter: - (id)rightJustifiedText;	// 0x34d72d9d
// converted property setter: - (void)setCount:(long)count;	// 0x34d72dcd
// converted property setter: - (void)setDisplaysCount:(BOOL)count;	// 0x34d72e25
// converted property setter: - (void)setDividerBrightness:(float)brightness;	// 0x34d72f7d
// converted property setter: - (void)setIcon:(id)icon;	// 0x34d72ef9
// converted property setter: - (void)setIconVerticalOffset:(float)offset;	// 0x34d72f4d
// declared property setter: - (void)setRightJustifiedText:(id)text;	// 0x34d72d49
// converted property setter: - (void)setSubtitle:(id)subtitle;	// 0x34d72e75
// converted property setter: - (void)setTitle:(id)title;	// 0x34d72b95
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x34d72fbd
// converted property getter: - (id)subtitle;	// 0x34d72ec9
// converted property getter: - (id)title;	// 0x34d72d39
@end

