/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRControl.h"
#import "AppleTV-Structs.h"

@class BRImage;

__attribute__((visibility("hidden")))
@interface BRPhotoBrowserCorkBoardControl : BRControl {
@private
	BRImage *_image;	// 44 = 0x2c
}
- (id)init;	// 0x34d733a1
- (void)dealloc;	// 0x34d7346d
- (void)layoutSubcontrols;	// 0x34d734b1
@end

