/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRBaseMediaCollection.h"

@class NSString, NSArray, BRMediaCollectionType;

@interface BRPhotoMediaCollection : BRBaseMediaCollection {
@private
	NSString *_collectionName;	// 8 = 0x8
	NSString *_keyAssetID;	// 12 = 0xc
	NSString *_description;	// 16 = 0x10
	NSArray *_mediaAssets;	// 20 = 0x14
	NSString *_collectionID;	// 24 = 0x18
	BRMediaCollectionType *_collectionType;	// 28 = 0x1c
	double _date;	// 32 = 0x20
	BOOL _dateCalculated;	// 40 = 0x28
}
@property(retain) NSString *collectionID;	// G=0x34ce322d; S=0x34ce32f5; converted property
@property(retain) NSString *collectionName;	// G=0x34ce2c31; S=0x34ce2cf9; converted property
@property(retain) BRMediaCollectionType *collectionType;	// G=0x34ce359d; S=0x34ce35ad; converted property
@property(retain) id date;	// G=0x34ce35bd; S=0x34ce3629; converted property
@property(retain) NSString *description;	// G=0x34ce3091; S=0x34ce3159; converted property
@property(retain) NSString *keyAssetID;	// G=0x34ce2e05; S=0x34ce2ecd; converted property
@property(retain) NSArray *mediaAssets;	// G=0x34ce33c9; S=0x34ce3491; converted property
+ (id)collectionWithCollectionInfo:(id)collectionInfo;	// 0x34ce2a59
- (id)initWithCollectionInfo:(id)collectionInfo;	// 0x34ce2a8d
- (void)_calculateMostRecentDate;	// 0x34ce366d
- (id)archivableCollectionInfo;	// 0x34ce3669
// converted property getter: - (id)collectionID;	// 0x34ce322d
// converted property getter: - (id)collectionName;	// 0x34ce2c31
// converted property getter: - (id)collectionType;	// 0x34ce359d
// converted property getter: - (id)date;	// 0x34ce35bd
- (void)dealloc;	// 0x34ce2ab5
// converted property getter: - (id)description;	// 0x34ce3091
- (unsigned)hash;	// 0x34ce2b41
- (BOOL)isEqual:(id)equal;	// 0x34ce2b79
- (BOOL)isLibrary;	// 0x34ce3665
- (id)keyAsset;	// 0x34ce2fa1
// converted property getter: - (id)keyAssetID;	// 0x34ce2e05
// converted property getter: - (id)mediaAssets;	// 0x34ce33c9
- (id)photoAssets;	// 0x34ce3589
- (id)playbackOptions;	// 0x34ce2e01
// converted property setter: - (void)setCollectionID:(id)anId;	// 0x34ce32f5
// converted property setter: - (void)setCollectionName:(id)name;	// 0x34ce2cf9
// converted property setter: - (void)setCollectionType:(id)type;	// 0x34ce35ad
// converted property setter: - (void)setDate:(id)date;	// 0x34ce3629
// converted property setter: - (void)setDescription:(id)description;	// 0x34ce3159
// converted property setter: - (void)setKeyAssetID:(id)anId;	// 0x34ce2ecd
// converted property setter: - (void)setMediaAssets:(id)assets;	// 0x34ce3491
- (id)title;	// 0x34ce2c1d
@end

