/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRImageProxy.h"
#import <Foundation/Foundation.h> // Unknown library

@class BRPhotoMediaCollection, BRPhotoMediaAsset;

@interface BRPhotoImageProxy : NSObject <BRImageProxy> {
@private
	BRPhotoMediaAsset *_asset;	// 4 = 0x4
	BRPhotoMediaCollection *_collection;	// 8 = 0x8
}
@property(readonly, retain) BRPhotoMediaAsset *asset;	// G=0x34ce13f9; converted property
+ (id)imageProxyWithAsset:(id)asset;	// 0x34ce0e25
+ (id)imageProxyWithCollection:(id)collection;	// 0x34ce0eb9
- (id)initWithAsset:(id)asset;	// 0x34ce0e69
- (id)initWithCollection:(id)collection;	// 0x34ce0efd
// converted property getter: - (id)asset;	// 0x34ce13f9
- (void)cancelImageRequestsForImageSizes:(int)imageSizes;	// 0x34ce1219
- (void)dealloc;	// 0x34ce0fad
- (id)defaultImageForImageSize:(int)imageSize;	// 0x34ce11d1
- (id)imageForImageSize:(int)imageSize;	// 0x34ce1061
- (id)imageIDForImageSize:(int)imageSize;	// 0x34ce1005
- (id)object;	// 0x34ce13d9
- (BOOL)supportsImageForImageSize:(int)imageSize;	// 0x34ce1215
@end

