/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRFullScreenPhotoControllerDelegate.h"
#import "AppleTV-Structs.h"
#import "BRController.h"

@class NSString, NSDateFormatter, BRPhotoBrowserBannerButton, BRPhotoBrowserHeaderControl, BRGridControl, BRTextControl, NSTimer, BRPanelControl, BRCursorControl, BRScrollControl, BRWaitSpinnerControl, NSInvocation;
@protocol BRProvider;

@interface BRPhotoBrowserController : BRController <BRFullScreenPhotoControllerDelegate> {
@private
	id<BRProvider> _provider;	// 60 = 0x3c
	int _style;	// 64 = 0x40
	float _iconVerticalOffset;	// 68 = 0x44
	NSString *_subtitleKey;	// 72 = 0x48
	int _cursorStyle;	// 76 = 0x4c
	BOOL _displaysCount;	// 80 = 0x50
	NSDateFormatter *_formatter;	// 84 = 0x54
	long _providerDataCount;	// 88 = 0x58
	BRPhotoBrowserHeaderControl *_header;	// 92 = 0x5c
	BRGridControl *_grid;	// 96 = 0x60
	BRWaitSpinnerControl *_spinner;	// 100 = 0x64
	BRCursorControl *_cursorControl;	// 104 = 0x68
	BRScrollControl *_scroller;	// 108 = 0x6c
	BRPanelControl *_bannerControl;	// 112 = 0x70
	BRTextControl *_noContentMessageControl;	// 116 = 0x74
	NSTimer *_noContentMessageTimer;	// 120 = 0x78
	BOOL _isNetworkDependent;	// 124 = 0x7c
	BOOL _isValidWithZeroData;	// 125 = 0x7d
	BOOL _useCorkBoardBackground;	// 126 = 0x7e
	NSInvocation *_invocation;	// 128 = 0x80
	BRPhotoBrowserBannerButton *_slideshowButton;	// 132 = 0x84
	BRPhotoBrowserBannerButton *_settingsButton;	// 136 = 0x88
	double noContentErrorDisplayDelay;	// 140 = 0x8c
}
@property(assign) int columnCount;	// G=0x34d70f2d; S=0x34d70eed; converted property
@property(assign) int cursorStyle;	// G=0x34d70ead; S=0x34d70e8d; converted property
@property(assign) BOOL displaysCount;	// G=0x34d70d19; S=0x34d70ce5; converted property
@property(assign) float dividerBrightness;	// G=0x34d70fad; S=0x34d70f8d; converted property
@property(assign) float horizontalGap;	// G=0x34d70f0d; S=0x34d70ecd; converted property
@property(retain) id icon;	// G=0x34d70d6d; S=0x34d70d39; converted property
@property(assign) float iconVerticalOffset;	// G=0x34d70dc1; S=0x34d70d8d; converted property
@property(assign) BOOL isNetworkDependent;	// G=0x34d71371; S=0x34d71361; converted property
@property(assign) BOOL isValidWithZeroData;	// G=0x34d71391; S=0x34d71381; converted property
@property(assign, nonatomic) double noContentErrorDisplayDelay;	// G=0x34d716d1; S=0x34d716e9; @synthesize
@property(copy, nonatomic) NSString *rightJustifiedText;	// G=0x34d70cc5; S=0x34d70ca5; 
@property(assign) int style;	// G=0x34d70bf5; S=0x34d708f9; converted property
@property(retain) id subtitle;	// G=0x34d70e15; S=0x34d70de1; converted property
@property(retain) NSString *subtitleKey;	// G=0x34d70e7d; S=0x34d70e35; converted property
@property(retain) id title;	// G=0x34d70c85; S=0x34d70c05; converted property
@property(assign) float verticalGap;	// G=0x34d70f6d; S=0x34d70f4d; converted property
+ (id)controllerForProvider:(id)provider;	// 0x34d70189
+ (id)controllerForProvider:(id)provider style:(int)style;	// 0x34d701e5
- (id)initWithProvider:(id)provider;	// 0x34d701cd
- (id)initWithProvider:(id)provider style:(int)style;	// 0x34d7022d
- (id)_containerCollection;	// 0x34d71e95
- (void)_focusChanged:(id)changed;	// 0x34d7268d
- (void)_handleProviderDataCountChange;	// 0x34d72105
- (void)_handleSelection:(id)selection;	// 0x34d72281
- (void)_handleSettingsSelection:(id)selection;	// 0x34d725e5
- (void)_handleSlideshowSelection:(id)selection;	// 0x34d72535
- (void)_hideNoContentMessage;	// 0x34d71f95
- (void)_initiateSlideshowPlaybackAtIndex:(long)index inCollection:(id)collection withOptions:(id)options;	// 0x34d72029
- (void)_noContentTimerFired:(id)fired;	// 0x34d71fd1
- (void)_playerStateChanged:(id)changed;	// 0x34d726dd
- (void)_providerUpdated:(id)updated;	// 0x34d726c9
- (void)_setupControls;	// 0x34d71851
- (void)_showNoContentMessage;	// 0x34d71ee9
- (void)_slideshowPlayerAssetChanged:(id)changed;	// 0x34d72769
- (id)_subtitleStringForKey:(id)key;	// 0x34d71cbd
- (id)accessibilityLabel;	// 0x34d71689
- (void)addBannerControl:(id)control;	// 0x34d70fcd
- (BOOL)brEventAction:(id)action;	// 0x34d713e9
// converted property getter: - (int)columnCount;	// 0x34d70f2d
- (void)controlWasActivated;	// 0x34d707a1
- (void)controlWasDeactivated;	// 0x34d70879
// converted property getter: - (int)cursorStyle;	// 0x34d70ead
- (void)dealloc;	// 0x34d705cd
// converted property getter: - (BOOL)displaysCount;	// 0x34d70d19
// converted property getter: - (float)dividerBrightness;	// 0x34d70fad
// converted property getter: - (float)horizontalGap;	// 0x34d70f0d
// converted property getter: - (id)icon;	// 0x34d70d6d
// converted property getter: - (float)iconVerticalOffset;	// 0x34d70dc1
- (id)invocaiton;	// 0x34d713d9
// converted property getter: - (BOOL)isNetworkDependent;	// 0x34d71371
- (BOOL)isValidAfterDataUpdate;	// 0x34d708c5
// converted property getter: - (BOOL)isValidWithZeroData;	// 0x34d71391
- (void)layoutSubcontrols;	// 0x34d71065
// declared property getter: - (double)noContentErrorDisplayDelay;	// 0x34d716d1
- (void)photoPlaybackWillStartForPlayer:(id)photoPlayback;	// 0x34d717c9
// declared property getter: - (id)rightJustifiedText;	// 0x34d70cc5
// converted property setter: - (void)setColumnCount:(int)count;	// 0x34d70eed
// converted property setter: - (void)setCursorStyle:(int)style;	// 0x34d70e8d
// converted property setter: - (void)setDisplaysCount:(BOOL)count;	// 0x34d70ce5
// converted property setter: - (void)setDividerBrightness:(float)brightness;	// 0x34d70f8d
// converted property setter: - (void)setHorizontalGap:(float)gap;	// 0x34d70ecd
// converted property setter: - (void)setIcon:(id)icon;	// 0x34d70d39
// converted property setter: - (void)setIconVerticalOffset:(float)offset;	// 0x34d70d8d
- (void)setInvocation:(id)invocation;	// 0x34d713a1
// converted property setter: - (void)setIsNetworkDependent:(BOOL)dependent;	// 0x34d71361
// converted property setter: - (void)setIsValidWithZeroData:(BOOL)zeroData;	// 0x34d71381
- (void)setLastViewedSlideIndex:(int)index;	// 0x34d716fd
// declared property setter: - (void)setNoContentErrorDisplayDelay:(double)delay;	// 0x34d716e9
- (void)setProvider:(id)provider;	// 0x34d704f1
// declared property setter: - (void)setRightJustifiedText:(id)text;	// 0x34d70ca5
// converted property setter: - (void)setStyle:(int)style;	// 0x34d708f9
// converted property setter: - (void)setSubtitle:(id)subtitle;	// 0x34d70de1
// converted property setter: - (void)setSubtitleKey:(id)key;	// 0x34d70e35
// converted property setter: - (void)setTitle:(id)title;	// 0x34d70c05
// converted property setter: - (void)setVerticalGap:(float)gap;	// 0x34d70f4d
// converted property getter: - (int)style;	// 0x34d70bf5
// converted property getter: - (id)subtitle;	// 0x34d70e15
// converted property getter: - (id)subtitleKey;	// 0x34d70e7d
// converted property getter: - (id)title;	// 0x34d70c85
// converted property getter: - (float)verticalGap;	// 0x34d70f6d
- (void)wasBuried;	// 0x34d70711
- (void)wasExhumed;	// 0x34d70759
@end

