/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRMediaMenuController.h"

@class NSSet;

@interface BRPlaylistsMenuController : BRMediaMenuController {
@private
	NSSet *_mediaTypes;	// 136 = 0x88
}
+ (id)_dataStoreWithMediaTypes:(id)mediaTypes sortDescriptors:(id)descriptors;	// 0x34d7790d
+ (long)playlistCountForMediaTypes:(id)mediaTypes;	// 0x34d77615
- (id)initWithMediaTypes:(id)mediaTypes;	// 0x34d77639
- (id)initWithMediaTypes:(id)mediaTypes resolveArtworkFromParentCollections:(BOOL)parentCollections;	// 0x34d77651
- (id)_dataProviderForController:(id)controller;	// 0x34d77aad
- (void)_itemSelected:(id)selected;	// 0x34d77b59
- (void)_pushControllerForPlaylist:(id)playlist;	// 0x34d77ce1
- (void)_startPlayerWithTrackAtIndex:(long)index tracklist:(id)tracklist shuffle:(BOOL)shuffle list:(id)list;	// 0x34d78071
- (void)dealloc;	// 0x34d778c9
@end

