/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRContainerViewCell.h"
#import "AppleTV-Structs.h"
#import "BRControl.h"
#import "BRPosterImageDataSource.h"
#import "BRMediaShelfViewCell.h"

@class NSString, BRHorizontalSegmentedWidget, BRImage, BRTextControl, BRImageControl, BRAsyncTask, BRPosterReflectionControl, BRAutoScrollingTextControl, BRWaitSpinnerControl;
@protocol BRImageProxy;

@interface BRPosterControl : BRControl <BRMediaShelfViewCell, BRContainerViewCell, BRPosterImageDataSource> {
@private
	int _style;	// 44 = 0x2c
	BRImageControl *_defaultImageControl;	// 48 = 0x30
	BRImage *_defaultImage;	// 52 = 0x34
	BOOL _usingDefaultImage;	// 56 = 0x38
	BRControl *_imageControl;	// 60 = 0x3c
	BRImage *_image;	// 64 = 0x40
	id<BRImageProxy> _imageProxy;	// 68 = 0x44
	int _imageSize;	// 72 = 0x48
	BRHorizontalSegmentedWidget *_numberBadge;	// 76 = 0x4c
	int _numberBadgeValue;	// 80 = 0x50
	CGColorRef _posterBorderColor;	// 84 = 0x54
	float _posterBorderWidth;	// 88 = 0x58
	BOOL _imageRequested;	// 92 = 0x5c
	NSString *_artworkIdentifier;	// 96 = 0x60
	BRAsyncTask *_imageTask;	// 100 = 0x64
	BOOL _imageLoadSuspended;	// 104 = 0x68
	BRPosterReflectionControl *_reflectionControl;	// 108 = 0x6c
	float _reflectionAmount;	// 112 = 0x70
	float _reflectionBaseline;	// 116 = 0x74
	BRTextControl *_ordinalTextControl;	// 120 = 0x78
	BRAutoScrollingTextControl *_autoScrollingTitleControl;	// 124 = 0x7c
	BRTextControl *_subtitleTextControl;	// 128 = 0x80
	float _titleWidthScale;	// 132 = 0x84
	float _titleVerticalOffset;	// 136 = 0x88
	BOOL _alwaysShowTitles;	// 140 = 0x8c
	BOOL _onlyShowSubtitlesWhenFocused;	// 141 = 0x8d
	BRWaitSpinnerControl *_spinnerControl;	// 144 = 0x90
	float _cornerRadius;	// 148 = 0x94
	float _cropAspectRatio;	// 152 = 0x98
	BOOL _autoDownsample;	// 156 = 0x9c
	BOOL _observingBounds;	// 157 = 0x9d
	BOOL _cropAndFill;	// 158 = 0x9e
	BOOL _deletterboxImage;	// 159 = 0x9f
	BRImageControl *_badgeImageControl;	// 160 = 0xa0
	BRImage *_badgeImage;	// 164 = 0xa4
	float _badgeScale;	// 168 = 0xa8
	float _badgeOpacity;	// 172 = 0xac
	float _badgeFocusedOpacity;	// 176 = 0xb0
	int _badgePosition;	// 180 = 0xb4
	BOOL _badgeUpdated;	// 184 = 0xb8
	BRImage *_borderImage;	// 188 = 0xbc
	CGRect _borderImageFocusRect;	// 192 = 0xc0
	CGRect _borderImagePhotoImageRect;	// 208 = 0xd0
	NSString *_accessibilityLabel;	// 224 = 0xe0
	BOOL _decoratedImageCacheEnabled;	// 228 = 0xe4
	BOOL _usingDecoratedImage;	// 229 = 0xe5
	BOOL _imageEdgeAntialiasingEnabled;	// 230 = 0xe6
	id _loadCompletionBlock;	// 232 = 0xe8
	BOOL _readyToDisplay;	// 236 = 0xec
	BOOL _ignoreLoadAndDisplayOnDemand;	// 237 = 0xed
	BOOL _disableAnimations;	// 238 = 0xee
}
@property(retain) NSString *accessibilityLabel;	// G=0x34d66e6d; S=0x34d66f2d; converted property
@property(assign) BOOL alwaysShowTitles;	// G=0x34d6585d; S=0x34d65831; converted property
@property(readonly, retain) BRImage *badgeImage;	// G=0x34d651d5; converted property
@property(assign) float badgeOpacity;	// G=0x34d652a9; S=0x34d6523d; converted property
@property(readonly, assign) int badgePosition;	// G=0x34d651e5; converted property
@property(assign) float badgeScale;	// G=0x34d6522d; S=0x34d651f5; converted property
@property(assign) float cornerRadius;	// G=0x34d65049; S=0x34d65029; converted property
@property(assign) BOOL cropAndFill;	// G=0x34d65099; S=0x34d65059; converted property
@property(assign) float cropAspectRatio;	// G=0x34d650f5; S=0x34d650a9; converted property
@property(retain) BRImage *defaultImage;	// G=0x34d646d5; S=0x34d6465d; converted property
@property(assign) BOOL deletterboxImage;	// G=0x34d65a91; S=0x34d65a81; converted property
@property(assign) float focusedBadgeOpacity;	// G=0x34d65325; S=0x34d652b9; converted property
@property(readonly, retain) BRImage *image;	// G=0x34d65a71; converted property
@property(retain) id imageProxy;	// G=0x34d64be5; S=0x34d64b2d; converted property
@property(assign) int numberBadgeValue;	// G=0x34d655e1; S=0x34d65335; converted property
@property(assign) BOOL onlyShowSubtitlesWhenFocused;	// G=0x34d6587d; S=0x34d6586d; converted property
@property(assign) int ordinal;	// G=0x34d64ec1; S=0x34d64d65; converted property
@property(assign) CGColorRef posterBorderColor;	// G=0x34d6472d; S=0x34d646e5; converted property
@property(assign) float posterBorderWidth;	// G=0x34d64775; S=0x34d6473d; converted property
@property(assign) int posterStyle;	// G=0x34d64b1d; S=0x34d64785; converted property
@property(assign) float reflectionAmount;	// G=0x34d64d0d; S=0x34d64cbd; converted property
@property(assign) float reflectionBaseline;	// G=0x34d64d55; S=0x34d64d1d; converted property
@property(assign) BOOL spinnerEnabled;	// G=0x34d65011; S=0x34d64efd; converted property
@property(retain) id subtitle;	// G=0x34d65a51; S=0x34d6588d; converted property
@property(retain) id title;	// G=0x34d6573d; S=0x34d655f1; converted property
@property(assign) float titleVerticalOffset;	// G=0x34d65821; S=0x34d657e9; converted property
@property(assign) float titleWidthScale;	// G=0x34d657b1; S=0x34d6576d; converted property
+ (void)initialize;	// 0x34d6418d
+ (Class)layerClass;	// 0x34d6416d
+ (id)polaroidPosterWithImageProxy:(id)imageProxy title:(id)title;	// 0x34d64119
+ (id)posterButtonWithImageProxy:(id)imageProxy title:(id)title;	// 0x34d63fe9
+ (id)tilePosterWithImageProxy:(id)imageProxy title:(id)title subtitle:(id)subtitle;	// 0x34d640a1
+ (id)twoLinePosterButtonWithImageProxy:(id)imageProxy title:(id)title subtitle:(id)subtitle;	// 0x34d6403d
- (id)init;	// 0x34d641ed
- (id)_addFadeAnimationToLayer:(id)layer forKey:(id)key;	// 0x34d67e9d
- (id)_artworkIdentifier;	// 0x34d6815d
- (void)_clearCurrentImage;	// 0x34d68255
- (void)_cropImage:(id)image;	// 0x34d68f59
- (id)_currentImage;	// 0x34d676cd
- (CGRect)_currentImageRect;	// 0x34d67821
- (void)_decorateImage:(id)image;	// 0x34d691c1
- (id)_decoratedImageIdentifier:(id)identifier size:(CGSize)size;	// 0x34d69161
- (void)_deletterboxImage:(id)image;	// 0x34d68f09
- (id)_fetchImage;	// 0x34d68531
- (void)_focusWasChanged;	// 0x34d67f71
- (id)_getDecoratedImage:(id)image imageID:(id)anId toSize:(CGSize)size writeToDisk:(BOOL)disk;	// 0x34d69279
- (id)_getImageFromCacheNamed:(id)cacheNamed withSize:(CGSize)size;	// 0x34d68469
- (BOOL)_imageIsCorrectSize:(id)size requiresTask:(BOOL *)task requiresDeletterBox:(BOOL *)box;	// 0x34d6883d
- (void)_imageLoadFailed:(id)failed;	// 0x34d68769
- (BOOL)_imageRequiresCrop;	// 0x34d67495
- (int)_imageSize;	// 0x34d6822d
- (void)_imageTaskComplete:(id)complete;	// 0x34d697d1
- (void)_imageUpdated:(id)updated;	// 0x34d685e5
- (void)_lowMemoryNotification:(id)notification;	// 0x34d682e9
- (CGRect)_mainImageRectFromMainImageUnitRect;	// 0x34d678c1
- (CGRect)_maxImageRect;	// 0x34d676f1
- (id)_numberBadgeAttributes;	// 0x34d681b5
- (id)_ordinalAttributes;	// 0x34d67dad
- (BOOL)_resizeImage:(id)image;	// 0x34d68965
- (void)_restartImageResizing;	// 0x34d6816d
- (void)_scaleImage:(id)image;	// 0x34d69061
- (void)_setArtworkIdentifier:(id)identifier;	// 0x34d68045
- (void)_setAttributedTitle:(id)title withCrossfade:(BOOL)crossfade;	// 0x34d67c79
- (void)_setFinalFormImage:(id)image;	// 0x34d69875
- (void)_startDeletterboxTaskForImage:(id)image;	// 0x34d68da9
- (void)_startImageProcessingTaskForImage:(id)image;	// 0x34d689d9
- (id)_subtitleAttributes;	// 0x34d673b5
- (id)_titleAttributes;	// 0x34d671c9
- (void)_updateDefaultArtwork;	// 0x34d674d9
- (void)_updateDeferredArtwork;	// 0x34d68321
- (void)_updateTextLayerOpacity;	// 0x34d67975
- (NSRange)accessibilityIndexRange;	// 0x34d66f75
// converted property getter: - (id)accessibilityLabel;	// 0x34d66e6d
- (id)accessibilitySecondaryLabel;	// 0x34d66ecd
// converted property getter: - (BOOL)alwaysShowTitles;	// 0x34d6585d
- (id)badge;	// 0x34d67035
// converted property getter: - (id)badgeImage;	// 0x34d651d5
// converted property getter: - (float)badgeOpacity;	// 0x34d652a9
// converted property getter: - (int)badgePosition;	// 0x34d651e5
// converted property getter: - (float)badgeScale;	// 0x34d6522d
- (void)cancelContainerViewLoad;	// 0x34d670ad
- (void)controlWasActivated;	// 0x34d644a5
- (void)controlWasDeactivated;	// 0x34d64555
- (void)controlWasFocused;	// 0x34d65d19
- (void)controlWasUnfocused;	// 0x34d65d55
// converted property getter: - (float)cornerRadius;	// 0x34d65049
// converted property getter: - (BOOL)cropAndFill;	// 0x34d65099
// converted property getter: - (float)cropAspectRatio;	// 0x34d650f5
- (void)dealloc;	// 0x34d642ad
// converted property getter: - (id)defaultImage;	// 0x34d646d5
// converted property getter: - (BOOL)deletterboxImage;	// 0x34d65a91
- (id)description;	// 0x34d64439
- (CGRect)focusCursorFrame;	// 0x34d65aa1
// converted property getter: - (float)focusedBadgeOpacity;	// 0x34d65325
- (void)hideTextLayers;	// 0x34d65d91
// converted property getter: - (id)image;	// 0x34d65a71
// converted property getter: - (id)imageProxy;	// 0x34d64be5
- (BOOL)isAccessibilityElement;	// 0x34d66e69
- (void)layoutSubcontrols;	// 0x34d65de5
- (void)loadWithCompletionBlock:(id)completionBlock;	// 0x34d67045
// converted property getter: - (int)numberBadgeValue;	// 0x34d655e1
// converted property getter: - (BOOL)onlyShowSubtitlesWhenFocused;	// 0x34d6587d
// converted property getter: - (int)ordinal;	// 0x34d64ec1
// converted property getter: - (CGColorRef)posterBorderColor;	// 0x34d6472d
// converted property getter: - (float)posterBorderWidth;	// 0x34d64775
- (id)posterImage;	// 0x34d67145
// converted property getter: - (int)posterStyle;	// 0x34d64b1d
- (float)preferredCursorRadius;	// 0x34d67025
// converted property getter: - (float)reflectionAmount;	// 0x34d64d0d
// converted property getter: - (float)reflectionBaseline;	// 0x34d64d55
// converted property setter: - (void)setAccessibilityLabel:(id)label;	// 0x34d66f2d
// converted property setter: - (void)setAlwaysShowTitles:(BOOL)titles;	// 0x34d65831
- (void)setBadgeImage:(id)image atPosition:(int)position;	// 0x34d65105
// converted property setter: - (void)setBadgeOpacity:(float)opacity;	// 0x34d6523d
// converted property setter: - (void)setBadgeScale:(float)scale;	// 0x34d651f5
// converted property setter: - (void)setCornerRadius:(float)radius;	// 0x34d65029
// converted property setter: - (void)setCropAndFill:(BOOL)fill;	// 0x34d65059
// converted property setter: - (void)setCropAspectRatio:(float)ratio;	// 0x34d650a9
// converted property setter: - (void)setDefaultImage:(id)image;	// 0x34d6465d
// converted property setter: - (void)setDeletterboxImage:(BOOL)image;	// 0x34d65a81
- (BOOL)setEnableDecoratedImageCache:(BOOL)cache;	// 0x34d64bf5
// converted property setter: - (void)setFocusedBadgeOpacity:(float)opacity;	// 0x34d652b9
- (void)setIgnoreLoadAndDisplayOnDemand;	// 0x34d67101
- (void)setIgnoreLoadAndDisplayOnDemandDisableAnimations:(BOOL)animations;	// 0x34d6711d
- (void)setImageEdgeAntialiasingEnabled:(BOOL)enabled;	// 0x34d64c49
// converted property setter: - (void)setImageProxy:(id)proxy;	// 0x34d64b2d
- (void)setImageProxy:(id)proxy withSize:(int)size;	// 0x34d64bc1
- (void)setNonAttributedSubtitle:(id)subtitle;	// 0x34d659ad
- (void)setNonAttributedTitle:(id)title;	// 0x34d65625
- (void)setNonAttributedTitleWithCrossfade:(id)crossfade;	// 0x34d656c9
// converted property setter: - (void)setNumberBadgeValue:(int)value;	// 0x34d65335
// converted property setter: - (void)setOnlyShowSubtitlesWhenFocused:(BOOL)focused;	// 0x34d6586d
// converted property setter: - (void)setOrdinal:(int)ordinal;	// 0x34d64d65
// converted property setter: - (void)setPosterBorderColor:(CGColorRef)color;	// 0x34d646e5
// converted property setter: - (void)setPosterBorderWidth:(float)width;	// 0x34d6473d
// converted property setter: - (void)setPosterStyle:(int)style;	// 0x34d64785
- (void)setReadyToDisplay;	// 0x34d670d5
// converted property setter: - (void)setReflectionAmount:(float)amount;	// 0x34d64cbd
// converted property setter: - (void)setReflectionBaseline:(float)baseline;	// 0x34d64d1d
// converted property setter: - (void)setSpinnerEnabled:(BOOL)enabled;	// 0x34d64efd
// converted property setter: - (void)setSubtitle:(id)subtitle;	// 0x34d6588d
// converted property setter: - (void)setTitle:(id)title;	// 0x34d655f1
// converted property setter: - (void)setTitleVerticalOffset:(float)offset;	// 0x34d657e9
// converted property setter: - (void)setTitleWidthScale:(float)scale;	// 0x34d6576d
- (void)setTitleWithCrossfade:(id)crossfade;	// 0x34d65609
// converted property getter: - (BOOL)spinnerEnabled;	// 0x34d65011
// converted property getter: - (id)subtitle;	// 0x34d65a51
// converted property getter: - (id)title;	// 0x34d6573d
- (id)titleControl;	// 0x34d6575d
// converted property getter: - (float)titleVerticalOffset;	// 0x34d65821
// converted property getter: - (float)titleWidthScale;	// 0x34d657b1
@end

