/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRSingleton.h"

@class BRWindow, NSMutableArray;

@interface BRPopUpManager : BRSingleton {
@private
	NSMutableArray *_queuedPopUps;	// 4 = 0x4
	BRWindow *_popUpContainerWindow;	// 8 = 0x8
	double _lastUpdate;	// 12 = 0xc
}
+ (void)setSingleton:(id)singleton;	// 0x34d9a751
+ (id)singleton;	// 0x34d9a75d
- (id)init;	// 0x34d9a769
- (void)_addControlToQueue:(id)queue;	// 0x34d9b159
- (void)_animateRemovePopupWithIdentifier:(id)identifier;	// 0x34d9ab05
- (BOOL)_canDisplay;	// 0x34d9b0d9
- (void)_displayPopUp:(id)up;	// 0x34d9aec5
- (id)_popUpForIdentifier:(id)identifier;	// 0x34d9b03d
- (void)_processPopUps;	// 0x34d9ae15
- (void)_removeAnimationFinished:(id)finished;	// 0x34d9ad69
- (void)_removeControlFromQueue:(id)queue;	// 0x34d9b1b9
- (void)_removePopup:(id)popup;	// 0x34d9ac95
- (void)_removePopupWithIdentifier:(id)identifier;	// 0x34d9ac5d
- (void)_updateActivity;	// 0x34d9b119
- (void)dealloc;	// 0x34d9a7f5
- (void)postPopUpWithControl:(id)control identifier:(id)identifier position:(unsigned)position size:(CGSize)size options:(id)options;	// 0x34d9a885
- (void)removePopUpWithIdentifier:(id)identifier;	// 0x34d9aaf1
@end

