/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRButtonControl.h"


@interface BRPreviewBrowserControl : BRButtonControl {
}
+ (id)previewBrowser;	// 0x34d2e5b5
- (BOOL)brEventAction:(id)action;	// 0x34d2e639
@end

