/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRSelectionHandler.h"
#import <Foundation/Foundation.h> // Unknown library

@class BRScrollingTextControl;

__attribute__((visibility("hidden")))
@interface BRScrollingTextControlSelectionHandler : NSObject <BRSelectionHandler> {
@private
	BRScrollingTextControl *_control;	// 4 = 0x4
}
- (BOOL)handleSelectionForControl:(id)control;	// 0x34d33b61
- (void)setControl:(id)control;	// 0x34d33b51
@end

