/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRDataStore.h"

@class NSSet, NSString;

@interface BRSeriesDataStore : BRDataStore {
@private
	NSSet *_seriesMediaTypes;	// 40 = 0x28
	NSString *_seriesName;	// 44 = 0x2c
	int _seriesDataStoreType;	// 48 = 0x30
}
+ (id)byDateDataStoreWithTypes:(id)types;	// 0x34dab7e5
+ (id)byMostRecentDataStoreWithTypes:(id)types;	// 0x34dab8c5
+ (id)byShowDataStoreWithTypes:(id)types forSeries:(id)series;	// 0x34dab82d
+ (id)byUnwatchedByMostRecentDataStoreWithTypes:(id)types;	// 0x34dab90d
+ (id)byUnwatchedDataStoreWithTypes:(id)types forSeries:(id)series;	// 0x34dab879
- (id)_aggregateSeries:(id)series aggregate:(id)aggregate sortByDate:(BOOL)date;	// 0x34dabff1
- (id)_filteredSeriesFrom:(id)from;	// 0x34dac419
- (id)_groupEpisodesIntoSeries:(id)series filterOutWatched:(BOOL)watched sortByDate:(BOOL)date;	// 0x34dac551
- (id)_groupSeriesIntoSeasons:(id)seasons filterOutWatched:(BOOL)watched;	// 0x34dac70d
- (void)_handleObjectModifiedForMostRecentUnwatchedDataStore:(id)mostRecentUnwatchedDataStore;	// 0x34dac9ad
- (id)_initWithSeriesTypes:(id)seriesTypes seriesName:(id)name dataStoreType:(int)type;	// 0x34dabf75
- (id)_labelForSeason:(int)season;	// 0x34dac315
- (id)_mediaTypePredicate;	// 0x34dac195
- (id)_primaryCollectionTitlesFromData:(id)data;	// 0x34dac8a5
- (id)_seriesPredicate;	// 0x34dac2bd
- (id)_sortResultsByDate:(id)date;	// 0x34dac365
- (void)addObject:(id)object;	// 0x34daba75
- (void)dealloc;	// 0x34dab955
- (id)hashForData:(id)data;	// 0x34dabe8d
- (id)loadData;	// 0x34dabb8d
- (void)objectModified:(id)modified;	// 0x34dabae5
- (void)removeObject:(id)object;	// 0x34dabb79
- (BOOL)storeAppliesToObject:(id)object;	// 0x34dab9ad
@end

