/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library

@class NSString;

@interface BRSimpleMenuItem : NSObject {
@private
	NSString *_title;	// 4 = 0x4
	NSString *_rightJustifiedText;	// 8 = 0x8
	int _titlePosition;	// 12 = 0xc
	int _menuItemType;	// 16 = 0x10
}
@property(readonly, assign) int menuItemType;	// G=0x34ce487d; converted property
@property(readonly, retain) NSString *rightJustifiedText;	// G=0x34ce485d; converted property
@property(readonly, retain) NSString *title;	// G=0x34ce484d; converted property
@property(readonly, assign) int titlePosition;	// G=0x34ce486d; converted property
+ (id)simpleMenuItemWithTitle:(id)title rightJustifiedText:(id)text titlePosition:(int)position menuItemType:(int)type;	// 0x34ce46f1
+ (id)simpleMenuItemWithTitle:(id)title titlePosition:(int)position menuItemType:(int)type;	// 0x34ce46a5
- (id)initWithTitle:(id)title rightJustifiedText:(id)text titlePosition:(int)position menuItemType:(int)type;	// 0x34ce4765
- (id)initWithTitle:(id)title titlePosition:(int)position menuItemType:(int)type;	// 0x34ce4741
- (void)dealloc;	// 0x34ce47f5
// converted property getter: - (int)menuItemType;	// 0x34ce487d
// converted property getter: - (id)rightJustifiedText;	// 0x34ce485d
// converted property getter: - (id)title;	// 0x34ce484d
// converted property getter: - (int)titlePosition;	// 0x34ce486d
@end

