/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRBaseMenuItemLayerPopulator.h"


@interface BRSimpleMenuItemPopulator : BRBaseMenuItemLayerPopulator {
}
+ (BOOL)canHandleObject:(id)object;	// 0x34d6a345
- (id)menuItem;	// 0x34d6a375
- (id)title;	// 0x34d6a495
@end

