/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRBaseMenuItemLayerPopulator.h"


@interface BRSongMenuItemPopulator : BRBaseMenuItemLayerPopulator {
}
+ (BOOL)canHandleObject:(id)object;	// 0x34d81581
- (id)menuItem;	// 0x34d81625
- (float)menuItemHeightForObject:(id)object delegate:(id)delegate;	// 0x34d8188d
@end

