/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRSyncingMediaHost.h"

@class NSDate;

__attribute__((visibility("hidden")))
@interface BRStreamingMediaHost : BRSyncingMediaHost {
@private
	NSDate *_lastAccessedDate;	// 52 = 0x34
}
+ (id)streamingMediaHostWithHostInfo:(id)hostInfo;	// 0x34da4ef5
- (id)init;	// 0x34da4f31
- (void)dealloc;	// 0x34da4fa1
@end

