/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library

@class NSBundle;

@interface BRSystemLanguages : NSObject {
@private
	NSBundle *_promptBundle;	// 4 = 0x4
}
+ (id)currentLanguage;	// 0x34dd7361
- (id)init;	// 0x34dd71ad
- (id)_promptFileForLang:(id)lang;	// 0x34dd73c9
- (void)dealloc;	// 0x34dd7235
- (id)getLangsAndPrompts:(BOOL)prompts;	// 0x34dd7279
@end

