/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRSingleton.h"

@class NSManagedObjectContext, NSManagedObjectModel, NSArray, NSPersistentStoreCoordinator;

@interface BRTextEntryHistory : BRSingleton {
@private
	NSManagedObjectContext *_managedObjectContext;	// 4 = 0x4
	NSManagedObjectModel *_managedObjectModel;	// 8 = 0x8
	NSPersistentStoreCoordinator *_persistentStoreCoordinator;	// 12 = 0xc
	NSArray *_clientIdentifiers;	// 16 = 0x10
	NSArray *_behaviorIdentifiers;	// 20 = 0x14
	NSArray *_behaviorsCache;	// 24 = 0x18
	NSArray *_historyItemStringsCache;	// 28 = 0x1c
	BOOL _allClientsCached;	// 32 = 0x20
	BOOL _allBehaviorsCached;	// 33 = 0x21
}
@property(readonly, retain) NSManagedObjectContext *managedObjectContext;	// G=0x34d4caf9; converted property
@property(readonly, retain) NSManagedObjectModel *managedObjectModel;	// G=0x34d4cb75; converted property
@property(readonly, retain) NSPersistentStoreCoordinator *persistentStoreCoordinator;	// G=0x34d4cc15; converted property
+ (void)setSingleton:(id)singleton;	// 0x34d4b1f1
+ (id)singleton;	// 0x34d4b1e5
- (id)init;	// 0x34d4b1fd
- (void)_addClient:(id)client behaviors:(id)behaviors maxItemsPerBehavior:(id)behavior;	// 0x34d4b8f5
- (void)_addHistoryItem:(id)item forClient:(id)client;	// 0x34d4c199
- (void)_deleteAllHistoryItemsForClient:(id)client;	// 0x34d4c525
- (void)_deleteAllTextEntryHistory;	// 0x34d4c5e5
- (void)_deleteHistoryItem:(id)item forClient:(id)client;	// 0x34d4c429
- (void)_displayAllTextEntryHistory;	// 0x34d4c755
- (void)_performAction:(int)action withHistoryItem:(id)historyItem forClients:(id)clients textEntryBehaviors:(id)behaviors;	// 0x34d4bddd
- (void)_refreshDataCacheForClients:(id)clients behaviors:(id)behaviors;	// 0x34d4cf39
- (void)_saveContext;	// 0x34d4cdad
- (void)_validateCacheAgainstClientIdentifiers:(id)identifiers behaviorIdentifiers:(id)identifiers2;	// 0x34d4ce21
- (void)dealloc;	// 0x34d4b399
- (void)deleteAllHistoryItemsForClients:(id)clients;	// 0x34d4b625
- (void)deleteAllHistoryItemsForClients:(id)clients textEntryBehaviors:(id)behaviors;	// 0x34d4b5d9
- (void)deleteHistoryItem:(id)item forClients:(id)clients textEntryBehaviors:(id)behaviors;	// 0x34d4b581
- (void)deleteTextEntryBehaviors:(id)behaviors forClients:(id)clients;	// 0x34d4b57d
- (id)historyForClients:(id)clients textEntryBehaviors:(id)behaviors;	// 0x34d4b4b5
// converted property getter: - (id)managedObjectContext;	// 0x34d4caf9
// converted property getter: - (id)managedObjectModel;	// 0x34d4cb75
// converted property getter: - (id)persistentStoreCoordinator;	// 0x34d4cc15
- (void)registerClient:(id)client withTextEntryBehaviors:(id)textEntryBehaviors maxItemsPerBehavior:(id)behavior;	// 0x34d4b449
- (void)setHistoryItem:(id)item forClients:(id)clients textEntryBehaviors:(id)behaviors;	// 0x34d4b511
@end

