/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library

@class NSString;

@interface BRTimer : NSObject {
@private
	BOOL _cancel;	// 4 = 0x4
	NSString *_name;	// 8 = 0x8
	double _interval;	// 12 = 0xc
}
@property(assign) BOOL cancel;	// G=0x34dd7e69; S=0x34dd7e79; @synthesize=_cancel
+ (id)createTimerWithName:(id)name;	// 0x34dd7d71
- (id)initWithName:(id)name;	// 0x34dd7d75
// declared property getter: - (BOOL)cancel;	// 0x34dd7e69
- (void)dealloc;	// 0x34dd7dd5
- (void)reset;	// 0x34dd7e4d
// declared property setter: - (void)setCancel:(BOOL)cancel;	// 0x34dd7e79
@end

