/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class NSArray, BRImageControl;

__attribute__((visibility("hidden")))
@interface BRTrackInfoLayer : BRControl {
@private
	BRControl *_background;	// 44 = 0x2c
	BRImageControl *_art;	// 48 = 0x30
	NSArray *_lines;	// 52 = 0x34
	float _maxLength;	// 56 = 0x38
	long _maxLines;	// 60 = 0x3c
}
- (id)init;	// 0x34d4ece9
- (void)_updateSublayers;	// 0x34d4f421
- (id)accessibilityLabel;	// 0x34d4f409
- (void)dealloc;	// 0x34d4ed8d
- (void)layoutSubcontrols;	// 0x34d4f14d
- (void)setImage:(id)image;	// 0x34d4f085
- (void)setLines:(id)lines withImage:(id)image;	// 0x34d4edf5
- (void)setMaxLines:(long)lines;	// 0x34d4f12d
@end

