/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class BRImageControl;
@protocol BRTumblerDelegate, BRTumblerDataSource;

@interface BRTumblerControl : BRControl {
@private
	id<BRTumblerDataSource> _dataSource;	// 44 = 0x2c
	id<BRTumblerDelegate> _delegate;	// 48 = 0x30
	unsigned _currentIndex;	// 52 = 0x34
	unsigned _itemCount;	// 56 = 0x38
	BRControl *_currentItem;	// 60 = 0x3c
	BRControl *_nextItem;	// 64 = 0x40
	BRControl *_prevItem;	// 68 = 0x44
	BRControl *_nextNextItem;	// 72 = 0x48
	BRControl *_prevPrevItem;	// 76 = 0x4c
	int _tumbleState;	// 80 = 0x50
	BRControl *_nextFade;	// 84 = 0x54
	BRControl *_prevFade;	// 88 = 0x58
	BRControl *_nextBlackout;	// 92 = 0x5c
	BRControl *_prevBlackout;	// 96 = 0x60
	BRImageControl *_nextArrow;	// 100 = 0x64
	BRImageControl *_prevArrow;	// 104 = 0x68
}
@property(readonly, assign, nonatomic) BRControl *currentItem;	// G=0x34d56015; @synthesize=_currentItem
@property(assign, nonatomic) unsigned currentItemIndex;	// G=0x34d55109; S=0x34d55119; 
@property(assign, nonatomic) id<BRTumblerDataSource> dataSource;	// G=0x34d55fe5; S=0x34d556f5; @synthesize=_dataSource
@property(assign, nonatomic) id<BRTumblerDelegate> delegate;	// G=0x34d55ff5; S=0x34d56005; @synthesize=_delegate
- (id)init;	// 0x34d54bad
- (id)_arrowAnimations;	// 0x34d56465
- (id)_controlFromDataSourceAtIndex:(unsigned)index;	// 0x34d56581
- (CGPoint)_currentPos;	// 0x34d56309
- (id)_nextFadeFilters;	// 0x34d56025
- (CGPoint)_nextNextPos;	// 0x34d563ed
- (CGPoint)_nextPos;	// 0x34d5637d
- (id)_prevFadeFilters;	// 0x34d5611d
- (CGPoint)_prevPos;	// 0x34d5628d
- (CGPoint)_prevPrevPos;	// 0x34d56215
- (BOOL)_tumbleNextShouldAnimate:(BOOL)_tumbleNext;	// 0x34d56b39
- (BOOL)_tumblePrevShouldAnimate:(BOOL)_tumblePrev;	// 0x34d565c5
- (id)accessibilityLabel;	// 0x34d570b1
- (void)animationDidStop:(id)animation finished:(BOOL)finished;	// 0x34d55f35
- (BOOL)brEventAction:(id)action;	// 0x34d559f1
// declared property getter: - (id)currentItem;	// 0x34d56015
// declared property getter: - (unsigned)currentItemIndex;	// 0x34d55109
// declared property getter: - (id)dataSource;	// 0x34d55fe5
- (void)dealloc;	// 0x34d55011
// declared property getter: - (id)delegate;	// 0x34d55ff5
- (void)layoutSubcontrols;	// 0x34d55159
- (void)reload;	// 0x34d55715
// declared property setter: - (void)setCurrentItemIndex:(unsigned)index;	// 0x34d55119
// declared property setter: - (void)setDataSource:(id)source;	// 0x34d556f5
// declared property setter: - (void)setDelegate:(id)delegate;	// 0x34d56005
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x34d55141
@end

