/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library

@class BRAsyncTaskContext, NSMutableArray;

@interface BRURLDocumentManager : NSObject {
@private
	NSMutableArray *_activeDocuments;	// 4 = 0x4
	NSMutableArray *_queue;	// 8 = 0x8
	BRAsyncTaskContext *_taskContext;	// 12 = 0xc
}
+ (void)_processCompleteDocuments:(id)documents;	// 0x34ddaa59
+ (void)initialize;	// 0x34dd9fa9
+ (id)textDocumentManager;	// 0x34dd9ff1
- (id)init;	// 0x34dda0cd
- (void)_documentComplete:(id)complete;	// 0x34dda8ed
- (void)_processLoadDocument:(id)document;	// 0x34dda5e5
- (void)_removeActiveDocument:(id)document;	// 0x34dda81d
- (id)_synchronizationObject;	// 0x34dda8dd
- (void)cancelLoad:(id)load;	// 0x34dda4a5
- (void)dealloc;	// 0x34dda17d
- (void)loadDocument:(id)document;	// 0x34dda361
- (void)purgeDocuments;	// 0x34dda21d
@end

