/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRAuthenticator.h"

@class NSString;

@interface BRUserPasswordAuthenticator : BRAuthenticator {
@private
	NSString *_user;	// 8 = 0x8
	NSString *_password;	// 12 = 0xc
}
@property(retain) NSString *password;	// G=0x34d9e6dd; S=0x34d9e6f5; @synthesize=_password
@property(retain) NSString *user;	// G=0x34d9e69d; S=0x34d9e6b5; @synthesize=_user
- (id)initWithAccount:(id)account scope:(unsigned)scope;	// 0x34d9e3d9
- (void)_handleAuthenticationSucceeded;	// 0x34d9e71d
- (void)dealloc;	// 0x34d9e485
- (id)makeAuthenticationController;	// 0x34d9e4dd
// declared property getter: - (id)password;	// 0x34d9e6dd
- (BOOL)requiresPassword:(id *)password;	// 0x34d9e619
- (BOOL)requiresUser:(id *)user;	// 0x34d9e559
// declared property setter: - (void)setPassword:(id)password;	// 0x34d9e6f5
// declared property setter: - (void)setUser:(id)user;	// 0x34d9e6b5
// declared property getter: - (id)user;	// 0x34d9e69d
@end

