/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRControl.h"
#import "AppleTV-Structs.h"

@class BRImageControl;

__attribute__((visibility("hidden")))
@interface BRVerticalScrollBarControl : BRControl {
@private
	BRImageControl *_image;	// 44 = 0x2c
	float _position;	// 48 = 0x30
}
@property(retain) BRImageControl *image;	// G=0x34d32d31; S=0x34d32d11; converted property
- (id)init;	// 0x34d32c35
- (void)dealloc;	// 0x34d32cad
// converted property getter: - (id)image;	// 0x34d32d31
- (void)layoutSubcontrols;	// 0x34d32d51
// converted property setter: - (void)setImage:(id)image;	// 0x34d32d11
- (void)setScrollPosition:(float)position;	// 0x34d32cf1
@end

