/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRController.h"


@interface BRViewController : BRController {
@private
	BRControl *_view;	// 60 = 0x3c
}
@property(retain) BRControl *view;	// G=0x34cdce15; S=0x34cdcd95; converted property
- (void)dealloc;	// 0x34cdcd51
- (void)layoutSubcontrols;	// 0x34cdce25
// converted property setter: - (void)setView:(id)view;	// 0x34cdcd95
// converted property getter: - (id)view;	// 0x34cdce15
@end

