/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import <Foundation/Foundation.h> // Unknown library

@class BRControl;

@interface BRWindow : NSObject {
@private
	BRControl *_content;	// 4 = 0x4
	BRControl *_plane;	// 8 = 0x8
	int _level;	// 12 = 0xc
	BOOL _orderedIn;	// 16 = 0x10
	BOOL _opaque;	// 17 = 0x11
}
@property(assign) BOOL acceptsFocus;	// G=0x34cbed25; S=0x34cbed05; converted property
@property(retain) BRControl *content;	// G=0x34cbeb51; S=0x34cbeab5; converted property
@property(assign) BOOL isOpaque;	// G=0x34cbed45; S=0x34cbecc9; converted property
@property(assign) int level;	// G=0x34cbeba1; S=0x34cbeb61; converted property
@property(readonly, assign, getter=isOrderedIn) BOOL orderedIn;	// G=0x34cbed55; converted property
+ (BOOL)dispatchEvent:(id)event;	// 0x34cbeebd
+ (id)focusedLeafControl;	// 0x34cbeeed
+ (void)initialize;	// 0x34cbe599
+ (CGRect)interfaceFrame;	// 0x34cbe971
+ (CGSize)maxBounds;	// 0x34cbe95d
+ (id)rootLayer;	// 0x34cbed65
+ (void)setMaxBounds:(CGSize)bounds;	// 0x34cbed91
+ (id)window;	// 0x34cbe92d
+ (id)windowList;	// 0x34cbed85
- (id)init;	// 0x34cbe991
- (void)_addWindow:(id)window atIndex:(long)index;	// 0x34cbf1d5
- (id)_controlPlane;	// 0x34cbef15
- (void)_orderWindow:(id)window above:(id)above;	// 0x34cbf135
- (void)_orderWindow:(id)window below:(id)below;	// 0x34cbf099
- (void)_orderWindowBack:(id)back;	// 0x34cbf009
- (void)_orderWindowFront:(id)front;	// 0x34cbef79
- (void)_orderWindowOut:(id)anOut;	// 0x34cbef25
- (void)_updateContent;	// 0x34cbf415
- (void)_updateRenderedWindows;	// 0x34cbf281
// converted property getter: - (BOOL)acceptsFocus;	// 0x34cbed25
// converted property getter: - (id)content;	// 0x34cbeb51
- (void)dealloc;	// 0x34cbea35
// converted property getter: - (BOOL)isOpaque;	// 0x34cbed45
// converted property getter: - (BOOL)isOrderedIn;	// 0x34cbed55
// converted property getter: - (int)level;	// 0x34cbeba1
- (void)orderAbove:(id)above;	// 0x34cbec8d
- (void)orderBack;	// 0x34cbec19
- (void)orderBelow:(id)below;	// 0x34cbec51
- (void)orderFront;	// 0x34cbebe1
- (void)orderOut;	// 0x34cbebb1
// converted property setter: - (void)setAcceptsFocus:(BOOL)focus;	// 0x34cbed05
// converted property setter: - (void)setContent:(id)content;	// 0x34cbeab5
// converted property setter: - (void)setIsOpaque:(BOOL)opaque;	// 0x34cbecc9
// converted property setter: - (void)setLevel:(int)level;	// 0x34cbeb61
@end

