/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRImageProxy.h"
#import <Foundation/Foundation.h> // Unknown library

@class BRXMLMediaAsset;

__attribute__((visibility("hidden")))
@interface BRXMLImageProxy : NSObject <BRImageProxy> {
@private
	BRXMLMediaAsset *_asset;	// 4 = 0x4
}
+ (id)imageProxyForAsset:(id)asset;	// 0x34ce76fd
- (id)initWithAsset:(id)asset;	// 0x34ce773d
- (void)cancelImageRequestsForImageSizes:(int)imageSizes;	// 0x34ce7911
- (void)dealloc;	// 0x34ce778d
- (id)defaultImageForImageSize:(int)imageSize;	// 0x34ce7869
- (id)imageForImageSize:(int)imageSize;	// 0x34ce781d
- (id)imageIDForImageSize:(int)imageSize;	// 0x34ce77d1
- (id)object;	// 0x34ce7915
- (BOOL)supportsImageForImageSize:(int)imageSize;	// 0x34ce78ad
@end

