/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import <Foundation/Foundation.h> // Unknown library

@class NSError, NSLock, CDNDownloadData, NSMutableString, NSString, NSMutableData;

__attribute__((visibility("hidden")))
@interface ContentDownloadData : NSObject {
@private
	BOOL ignore;	// 4 = 0x4
	NSLock *lock;	// 8 = 0x8
	CDNDownloadData *cdn;	// 12 = 0xc
	int downloadableId;	// 16 = 0x10
	unsigned bitRate;	// 20 = 0x14
	unsigned long long expiration;	// 24 = 0x18
	unsigned sortedIndex;	// 32 = 0x20
	int contentProfile;	// 36 = 0x24
	NSString *url;	// 40 = 0x28
	NSString *redirectedUrl;	// 44 = 0x2c
	int state;	// 48 = 0x30
	int error;	// 52 = 0x34
	NSError *nsError;	// 56 = 0x38
	BOOL failed;	// 60 = 0x3c
	int httpStatusCode;	// 64 = 0x40
	double downloadStartTime;	// 68 = 0x44
	double downloadEndTime;	// 76 = 0x4c
	double playlistGenerateStartTime;	// 84 = 0x54
	double playlistGenerateEndTime;	// 92 = 0x5c
	double parseKeyStartTime;	// 100 = 0x64
	double parseKeyEndTime;	// 108 = 0x6c
	NSMutableString *moviePlaylist;	// 116 = 0x74
	int movieDuration;	// 120 = 0x78
	int moviePeakBandwidth;	// 124 = 0x7c
	int movieAverageBandwidth;	// 128 = 0x80
	NSMutableData *contentHeaderData;	// 132 = 0x84
	int contentChunkStart;	// 136 = 0x88
}
@property(readonly, assign, nonatomic) unsigned bitRate;	// G=0x34f13b18; @synthesize
@property(readonly, retain, nonatomic) CDNDownloadData *cdn;	// G=0x34f13b68; @synthesize
@property(readonly, assign, nonatomic) int contentChunkStart;	// G=0x34f13828; @synthesize
@property(readonly, retain, nonatomic) NSMutableData *contentHeaderData;	// G=0x34f13814; @synthesize
@property(readonly, assign, nonatomic) int contentProfile;	// G=0x34f13ac4; @synthesize
@property(assign, nonatomic) double downloadEndTime;	// G=0x34f13988; S=0x34f139a0; @synthesize
@property(assign, nonatomic) double downloadStartTime;	// G=0x34f139b8; S=0x34f139d0; @synthesize
@property(readonly, assign, nonatomic) int downloadableId;	// G=0x34f13b2c; @synthesize
@property(assign, nonatomic) int error;	// G=0x34f13a4c; S=0x34f13a60; @synthesize
@property(readonly, assign, nonatomic) unsigned long long expiration;	// G=0x34f13b00; @synthesize
@property(assign, nonatomic) BOOL failed;	// G=0x34f13a10; S=0x34f13a24; @synthesize
@property(assign, nonatomic) int httpStatusCode;	// G=0x34f139e8; S=0x34f139fc; @synthesize
@property(assign, nonatomic) BOOL ignore;	// G=0x34f13b7c; S=0x34f13b90; @synthesize
@property(assign, nonatomic) NSLock *lock;	// G=0x34f13b40; S=0x34f13b54; @synthesize
@property(assign, nonatomic) int movieAverageBandwidth;	// G=0x34f13850; S=0x34f13864; @synthesize
@property(assign, nonatomic) int movieDuration;	// G=0x34f138a0; S=0x34f138b4; @synthesize
@property(assign, nonatomic) int moviePeakBandwidth;	// G=0x34f13878; S=0x34f1388c; @synthesize
@property(readonly, retain, nonatomic) NSMutableString *moviePlaylist;	// G=0x34f1383c; @synthesize
@property(retain, nonatomic) NSError *nsError;	// G=0x34f13a38; S=0x34f13e68; @synthesize
@property(assign, nonatomic) double parseKeyEndTime;	// G=0x34f138c8; S=0x34f138e0; @synthesize
@property(assign, nonatomic) double parseKeyStartTime;	// G=0x34f138f8; S=0x34f13910; @synthesize
@property(assign, nonatomic) double playlistGenerateEndTime;	// G=0x34f13928; S=0x34f13940; @synthesize
@property(assign, nonatomic) double playlistGenerateStartTime;	// G=0x34f13958; S=0x34f13970; @synthesize
@property(readonly, retain, nonatomic) NSString *redirectedUrl;	// G=0x34f13a9c; @synthesize
@property(assign, nonatomic) unsigned sortedIndex;	// G=0x34f13ad8; S=0x34f13aec; @synthesize
@property(assign, nonatomic) int state;	// G=0x34f13a74; S=0x34f13a88; @synthesize
@property(readonly, retain, nonatomic) NSString *url;	// G=0x34f13ab0; @synthesize
- (id)initWithAuthResponseData:(AuthResponseData *)authResponseData withDownloadId:(unsigned)downloadId withCdn:(id)cdn;	// 0x34f13e9c
// declared property getter: - (unsigned)bitRate;	// 0x34f13b18
// declared property getter: - (id)cdn;	// 0x34f13b68
- (int)compareByDescendingBitRate:(id)rate;	// 0x34f13bc0
// declared property getter: - (int)contentChunkStart;	// 0x34f13828
// declared property getter: - (id)contentHeaderData;	// 0x34f13814
// declared property getter: - (int)contentProfile;	// 0x34f13ac4
- (void)dealloc;	// 0x34f13d78
// declared property getter: - (double)downloadEndTime;	// 0x34f13988
// declared property getter: - (double)downloadStartTime;	// 0x34f139b8
// declared property getter: - (int)downloadableId;	// 0x34f13b2c
// declared property getter: - (int)error;	// 0x34f13a4c
// declared property getter: - (unsigned long long)expiration;	// 0x34f13b00
// declared property getter: - (BOOL)failed;	// 0x34f13a10
// declared property getter: - (int)httpStatusCode;	// 0x34f139e8
// declared property getter: - (BOOL)ignore;	// 0x34f13b7c
// declared property getter: - (id)lock;	// 0x34f13b40
// declared property getter: - (int)movieAverageBandwidth;	// 0x34f13850
// declared property getter: - (int)movieDuration;	// 0x34f138a0
// declared property getter: - (int)moviePeakBandwidth;	// 0x34f13878
// declared property getter: - (id)moviePlaylist;	// 0x34f1383c
// declared property getter: - (id)nsError;	// 0x34f13a38
// declared property getter: - (double)parseKeyEndTime;	// 0x34f138c8
// declared property getter: - (double)parseKeyStartTime;	// 0x34f138f8
// declared property getter: - (double)playlistGenerateEndTime;	// 0x34f13928
// declared property getter: - (double)playlistGenerateStartTime;	// 0x34f13958
// declared property getter: - (id)redirectedUrl;	// 0x34f13a9c
- (void)setContentHeaderData:(id)data withChunkStart:(int)chunkStart;	// 0x34f13d08
// declared property setter: - (void)setDownloadEndTime:(double)time;	// 0x34f139a0
// declared property setter: - (void)setDownloadStartTime:(double)time;	// 0x34f139d0
// declared property setter: - (void)setError:(int)error;	// 0x34f13a60
// declared property setter: - (void)setFailed:(BOOL)failed;	// 0x34f13a24
// declared property setter: - (void)setHttpStatusCode:(int)code;	// 0x34f139fc
// declared property setter: - (void)setIgnore:(BOOL)ignore;	// 0x34f13b90
// declared property setter: - (void)setLock:(id)lock;	// 0x34f13b54
// declared property setter: - (void)setMovieAverageBandwidth:(int)bandwidth;	// 0x34f13864
// declared property setter: - (void)setMovieDuration:(int)duration;	// 0x34f138b4
// declared property setter: - (void)setMoviePeakBandwidth:(int)bandwidth;	// 0x34f1388c
- (void)setMoviePlaylist:(id)playlist;	// 0x34f13cb4
// declared property setter: - (void)setNsError:(id)error;	// 0x34f13e68
// declared property setter: - (void)setParseKeyEndTime:(double)time;	// 0x34f138e0
// declared property setter: - (void)setParseKeyStartTime:(double)time;	// 0x34f13910
// declared property setter: - (void)setPlaylistGenerateEndTime:(double)time;	// 0x34f13940
// declared property setter: - (void)setPlaylistGenerateStartTime:(double)time;	// 0x34f13970
- (void)setRedirectedUrl:(id)url;	// 0x34f13c34
// declared property setter: - (void)setSortedIndex:(unsigned)index;	// 0x34f13aec
// declared property setter: - (void)setState:(int)state;	// 0x34f13a88
// declared property getter: - (unsigned)sortedIndex;	// 0x34f13ad8
// declared property getter: - (int)state;	// 0x34f13a74
// declared property getter: - (id)url;	// 0x34f13ab0
@end

