/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library

@class NSString, NSData;

__attribute__((visibility("hidden")))
@interface DRMData : NSObject {
@private
	NSString *drmSystemID;	// 4 = 0x4
	NSData *data;	// 8 = 0x8
}
+ (void)initialize;	// 0x34de82e8
+ (id)netflixKeyEnvelopeID;	// 0x34de8154
+ (id)playReadyID;	// 0x34de8140
- (id)initWithBuffer:(id)buffer length:(unsigned)length;	// 0x34de820c
- (void)dealloc;	// 0x34de8190
- (id)getDRMSystemID;	// 0x34de8168
- (id)getData;	// 0x34de817c
@end

