/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library

@class NSError, NSURL, NSMutableDictionary, NSString, NSMutableData, NSURLConnection, NSData, NSHTTPURLResponse, NSURLCredential;

__attribute__((visibility("hidden")))
@interface MMRequest : NSObject {
@private
	NSData *_messageBody;	// 4 = 0x4
	NSString *_method;	// 8 = 0x8
	NSURL *_url;	// 12 = 0xc
	NSURL *_originalUrl;	// 16 = 0x10
	NSMutableDictionary *_requestHeaders;	// 20 = 0x14
	NSHTTPURLResponse *_response;	// 24 = 0x18
	NSMutableData *_responseData;	// 28 = 0x1c
	NSURLCredential *_credentials;	// 32 = 0x20
	NSError *_error;	// 36 = 0x24
	NSURLConnection *_connection;	// 40 = 0x28
	BOOL _requestStarted;	// 44 = 0x2c
	BOOL _requestCompleted;	// 45 = 0x2d
}
@property(retain, nonatomic) NSURLConnection *connection;	// G=0x34de1a21; S=0x34de1d69; @synthesize=_connection
@property(retain, nonatomic) NSURLCredential *credentials;	// G=0x34de1a41; S=0x34de1d19; @synthesize=_credentials
@property(retain, nonatomic) NSError *error;	// G=0x34de1a31; S=0x34de1d41; @synthesize=_error
@property(retain, nonatomic) NSData *messageBody;	// G=0x34de1ac1; S=0x34de1c29; @synthesize=_messageBody
@property(retain, nonatomic) NSString *method;	// G=0x34de1ab1; S=0x34de1c51; @synthesize=_method
@property(retain, nonatomic) NSURL *originalUrl;	// G=0x34de1a91; S=0x34de1ca1; @synthesize=_originalUrl
@property(assign, nonatomic) BOOL requestCompleted;	// G=0x34de19e1; S=0x34de19f1; @synthesize=_requestCompleted
@property(retain, nonatomic) NSMutableDictionary *requestHeaders;	// G=0x34de1a81; S=0x34de1cc9; @synthesize=_requestHeaders
@property(assign, nonatomic) BOOL requestStarted;	// G=0x34de1a01; S=0x34de1a11; @synthesize=_requestStarted
@property(retain, nonatomic) NSHTTPURLResponse *response;	// G=0x34de1a71; S=0x34de1cf1; @synthesize=_response
@property(assign, nonatomic) NSMutableData *responseData;	// G=0x34de1a51; S=0x34de1a61; @synthesize=_responseData
@property(retain, nonatomic) NSURL *url;	// G=0x34de1aa1; S=0x34de1c79; @synthesize=_url
- (id)initWithMessage:(id)message usingMethod:(id)method headers:(id)headers url:(id)url;	// 0x34de1ad1
- (void)_cleanUpConnection;	// 0x34de1fa1
- (void)_runRequestThread;	// 0x34de2221
- (id)_urlRequest;	// 0x34de2035
// declared property getter: - (id)connection;	// 0x34de1a21
- (void)connection:(id)connection didFailWithError:(id)error;	// 0x34de1db5
- (void)connection:(id)connection didReceiveAuthenticationChallenge:(id)challenge;	// 0x34de1edd
- (void)connection:(id)connection didReceiveData:(id)data;	// 0x34de1e75
- (void)connection:(id)connection didReceiveResponse:(id)response;	// 0x34de1e61
- (void)connectionDidFinishLoading:(id)connection;	// 0x34de1d91
// declared property getter: - (id)credentials;	// 0x34de1a41
- (void)dealloc;	// 0x34de23d5
// declared property getter: - (id)error;	// 0x34de1a31
- (int)httpStatusCode;	// 0x34de21f1
// declared property getter: - (id)messageBody;	// 0x34de1ac1
// declared property getter: - (id)method;	// 0x34de1ab1
// declared property getter: - (id)originalUrl;	// 0x34de1a91
// declared property getter: - (BOOL)requestCompleted;	// 0x34de19e1
// declared property getter: - (id)requestHeaders;	// 0x34de1a81
// declared property getter: - (BOOL)requestStarted;	// 0x34de1a01
// declared property getter: - (id)response;	// 0x34de1a71
// declared property getter: - (id)responseData;	// 0x34de1a51
- (id)result;	// 0x34de21e1
- (void)sendAsynchronously;	// 0x34de2395
- (void)sendSynchronously;	// 0x34de2339
// declared property setter: - (void)setConnection:(id)connection;	// 0x34de1d69
// declared property setter: - (void)setCredentials:(id)credentials;	// 0x34de1d19
// declared property setter: - (void)setError:(id)error;	// 0x34de1d41
// declared property setter: - (void)setMessageBody:(id)body;	// 0x34de1c29
// declared property setter: - (void)setMethod:(id)method;	// 0x34de1c51
// declared property setter: - (void)setOriginalUrl:(id)url;	// 0x34de1ca1
// declared property setter: - (void)setRequestCompleted:(BOOL)completed;	// 0x34de19f1
// declared property setter: - (void)setRequestHeaders:(id)headers;	// 0x34de1cc9
// declared property setter: - (void)setRequestStarted:(BOOL)started;	// 0x34de1a11
// declared property setter: - (void)setResponse:(id)response;	// 0x34de1cf1
// declared property setter: - (void)setResponseData:(id)data;	// 0x34de1a61
// declared property setter: - (void)setUrl:(id)url;	// 0x34de1c79
- (void)setUsername:(id)username andPassword:(id)password;	// 0x34de213d
- (void)setValue:(id)value forHeader:(id)header;	// 0x34de21a9
// declared property getter: - (id)url;	// 0x34de1aa1
@end

