/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library

@class MMRequest;

__attribute__((visibility("hidden")))
@interface MMTransaction : NSObject {
@private
	MMRequest *_request;	// 4 = 0x4
	BOOL _useSynchronous;	// 8 = 0x8
	BOOL _resultRequired;	// 9 = 0x9
}
@property(retain, nonatomic) MMRequest *request;	// G=0x34de2515; S=0x34de2599; @synthesize=_request
@property(assign, nonatomic) BOOL resultRequired;	// G=0x34de24d5; S=0x34de24e5; @synthesize=_resultRequired
@property(assign, nonatomic) BOOL useSynchronous;	// G=0x34de24f5; S=0x34de2505; @synthesize=_useSynchronous
- (id)initWithRequest:(id)request synchronousFlag:(BOOL)flag resultRequired:(BOOL)required delegate:(id)delegate;	// 0x34de2525
- (void)dealloc;	// 0x34de294d
- (void)dispatch;	// 0x34de28fd
- (int)errorType;	// 0x34de25c1
- (int)httpStatusCode;	// 0x34de27b9
- (BOOL)isSuccessful;	// 0x34de2851
// declared property getter: - (id)request;	// 0x34de2515
- (id)result;	// 0x34de2751
// declared property getter: - (BOOL)resultRequired;	// 0x34de24d5
// declared property setter: - (void)setRequest:(id)request;	// 0x34de2599
// declared property setter: - (void)setResultRequired:(BOOL)required;	// 0x34de24e5
// declared property setter: - (void)setUseSynchronous:(BOOL)synchronous;	// 0x34de2505
- (int)transactionState;	// 0x34de27e1
// declared property getter: - (BOOL)useSynchronous;	// 0x34de24f5
@end

