/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "NSObject.h"


@protocol MSSubscriberDelegate <NSObject>
- (void)subscriber:(id)subscriber didFailToRetriveSubscriptionUpdateWithError:(id)error;
@optional
- (void)subscriber:(id)subscriber didFindDisappearedSubscriptionforStreamID:(id)anId;
- (void)subscriber:(id)subscriber didFinishRequestingAssetRetrievalForStreamID:(id)streamID;
@required
- (void)subscriber:(id)subscriber didFinishRetrievingAsset:(id)asset error:(id)error;
- (void)subscriber:(id)subscriber didRequestAssetRetrievalForAssetCollections:(id)assetCollections streamID:(id)anId;
@optional
- (void)subscriber:(id)subscriber didResetSyncForStreamID:(id)streamID;
- (void)subscriber:(id)subscriber willBeginRequestingAssetRetrievalForStreamID:(id)streamID;
- (void)subscriberDidCompleteCheckForNewAssetCollections:(id)subscriber;
- (void)subscriberDidResetSync:(id)subscriber;
- (void)subscriberWillCheckForNewAssetCollections:(id)subscriber;
@end

