/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import <Foundation/Foundation.h> // Unknown library

@class NSMutableArray, NccpTransactionResult;
@protocol NccpHandlerDelegate;

__attribute__((visibility("hidden")))
@interface NccpCommunicator : NSObject {
@private
	NSObject<NccpHandlerDelegate> *mNccpHandlerDelegate;	// 4 = 0x4
	BOOL mNeedRegister;	// 8 = 0x8
	BOOL mNeedsCredentials;	// 9 = 0x9
	int fujiTarget;	// 12 = 0xc
	unsigned maxDownloadables;	// 16 = 0x10
	unsigned maxCdns;	// 20 = 0x14
	NccpTransactionResult *lastTransactionResult;	// 24 = 0x18
	NSMutableArray *rankedCDNList;	// 28 = 0x1c
	NSMutableArray *nccpRequestMetrics;	// 32 = 0x20
	BOOL mNeedCredentials;	// 36 = 0x24
}
@property(readonly, retain) NccpTransactionResult *lastTransactionResult;	// G=0x34efd0c8; @synthesize
@property(readonly, assign, nonatomic) unsigned maxCdns;	// G=0x34efbf0c; @synthesize
@property(readonly, assign, nonatomic) unsigned maxDownloadables;	// G=0x34efbf20; @synthesize
@property(readonly, assign) BOOL needCredentials;	// G=0x34efbf34; @synthesize=mNeedCredentials
@property(readonly, assign) BOOL needRegister;	// G=0x34efbf48; @synthesize=mNeedRegister
+ (id)NFErrToNWErr:(unsigned)nwerr;	// 0x34efc084
+ (id)NFErrToString:(unsigned)string;	// 0x34efc268
+ (id)buildEsn:(int)esn;	// 0x34efe1b0
+ (void)cleanUp;	// 0x34effb50
+ (BOOL)createWithDelegate:(id)delegate withTarget:(int)target useTestEnv:(BOOL)env withTestNCCPIdentityURL:(id)testNCCPIdentityURL withTestNCCPDataURL:(id)testNCCPDataURL withTestNCCPLoggingURL:(id)testNCCPLoggingURL useStagingNCCP:(BOOL)nccp caFile:(id)file idkey:(id)idkey idvalue:(id)idvalue secretkey:(id)secretkey secretvalue:(id)secretvalue;	// 0x34efcaf8
+ (id)deviceUserAgent;	// 0x34efbde0
+ (void)enableOutputtingOfNCCPTransactionResponse:(BOOL)nccptransactionResponse;	// 0x34efd9a0
+ (void)enterShutdown;	// 0x34efbdb8
+ (const char *)esnPrefix:(int)prefix;	// 0x34efd7f4
+ (id)esnPrefixAsNSString:(int)string;	// 0x34efcc04
+ (void)inactivePurgeSystemDataFiles;	// 0x34efd348
+ (id)instance;	// 0x34efbdf0
+ (BOOL)instantiated;	// 0x34efbe14
+ (BOOL)isNccpLoggingToConsole;	// 0x34efd7e4
+ (void)setDeviceUserAgent:(id)agent;	// 0x34efcd20
+ (void)setNccpLogToConsole:(BOOL)console;	// 0x34efd7c8
+ (void)setOSVersion:(id)version;	// 0x34efdc50
+ (void)setUIVersion:(id)version;	// 0x34efddcc
+ (void)setUniqueIdentifier:(id)identifier;	// 0x34efcd94
+ (id)uniqueIdentifier;	// 0x34efbdd0
- (id)initWithDelegate:(id)delegate;	// 0x34efda8c
- (BOOL)buildRankedCDNList:(AuthResponseData *)list withErrorMsg:(id *)errorMsg;	// 0x34efefcc
- (id)cdnDownloadDataWithCdnId:(unsigned)cdnId;	// 0x34efc654
- (void)cleanUp;	// 0x34efd4c0
- (void)dealloc;	// 0x34efc9c8
- (void)doBookmarkTh;	// 0x34efc844
- (void)doRuntimeTh;	// 0x34efc44c
- (id)extractClientHash:(id)hash;	// 0x34efd148
- (void)fillLicenseResponseData:(LicenseResponseData *)data;	// 0x34efd730
- (int)getAuthorizationET;	// 0x34efbd58
- (unsigned)getBookmark:(unsigned)bookmark;	// 0x34f042a0
- (unsigned)getBookmarkTh:(unsigned)th;	// 0x34efc91c
- (int)getCdnSelectionET;	// 0x34efbda8
- (id)getCurrentMovieTitle;	// 0x34efd9bc
- (unsigned)getDownloadableIdForLicenseReq;	// 0x34efbee4
- (unsigned)getLastTriedAuthMovieId;	// 0x34efbe7c
- (id)getLicense;	// 0x34efbed4
- (int)getLicenseET;	// 0x34efbd68
- (int)getMetaDataET;	// 0x34efbd78
- (id)getNccpRequestMetrics;	// 0x34efbe68
- (int)getNccpRequestMetricsTotalTime;	// 0x34efd5c4
- (id)getRankedCDNList;	// 0x34efbe54
- (int)getRegisterET;	// 0x34efbd88
- (double)getRunTime:(unsigned)time;	// 0x34f0238c
- (unsigned)getRunTimeTh:(unsigned)th;	// 0x34efc530
- (int)getUserMetaDataET;	// 0x34efbd98
- (void)initializeForPlaylistGeneration;	// 0x34efc304
- (void)invalidateAllResponseData;	// 0x34efc994
- (void)invalidateAuthorizationResponseData;	// 0x34efbe2c
- (void)invalidateLicenseResponseData;	// 0x34efc5d8
- (BOOL)is3GPlaybackAllowed;	// 0x34efbe90
// declared property getter: - (id)lastTransactionResult;	// 0x34efd0c8
// declared property getter: - (unsigned)maxCdns;	// 0x34efbf0c
// declared property getter: - (unsigned)maxDownloadables;	// 0x34efbf20
// declared property getter: - (BOOL)needCredentials;	// 0x34efbf34
// declared property getter: - (BOOL)needRegister;	// 0x34efbf48
- (BOOL)netflixIdsMatch:(id)match :(id)arg2;	// 0x34efccb0
- (void)purgeUserRegistration;	// 0x34efd470
- (void)removePreviousUserStoredData;	// 0x34efd55c
- (BOOL)resendAuthorization;	// 0x34efedfc
- (void)saveShopperId;	// 0x34efe51c
- (void)selectCdnByCdnId:(unsigned)anId;	// 0x34efd9fc
- (BOOL)sendAuthorization:(unsigned)authorization trackId:(int)anId withContentProfiles:(id)contentProfiles;	// 0x34f03854
- (BOOL)sendLicense:(id)license;	// 0x34f02988
- (BOOL)sendPing;	// 0x34f006c0
- (BOOL)sendRegister:(id)aRegister;	// 0x34effe7c
- (void)setCDNMeasurementMethod:(int)method;	// 0x34efbec4
- (void)setCDNRankingMethod:(int)method;	// 0x34efbeb4
- (void)setCDNValue:(int)value;	// 0x34efbea4
- (void)setNccpUrls:(int)urls useTestEnv:(BOOL)env withTestNCCPIdentityURL:(id)testNCCPIdentityURL withTestNCCPDataURL:(id)testNCCPDataURL withTestNCCPLoggingURL:(id)testNCCPLoggingURL useStagingNCCP:(BOOL)nccp;	// 0x34f00b4c
- (void)setNeedCredentials;	// 0x34efbef4
- (void)setNeedRegister;	// 0x34efc5a8
- (bool)startNrdpWithServer:(int)server useTestEnv:(BOOL)env withTestNCCPIdentityURL:(id)testNCCPIdentityURL withTestNCCPDataURL:(id)testNCCPDataURL withTestNCCPLoggingURL:(id)testNCCPLoggingURL useStagingNCCP:(BOOL)nccp caFile:(id)file idkey:(id)idkey idvalue:(id)idvalue secretkey:(id)secretkey secretvalue:(id)secretvalue;	// 0x34f00e90
- (void)triggerGetBookmark:(unsigned)bookmark;	// 0x34efc770
- (void)triggerGetRuntime:(unsigned)runtime;	// 0x34efc378
- (BOOL)updateAuthorizationResponseData:(AuthResponseData *)data withErrorMsg:(id *)errorMsg;	// 0x34efc71c
- (BOOL)updateCTicket:(unsigned long long)ticket;	// 0x34f03068
- (BOOL)updateId:(id)anId idvalue:(id)idvalue secretkey:(id)secretkey secretvalue:(id)secretvalue;	// 0x34efe6e8
- (void)updateLicenseResponseData:(LicenseResponseData *)data;	// 0x34efc60c
- (void)updateOSVersion;	// 0x34efe07c
- (void)updateUIVersion;	// 0x34efdf48
@end

