/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library


__attribute__((visibility("hidden")))
@interface NflxhlsStrings : NSObject {
}
+ (void)cleanUp;	// 0x34e09868
+ (id)instance;	// 0x34e098d4
- (id)init;	// 0x34e09984
- (void)dealloc;	// 0x34e09928
- (id)getString:(int)string;	// 0x34e09554
- (id)getStringKey:(int)key;	// 0x34e092dc
- (id)getStringWithAlertErrorCode:(int)alertErrorCode;	// 0x34e095b4
- (void)pseudoLocalize:(BOOL)localize;	// 0x34e094f8
- (void)updateLanguage:(id)language;	// 0x34e092fc
@end

