/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import <Foundation/NSAttributedString.h> // Unknown library


@interface NSAttributedString (Drawing)
- (void)drawAtPoint:(CGPoint)point context:(CGContextRef)context;	// 0x34dd8711
- (void)drawInRect:(CGRect)rect context:(CGContextRef)context;	// 0x34dd873d
- (void)drawInRect:(CGRect)rect withDim:(float)dim context:(CGContextRef)context;	// 0x34dd87a5
- (CGSize)typographicBounds;	// 0x34dd8859
- (CGSize)typographicBoundsWithConstraint:(CGSize)constraint;	// 0x34dd8889
@end

