/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/NSIndexPath.h> // Unknown library


@interface NSIndexPath (NSIndexPathExtensions)
+ (id)indexPathForColumn:(unsigned)column inSection:(unsigned)section;	// 0x34cee74d
+ (id)indexPathForRow:(unsigned)row inSection:(unsigned)section;	// 0x34cee721
- (unsigned)column;	// 0x34cee7a9
- (unsigned)row;	// 0x34cee791
- (unsigned)section;	// 0x34cee779
@end

