/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

//#import <Foundation/NURLRequest.h> // Unknown library

#import <Foundation/Foundation.h>
@interface NSMutableURLRequest (NfhlsProtocol)
- (void)setSpecialVars:(id)vars;	// 0x34df8060
@end

