/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library


__attribute__((visibility("hidden")))
@interface NSMutableURLRequestAdditions : NSObject {
}
+ (id)parametersForRequest:(id)request;	// 0x34e06684
+ (void)setParameters:(id)parameters forRequest:(id)request;	// 0x34e06200
@end

