/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/NSNotification.h> // Unknown library


@interface NSNotification (BRProviderHelpers)
- (id)providerRanges;	// 0x34d873d9
@end

