/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library


__attribute__((visibility("hidden")))
@interface NSURLAdditions : NSObject {
}
+ (id)URLStringQuery:(id)query;	// 0x34e06070
+ (id)URLStringWithoutQuery:(id)query;	// 0x34e06100
@end

