/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library


__attribute__((visibility("hidden")))
@interface OADataFetcher : NSObject {
}
+ (void)fetchDataWithRequest:(id)request delegate:(id)delegate didFinishSelector:(SEL)selector didFailSelector:(SEL)selector4;	// 0x34e05e64
@end

