/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library


__attribute__((visibility("hidden")))
@interface Platform : NSObject {
}
+ (void)initPlatformType;	// 0x34e0f5b0
+ (int)getPlatformType;	// 0x34e0f3c0
+ (void)initialize;	// 0x34e0f3bc
+ (id)platformTypeName;	// 0x34e0f3d0
@end

