/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRProvider.h"
#import <Foundation/Foundation.h> // Unknown library

@class NSArray;
@protocol BRControlFactory;

__attribute__((visibility("hidden")))
@interface RUITrailersProvider : NSObject <BRProvider> {
@private
	NSArray *_trailers;	// 4 = 0x4
	id<BRControlFactory> _factory;	// 8 = 0x8
}
- (id)initWithData:(id)data controlFactory:(id)factory;	// 0x34ca6399
- (id)controlFactory;	// 0x34ca645d
- (id)dataAtIndex:(long)index;	// 0x34ca648d
- (long)dataCount;	// 0x34ca646d
- (void)dealloc;	// 0x34ca6405
- (id)hashForDataAtIndex:(long)index;	// 0x34ca64ad
@end

