/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "SBJsonWriter.h"
#import "SBJsonBase.h"


@protocol SBJsonWriter
@property(assign) BOOL humanReadable;
@property(assign) BOOL sortKeys;
// declared property getter: - (BOOL)humanReadable;
// declared property setter: - (void)setHumanReadable:(BOOL)readable;
// declared property setter: - (void)setSortKeys:(BOOL)keys;
// declared property getter: - (BOOL)sortKeys;
- (id)stringWithObject:(id)object;
@end

__attribute__((visibility("hidden")))
@interface SBJsonWriter : SBJsonBase <SBJsonWriter> {
@private
	BOOL sortKeys;	// 16 = 0x10
	BOOL humanReadable;	// 17 = 0x11
}
@property(assign) BOOL humanReadable;	// G=0x34df6310; S=0x34df6324; @synthesize
@property(assign) BOOL sortKeys;	// G=0x34df6338; S=0x34df634c; @synthesize
+ (void)initialize;	// 0x34df688c
- (BOOL)appendArray:(id)array into:(id)into;	// 0x34df6d6c
- (BOOL)appendDictionary:(id)dictionary into:(id)into;	// 0x34df68f4
- (BOOL)appendString:(id)string into:(id)into;	// 0x34df7038
- (BOOL)appendValue:(id)value into:(id)into;	// 0x34df6360
// declared property getter: - (BOOL)humanReadable;	// 0x34df6310
- (id)indent;	// 0x34df665c
// declared property setter: - (void)setHumanReadable:(BOOL)readable;	// 0x34df6324
// declared property setter: - (void)setSortKeys:(BOOL)keys;	// 0x34df634c
// declared property getter: - (BOOL)sortKeys;	// 0x34df6338
- (id)stringWithFragment:(id)fragment;	// 0x34df6800
- (id)stringWithObject:(id)object;	// 0x34df66bc
@end

