/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <Foundation/Foundation.h> // Unknown library

@class NSLock, NSMutableDictionary, NSMutableArray;

__attribute__((visibility("hidden")))
@interface WSLogging : NSObject {
@private
	NSMutableDictionary *deviceInfoDictionary;	// 4 = 0x4
	NSMutableDictionary *clientInfoDictionary;	// 8 = 0x8
	NSMutableArray *activities;	// 12 = 0xc
	NSMutableArray *wsErrors;	// 16 = 0x10
	NSMutableArray *appErrors;	// 20 = 0x14
	int numItemsQueued;	// 24 = 0x18
	double lastUpdate;	// 28 = 0x1c
	NSLock *queueMutex;	// 36 = 0x24
}
+ (void)cleanUp;	// 0x34e0b1a4
+ (id)instance;	// 0x34e0b1e0
- (id)init;	// 0x34e0b504
- (void)_send;	// 0x34e09a14
- (void)addActivity:(id)activity withHostName:(id)hostName withVersion:(id)version withUUID:(id)uuid withURL:(id)url forAction:(id)action onView:(id)view withStartTime:(long long)startTime withResponseTime:(long long)responseTime;	// 0x34e0a800
- (void)addAppError:(id)error withInfoMessage:(id)infoMessage withException:(id)exception withStacktrace:(id)stacktrace;	// 0x34e09f1c
- (void)addWebServiceError:(id)error withHostName:(id)hostName withVersion:(id)version withUUID:(id)uuid withURL:(id)url forAction:(id)action onView:(id)view withInfoID:(id)infoID withInfoMessage:(id)infoMessage withStatusCode:(id)statusCode withSubCode:(id)subCode;	// 0x34e0a240
- (void)dealloc;	// 0x34e0b234
- (void)flush;	// 0x34e0b4a4
- (void)queueLogItemAndSendIfNecessary;	// 0x34e0b124
- (void)sendWSLoggingIfNecessary;	// 0x34e0b3c4
- (void)setClientInfo:(id)info withHostName:(id)hostName withVersion:(id)version;	// 0x34e0acfc
- (void)setDeviceInfo:(id)info withESN:(id)esn withCertificationVersion:(id)certificationVersion;	// 0x34e0af10
@end

